instructure/instructure-ui

- docs/getting-started/contributing.md
- docs/getting-started/releases.md
update documentation on installation and release process
> update install docs

- packages/emotion/package.json
- packages/emotion/src/useStyle/bidirectionalPolyfill.js
- packages/emotion/src/useStyle/index.js
- packages/ui-docs-client/src/KitchenSink/index.js
proof-of-concept polyfill instead of postcss-bidirection
> WIP(emotion,ui-docs-client): bidirectional polyfill POC

- docs/getting-started/usage.md
just warn users that such tools break instUI currently
> docs(ui-docs-client): add note about removing PropTypes causing issues

- packages/ui-karma-config/lib/index.js
for details see https://webpack.js.org/configuration/devtool/ and https://stackoverflow.com/a/50655297
> chore(ui-karma-config): generate full source maps when running Karma in debug mode

- packages/cz-lerna-changelog/lib/index.js
small fixes based on @HerrTopi 's suggestions in https://github.com/instructure/instructure-ui/pull/258
> chore: make visual change text uppercase; minor refactor

- packages/emotion/src/styleUtils/index.js
- packages/ui-view/src/View/index.js
withStyle decorator needs to properly mirror the components propTypes and default props so it can be
accessed in other components
> withStyle proptypes and defaults fix

- packages/ui-modal/src/Modal/__tests__/Modal.test.js
- packages/ui-modal/src/Modal/index.js
- packages/ui-modal/src/Modal/styles.css
This behaviour was introduced with INSTUI-1105, where it did not serve any special purpose, so it looks like OK to change it
> fix(ui-modal): fix modal resetting contents when size is changed to/from fullscreen

- packages/ui-pagination/package.json
- packages/ui-pagination/src/Pagination/__tests__/Pagination.test.js
- packages/ui-pagination/src/Pagination/index.js
- packages/ui-pagination/src/Pagination/styles.css
- packages/ui-pagination/src/Pagination/styles.js
> WIP(ui-pagination): migrate pagination to emotion styling (Closes: INSTUI-2758)

- packages/canvas-high-contrast-theme/package.json
- packages/canvas-theme/package.json
- packages/instructure-theme/package.json
- packages/ui-theme-tokens/package.json
Fixing the build:tokens script on `next`, same stuff as on https://github.com/instructure/instructure-ui/pull/330
> build:tokens buildfix

- packages/ui-select/package.json
- packages/ui-select/src/Select/__tests__/Select.test.js
- packages/ui-select/src/Select/__tests__/theme.test.js
- packages/ui-select/src/Select/index.js
- packages/ui-select/src/Select/styles.js
- packages/ui-select/src/Select/theme.js
> INSTUI-2752 - migrate Select from themeable to emotion

- .github/workflows/release.yml
Closes: INSTUI-2847
The docs deploy script ran on every push to master. It only should run on release commit pushes
TEST PLAN:
Push a release and a non release commit to master. On release commit, the "Deploy" job should run,
otherwise it should not
> fix: fix release script (INSTUI-2847)

- packages/ui-modal/src/Modal/__tests__/Modal.test.js
- packages/ui-modal/src/Modal/index.js
- packages/ui-modal/src/Modal/styles.js
- packages/ui-overlays/src/Mask/index.js
…changed to/from fullscreen
Closes: INSTUI-2842
> INSTUI-2842 - implement modal fix on next branch

- packages/__docs__/index.ejs
- packages/__docs__/plugins.js
- packages/ui-docs-plugin/package.json
- packages/ui-docs-plugin/src/index.js
- yarn.lock
> fix(ui-docs-plugin): fix favicon (INSTUI-2837)

- packages/babel-plugin-transform-imports/lib/index.js
- packages/ui-buttons/src/ToggleButton/ToggleButtonLocator.js
- packages/ui-calendar/src/index.js
- packages/ui-date-input/src/DateInput/DateInputLocator.js
- packages/ui-docs-plugin/src/index.js
- packages/ui-menu/src/Menu/MenuLocator.js
- packages/ui-navigation/src/Navigation/NavigationItem/NavigationItemLocator.js
- packages/ui-options/src/index.js
- packages/ui-pagination/src/Pagination/PaginationArrowButton/PaginationArrowButtonLocator.js
- packages/ui-pill/src/Pill/PillLocator.js
- packages/ui-popover/src/Popover/PopoverLocator.js
- packages/ui-popover/src/index.js
- packages/ui-position/src/index.js
- packages/ui-select/src/Select/SelectLocator.js
- packages/ui-select/src/index.js
- packages/ui-simple-select/src/SimpleSelect/SimpleSelectLocator.js
- packages/ui-time-select/src/TimeSelect/TimeSelectLocator.js
- packages/ui-tooltip/src/Tooltip/TooltipLocator.js
- packages/ui-tooltip/src/index.js
- packages/ui-webpack-config/config/module/rules.js
- yarn.lock
Sadly I could not get .mjs build to work, but I found a couple of build pipeline issues meanwhile
> INSTUI-2852 Fix bundle build, build pipeline fixes

- packages/ui-docs-client/src/Properties/index.js
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/index.js
- packages/ui-drawer-layout/src/DrawerLayout/index.js
- packages/ui-i18n/package.json
- packages/ui-i18n/src/ApplyTextDirection/__tests__/ApplyTextDirection.test.js
- packages/ui-i18n/src/__tests__/bidirectional.test.js
- packages/ui-i18n/src/bidirectional.js
- packages/ui-popover/src/Popover/index.js
- packages/ui-portal/src/Portal/ReactPortal.js
- packages/ui-portal/src/Portal/SubtreePortal.js
- packages/ui-tabs/src/Tabs/index.js
- packages/ui-tray/src/Tray/index.js
- packages/ui-view/src/View/index.js
- packages/ui-view/src/View/styles.js
- yarn.lock
…y,ui-view): refactor `bidirecti
Closes: INSTUI-2845
> INSTUI-2845 - Fix Bidirectional Context Issue 

- packages/ui-avatar/src/Avatar/README.md
- packages/ui-buttons/src/Button/README.md
- packages/ui-heading/src/Heading/README.md
- packages/ui-img/src/Img/README.md
- packages/ui-view/src/View/README.md
…de guides
Closes: INSTUI-2872
> INSTUI-2872 - remove v8 upgrade notes from docs

- packages/ui-scripts/lib/bump.js
- packages/ui-scripts/lib/utils/git.js
> chore(ui-scripts): add tags to bump script (INSTUI-2881)

- packages/ui-webpack-config/package.json
- yarn.lock
Its also used by ui-scripts/package.json by @codesandbox/common": "^1.0.8, but this is its latest version, I've left a comment to nag them codesandbox/codesandbox-client#5384
Fixes #409
> INSTUI-2890: update react-dev-utils to update immer on Master

- .github/scripts/calculateVersion.sh
- .github/workflows/release.yml
- packages/ui-scripts/lib/bump.js
- packages/ui-scripts/lib/utils/git.js
> chore(ui-scripts): update workflow to include tagging (NSTUI-2896)

- packages/ui-buttons/src/Button/__examples__/Button.examples.js
- packages/ui-component-examples/README.md
- packages/ui-component-examples/lib/generateComponentExamples.js
- packages/ui-drawer-layout/src/DrawerLayout/__examples__/DrawerLayout.examples.js
- packages/ui-menu/src/Menu/__examples__/Menu.examples.js
- packages/ui-popover/src/Popover/__examples__/Popover.examples.js
- packages/ui-select/src/Select/__examples__/Select.examples.js
- packages/ui-text-area/src/TextArea/__examples__/TextArea.examples.js
- packages/ui-text-area/src/TextArea/index.js
- packages/ui-text/src/Text/__examples__/Text.examples.js
- packages/ui-view/src/View/__examples__/View.examples.js
now they don't generate too many examples that result in errors.
> Update Storybook examples

- docs/guides/v7-deprecated-props-and-components.md
- packages/ui-focusable/src/FocusableView/index.js
Closes: INSTUI-2906
We wanted to provide a list of properties and components that are deprecated in v7, and will be
completely deleted in v8.0. Since the v8 release will bring many huge changes in itself, this is how
we want to make the upgrade easier.
> INSTUI-2906 - docs: add v7 deprecations docs

- docs/guides/themeable-to-emotion-migration-guide.md
- docs/guides/v8-upgrade-guide.md
This is a follow-up update for [Make a table of the deleted props in V8](https://instructure.atlassian.net/browse/INSTUI-2906)  ticket (PR: https://github.com/instructure/instructure-ui/pull/434)
> docs: update v8 migration docs

- packages/ui-tree-browser/package.json
- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/__tests__/TreeButton.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/styles.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/__tests__/TreeCollection.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/__tests__/TreeNode.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/index.js
- packages/ui-tree-browser/src/TreeBrowser/__tests__/TreeBrowser.test.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
port of the 7.x PR https://github.com/instructure/instructure-ui/pull/398
TEST PLAN:
- tests are passing
- tested in docs client
> INSTUI-2885: ui-tree-browser: can render custom items before and after collections

- docs/getting-started/api-guidelines.md
> docs: update API Guidelines docs with emotion conventions

- packages/ui-docs-client/src/Header/index.js
> INSTUI-2914 - add link to previous version of docs

- docs/guides/themeable-to-emotion-migration-guide.md
- packages/emotion/README.md
- packages/ui-code-editor/src/CodeEditor/index.js
- packages/ui-code-editor/src/CodeEditor/styles.js
- packages/ui-docs-client/src/App/index.js
- packages/ui-docs-client/src/App/styles.js
- packages/ui-motion/src/Transition/index.js
- packages/ui-motion/src/Transition/styles.js
Closes: INSTUI-2919
Added docs and migration guide for emotion's `Global` component and `keyframe` helper.
> INSTUI-2919 - add docs about emotion's `Global` and `keyframes`

- .github/workflows/manual-deploy-to-legacy-gh-pages.yml
> chore(instui-config): add manual deploy-to-gh-pages to github workflows (INSTUI-2929)

- packages/__examples__/babel.config.js
- packages/ui-babel-preset/lib/babel-plugin-add-displayname-for-react.js
- packages/ui-babel-preset/lib/index.js
- packages/ui-react-utils/src/getDisplayName.js
it was caused by minification/uglyfication
> Fix displayName set to null and weird values in prod

- packages/ui-navigation/src/AppNav/__tests__/AppNav.test.js
- packages/ui-navigation/src/AppNav/index.js
fix(ui-navigation): fix AppNav crashing with a single Item
test(ui-navigation): write test for single item AppNav
Closes: INSTUI-2958
> INSTUI-2958 - fix AppNav crashing with a single Item

- packages/ui-simple-select/src/SimpleSelect/Option/index.js
- packages/ui-simple-select/src/SimpleSelect/index.js
> feat(ui-simple-select): add number value option to simple-select ( INSTUI-2962 )

- packages/ui-select/src/Select/index.js
Same as https://github.com/instructure/instructure-ui/pull/464 just for v7
> fix(ui-select): fix exception when selecting all items and clicking outside

- docs/patterns/DrilldownMenu.md
> docs: add example pattern about the drilldown component

- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/styles.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/index.js
Closes: INSTUI-2949
Removed dash at any root level icon (TreeButton or TreeNode).
> INSTUI-2949 - remove dash at root icon

- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/__tests__/TreeCollection.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
> feat(ui-tree-browser): Add new getCollectionProps

- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/styles.css
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/index.js
Removed dash at any root level icon (TreeButton or TreeNode).
Closes: INSTUI-2977
> INSTUI-2977 - tree browser remove dash at root icon

- .github/workflows/vrt.yml
- packages/ui-drawer-layout/src/DrawerLayout/__examples__/DrawerLayout.examples.js
Added v7_maintenance branch to the vrt worflow, so chromatic tests run on push events and PR-s.
> chore: add vrt checks on v7_maintenance branch

- .github/workflows/manual-release-to-npm-and-deploy-to-legacy-gh-pages.yml
- .github/workflows/manual-release-to-npm.yml
- packages/ui-scripts/lib/fix-publish.js
- packages/ui-scripts/lib/publish.js
> chore(ui-scripts): fix release tagging on npm (INSTUI-2979)

- packages/ui/package.json
- packages/ui/src/index.js
> INSTUI-2995 - export `EmotionThemeProvider` and `withStyle` from ui package

- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/styles.js
> INSTUI-2994 - fix root item rendering with wrong fontFamily

- packages/emotion/package.json
- packages/emotion/src/EmotionThemeProvider/index.js
- packages/emotion/src/index.js
- packages/emotion/src/useTheme.js
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/styles.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/styles.js
- yarn.lock
Closes: INSTUI-2960
Fix keyframe syntax error in TreeButton and TreeCollection
> chore(emotion,ui-tree-browser): upgrade to emotion 11.0.0 (INSTUI-2960)

- packages/ui-number-input/src/NumberInput/__examples__/NumberInput.examples.js
- packages/ui-number-input/src/NumberInput/__tests__/NumberInput.test.js
- packages/ui-number-input/src/NumberInput/index.js
Closes: NSTUI-3001
This will be put on the underlying input field to hint at intended usage
> feat(ui-number-input): add inputMode prop to NumberInput (NSTUI-3001)

- packages/ui-scripts/README.md
> docs(ui-scripts): fix docs for ui-scripts (INSTUI-3005)

- docs/patterns/DrilldownMenu.md
> INSTUI-3010 - simplify Drilldown Menu example

- packages/ui-themes/babel.config.js
> INSTUI-3092 - ui-themes TS migration

- packages/ui-number-input/src/NumberInput/__examples__/NumberInput.examples.js
- packages/ui-number-input/src/NumberInput/__tests__/NumberInput.test.js
- packages/ui-number-input/src/NumberInput/index.js
Closes: INSTUI-3016
This will be put on the underlying input field to hint at intended usage
> feat(ui-number-input): add inputMode prop to NumberInput

- packages/ui-babel-preset/lib/index.js
see https://babeljs.io/docs/en/babel-plugin-proposal-class-properties#loose and
https://babeljs.io/docs/en/assumptions#setpublicclassfields
> INSTUI-3104 : fix Babel warning during build, update to newer syntax

- packages/ui-select/src/Select/README.md
> docs(ui-select): fix multiselect example (INSTUI-3019)

- package.json
- packages/__docs__/package.json
> docs: fix wrong binaries served for the legacy docs codepens

- packages/__docs__/babel.config.js
- packages/ui-scripts/package.json
Fixes the missing icon fonts on Iconography page.
Also contains small fix in `ui-scripts` package json, merging the 2 devDependencies blocks.
> INSTUI-3109 - iconfonts missing

- packages/ui-color-utils/babel.config.js
- packages/ui-color-utils/package.json
- packages/ui-color-utils/src/alpha.ts
- packages/ui-color-utils/src/contrast.ts
- packages/ui-color-utils/src/conversions.ts
- packages/ui-color-utils/src/darken.ts
- packages/ui-color-utils/src/isValid.ts
- packages/ui-color-utils/src/lighten.ts
- yarn.lock
> chore(ui-color-utils): tS types for `ui-color-utils` package

- package.json
- yarn.lock
> chore: upgrade packages with  minor and patch changes (INSTUI-3003)

- packages/ui-text-input/package.json
- packages/ui-text-input/src/TextInput/index.tsx
- packages/ui-text-input/src/TextInput/styles.ts
Closes: INSTUI-3135
Flex is a heavy weight component based on View, use a simple span instead for better performance.
> perf(ui-text-input): replace Flex with styled spans

- docs/patterns/DrilldownMenu.md
Closes: INSTUI-3158
When the `Drilldown` is open, it shold close if `Tab` is pressed.
> feat: add "tabbing out" logic to the `Drilldown Menu` pattern

- packages/ui-popover/src/Popover/index.tsx
> fix(ui-popover): inverse color Popover without arrow shouldn't have light border

- packages/ui-menu/src/Menu/__tests__/Menu.test.tsx
- packages/ui-menu/src/Menu/index.tsx
> feat(ui-menu): propagate offset props from `Menu` to `Popover`

- packages/__docs__/index.ejs
- packages/ui-docs-client/src/App/index.js
- packages/ui-docs-client/src/App/styles.css
- packages/ui-docs-client/src/Header/index.js
- packages/ui-docs-client/src/versionData.js
Closes: INSTUI-3185
If someone is viewing the docs page of a legacy version, we want to display a warning on the bottom
of the page.
> INSTUI-3185 - warning stripe on legacy doc pages

- packages/ui-docs-client/package.json
- packages/ui-docs-client/src/App/index.js
- packages/ui-docs-client/src/App/styles.css
- packages/ui-docs-client/src/Header/index.js
- packages/ui-docs-client/src/versionData.js
- yarn.lock
refs: INSTUI-3186
If someone is viewing the docs page of a legacy version, we want to display a warning on the bottom
of the page.
> INSTUI-3186 - add warning stripe on legacy doc pages

- packages/debounce/src/debounce.ts
- packages/ui-dom-utils/src/findDOMNode.ts
- packages/ui-dom-utils/src/getComputedStyle.ts
- packages/ui-dom-utils/src/getFontSize.ts
- packages/ui-dom-utils/src/matchMedia.ts
- packages/ui-responsive/babel.config.js
- packages/ui-responsive/src/QueryType.ts
- packages/ui-responsive/src/Responsive/__tests__/Responsive.test.tsx
- packages/ui-responsive/src/Responsive/index.tsx
- packages/ui-responsive/src/ResponsivePropTypes.ts
- packages/ui-responsive/src/addElementQueryMatchListener.ts
- packages/ui-responsive/src/addMediaQueryMatchListener.ts
- packages/ui-responsive/src/jsonToMediaQuery.ts
- packages/ui-responsive/src/parseQuery.ts
> chore(ui-responsive): add TS types to `ui-responsive` package

- packages/__docs__/src/Icons/index.js
- packages/__docs__/src/Nav/index.js
- packages/ui-i18n/package.json
> chore(ui-i18n): make docs search more fluid

- packages/__examples__/.storybook/stories/generateComponentExamples.js
- packages/__examples__/.storybook/stories/stories.js
- packages/__examples__/buildScripts/__tests__/generateComponentExamples.test.ts
- packages/ui-alerts/src/Alert/__examples__/Alert.examples.ts
- packages/ui-flex/src/Flex/__examples__/Flex.examples.tsx
- packages/ui-flex/src/Flex/index.tsx
- packages/ui-text-input/src/TextInput/__examples__/TextInput.examples.tsx
story generation is much faster, now it does not hang/take minutes on some components. These were generating 0 stories, so there will be Chromatic diffs.
Better error messages when a story cannot be generated, that includes a stack trace
> INSTUI-3215: Make storybook story generation better

- packages/__docs__/src/Document/index.js
- packages/__docs__/src/Figure/index.js
- packages/__docs__/src/Properties/index.js
- packages/__docs__/src/Properties/styles.js
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/index.tsx
- packages/ui-i18n/src/ApplyLocale/index.tsx
- packages/ui-i18n/src/ApplyTextDirection/index.tsx
- packages/ui-modal/src/Modal/index.tsx
- packages/ui-overlays/src/Overlay/index.tsx
- packages/ui-portal/src/Portal/index.tsx
- packages/ui-portal/src/index.ts
- packages/ui-responsive/src/Responsive/index.tsx
- packages/ui-tray/src/Tray/index.tsx
> docs: render ts based types instead of propTypes

- packages/ui-dom-utils/src/findFocusable.ts
- packages/ui-menu/src/Menu/MenuItemGroup/index.tsx
Update all instances of "indeces" to "indices"
> chore(ui-dom-utils,ui-menu): update spelling in comments

- packages/ui-expandable/babel.config.js
- packages/ui-expandable/src/Expandable/index.tsx
- packages/ui-toggle-details/src/ToggleDetails/index.tsx
- packages/ui-toggle-details/src/ToggleGroup/index.tsx
> chore(ui-expandable,ui-toggle-details): add better TS types to `Expandable`

- packages/__docs__/package.json
The issue was that it was not calling bundle, just starting a web server
> INSTUI-3144  fix docs production build

- packages/ui-byline/src/Byline/index.tsx
- packages/ui-calendar/src/Calendar/Day/index.tsx
- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-modal/src/Modal/ModalBody/index.tsx
- packages/ui-navigation/src/AppNav/index.tsx
- packages/ui-options/src/Options/index.tsx
- packages/ui-pagination/src/Pagination/index.tsx
- packages/ui-rating/src/Rating/index.tsx
- packages/ui-react-utils/src/omitProps.ts
- packages/ui-react-utils/src/passthroughProps.ts
- packages/ui-spinner/src/Spinner/index.tsx
- packages/ui-table/src/Table/Body/index.tsx
- packages/ui-table/src/Table/Cell/index.tsx
- packages/ui-table/src/Table/Row/index.tsx
- packages/ui-table/src/Table/RowHeader/index.tsx
- packages/ui-table/src/Table/index.tsx
- packages/ui-tag/src/Tag/index.tsx
- packages/ui-view/src/View/index.tsx
- packages/ui-view/src/View/types.ts
Refactor omitViewProps and omitProps so its more clear what they do. This resulted in a few small issues coming up (e.g. null used instead of undefined)
remove "?" from View props that have default value
> NSTUI-3159 better types for View and refactoring for OmitProps/passtroughProps

- packages/__docs__/src/App/index.js
- packages/__docs__/src/Document/index.js
- packages/__docs__/versions.json
> fix: link correct source code on docs page for legacy versions

- packages/ui-badge/src/Badge/__examples__/Badge.examples.tsx
- packages/ui-badge/src/Badge/__tests__/Badge.test.tsx
- packages/ui-badge/src/Badge/index.tsx
- packages/ui-badge/src/Badge/types.ts
> chore(ui-badge): improve typing for ui-badge (INSTUI-3033)

- packages/emotion/src/withStyle.tsx
- packages/ui-decorator/src/decorator.ts
- packages/ui-i18n/src/bidirectional.tsx
- packages/ui-react-utils/src/deprecated.ts
- packages/ui-react-utils/src/experimental.ts
- packages/ui-react-utils/src/hack.ts
- packages/ui-react-utils/src/windowMessageListener.ts
- packages/ui-testable/src/testable.ts
While not perfect, I doubt that we can make it significantly better without some large refactoring
> INSTUI-3043 : Better TypeScript typing for ui-decorator

- packages/ui-dom-utils/src/getFrameDocumentSafe.ts
> fix(ui-dom-utils): remove el.contentWindow.document from getFrameDocumentSafe

- packages/ui-text/babel.config.js
- packages/ui-text/src/Text/__examples__/Text.examples.ts
- packages/ui-text/src/Text/index.tsx
- packages/ui-text/src/Text/props.ts
> chore(ui-text): add typing to ui-text (INSTUI-3090)

- packages/ui-popover/src/Popover/README.md
- packages/ui-tooltip/src/Tooltip/README.md
Without this explanation its nearly impossible to figure out how to use a custom component as a tooltip/popover trigger
> INSTUI-3266 Explain how Tooltips+custom components work

- packages/emotion/src/__tests__/withStyle.test.tsx
- packages/emotion/src/withStyle.tsx
Closes: INSTUI-3242
If `styles` and `makeStyles` props are manually passed to the component, the withStyle decorator
throws a warning and overrides them with the default calculated values. This is needed so the users
cannot freely override the styles of the components. Added tests too.
> chore(emotion): disable manually passed `styles` and `makeStyles` props

- packages/__docs__/src/Description/index.tsx
- packages/__docs__/src/Description/props.ts
- packages/__docs__/src/Document/index.tsx
- packages/__docs__/src/Document/props.ts
- packages/__docs__/src/Document/styles.ts
- packages/__docs__/src/Document/theme.ts
- packages/__docs__/src/Figure/index.tsx
- packages/__docs__/src/Figure/props.ts
- packages/__docs__/src/Figure/styles.ts
- packages/__docs__/src/Figure/theme.ts
- packages/__docs__/src/Glyph/index.tsx
- packages/__docs__/src/Glyph/props.ts
- packages/__docs__/src/Glyph/styles.ts
- packages/__docs__/src/Glyph/theme.ts
- packages/__docs__/src/Guidelines/index.tsx
- packages/__docs__/src/Guidelines/props.ts
Typescript conversion with components starting with letter D, F, G
> INSTUI 3295 docs type script conversion letter D,F,G

- packages/ui-scripts/bin/specify-module-format.js
- packages/ui-scripts/src/build/babel.ts
> fix(ui-scripts): resolve webpack 5 commonjs build issue

- .github/workflows/pr-validation.yml
- dangerfile.ts
- package.json
- scripts/calculateBundleSize.js
- yarn.lock
Note: this solution will likely not work for PRs which are coming from forked repos.
Since we don't get that much PRs from outside collaborators I think this is not a huge issue right now.
> chore: add bundle size to PRs

- packages/ui-date-input/src/DateInput/__examples__/DateInput.examples.tsx
- packages/ui-date-input/src/DateInput/index.tsx
- packages/ui-date-input/src/DateInput/props.ts
- packages/ui-date-input/src/DateInput/styles.ts
> fix(ui-date-input): fix DateInput preventing fluid width

- packages/ui-focusable/babel.config.js
- packages/ui-focusable/src/Focusable/README.md
- packages/ui-focusable/src/Focusable/__tests__/Focusable.test.tsx
- packages/ui-focusable/src/Focusable/index.tsx
- packages/ui-focusable/src/Focusable/props.ts
TS typing for Focusable. I have rewritten its internal logic a little, because it was really hard to understand.
> INSTUI-3051 Focusable typing

- packages/ui-form-field/src/FormFieldGroup/index.tsx
- packages/ui-form-field/src/FormFieldLayout/index.tsx
- packages/ui-grid/babel.config.js
- packages/ui-grid/src/Grid/__examples__/Grid.examples.tsx
- packages/ui-grid/src/Grid/__tests__/Grid.test.tsx
- packages/ui-grid/src/Grid/index.tsx
- packages/ui-grid/src/Grid/props.ts
- packages/ui-grid/src/GridCol/index.tsx
- packages/ui-grid/src/GridCol/props.ts
- packages/ui-grid/src/GridCol/styles.ts
- packages/ui-grid/src/GridRow/index.tsx
- packages/ui-grid/src/GridRow/props.ts
> chore(ui-grid): add TS types to `ui-grid` package

- packages/ui-avatar/src/Avatar/__tests__/Avatar.test.js
- packages/ui-img/src/Img/README.md
- packages/ui-theme-tokens/src/canvas/__tests__/colors.test.js
- packages/ui-theme-tokens/src/canvas/colors.js
- packages/ui-theme-tokens/src/canvasHighContrast/__tests__/colors.test.js
- packages/ui-theme-tokens/src/instructure/__tests__/colors.test.js
- packages/ui-themeable/src/ApplyTheme/README.md
Backports https://github.com/instructure/instructure-ui/pull/767 from V8.
> INSTUI-3273 - canvas theme color update

- packages/ui-pages/package.json
- packages/ui-pages/src/Pages/Page/__tests__/Page.test.tsx
- packages/ui-pages/src/Pages/Page/index.tsx
- packages/ui-pages/src/Pages/Page/props.ts
- packages/ui-pages/src/Pages/PagesContext.ts
- packages/ui-pages/src/Pages/README.md
- packages/ui-pages/src/Pages/__tests__/Pages.test.tsx
- packages/ui-pages/src/Pages/index.tsx
- packages/ui-pages/src/Pages/props.ts
> chore(ui-pages): add TS types to `ui-pages` package

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-badge/src/Badge/README.md
- packages/ui-badge/src/Badge/__examples__/Badge.examples.tsx
- packages/ui-badge/src/Badge/__tests__/theme.test.ts
- packages/ui-badge/src/Badge/props.ts
- packages/ui-badge/src/Badge/styles.ts
- packages/ui-badge/src/Badge/theme.ts
> feat(ui-badge): add `inverse` variant to Badge

- packages/ui-options/src/Options/Item/__examples__/Item.examples.ts
- packages/ui-options/src/Options/Item/__tests__/Item.test.tsx
- packages/ui-options/src/Options/Item/index.tsx
- packages/ui-options/src/Options/Item/props.ts
- packages/ui-options/src/Options/Separator/index.tsx
- packages/ui-options/src/Options/Separator/props.ts
- packages/ui-options/src/Options/index.tsx
- packages/ui-options/src/Options/props.ts
> chore(ui-options): type ui-options (INSTUI-3065)

- packages/__docs__/src/Properties/index.js
- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-a11y-utils/src/ScreenReaderFocusRegion.ts
- packages/ui-dom-utils/src/handleMouseOverOut.ts
- packages/ui-pill/src/Pill/__tests__/Pill.test.tsx
- packages/ui-popover/src/Popover/__examples__/Popover.examples.tsx
- packages/ui-popover/src/Popover/__tests__/Popover.test.tsx
- packages/ui-popover/src/Popover/index.tsx
- packages/ui-popover/src/Popover/props.ts
- packages/ui-position/src/Position/index.tsx
- packages/ui-position/src/Position/props.ts
- packages/ui-position/src/index.ts
- packages/ui-view/src/ContextView/props.ts
> chore(ui-a11y-utils,ui-popover,ui-position,ui-view): type Popover

- packages/ui-flex/babel.config.js
- packages/ui-flex/src/Flex/Item/index.tsx
- packages/ui-flex/src/Flex/Item/props.ts
- packages/ui-flex/src/Flex/Item/styles.ts
- packages/ui-flex/src/Flex/index.tsx
- packages/ui-flex/src/Flex/props.ts
> chore(ui-flex): add TS types to `ui-flex` package

- packages/ui-progress/src/ProgressBar/__examples__/ProgressBar.examples.tsx
- packages/ui-progress/src/ProgressBar/index.tsx
- packages/ui-progress/src/ProgressBar/props.ts
- packages/ui-progress/src/ProgressBar/styles.ts
- packages/ui-progress/src/ProgressCircle/__examples__/ProgressCircle.examples.tsx
- packages/ui-progress/src/ProgressCircle/index.tsx
- packages/ui-progress/src/ProgressCircle/props.ts
- packages/ui-progress/src/ProgressCircle/styles.ts
- packages/ui-progress/src/ProgressCircle/theme.ts
> Ts type ui-progress (INSTUI-3073)

- packages/__docs__/src/Document/index.tsx
- packages/ui-form-field/babel.config.js
- packages/ui-form-field/src/FormField/index.tsx
- packages/ui-form-field/src/FormField/props.ts
- packages/ui-form-field/src/FormFieldGroup/__examples__/FormFieldGroup.examples.tsx
- packages/ui-form-field/src/FormFieldGroup/__examples__/generateMessages.ts
- packages/ui-form-field/src/FormFieldGroup/index.tsx
- packages/ui-form-field/src/FormFieldGroup/props.ts
- packages/ui-form-field/src/FormFieldLabel/index.tsx
- packages/ui-form-field/src/FormFieldLabel/props.ts
- packages/ui-form-field/src/FormFieldLayout/index.tsx
- packages/ui-form-field/src/FormFieldLayout/props.ts
- packages/ui-form-field/src/FormFieldLayout/styles.ts
- packages/ui-form-field/src/FormFieldMessage/index.tsx
- packages/ui-form-field/src/FormFieldMessages/index.tsx
- packages/ui-form-field/src/FormFieldMessages/props.ts
- packages/ui-form-field/src/__tests__/generateMessages.ts
> chore(ui-form-field): add TS types to `ui-form-field` package

- packages/ui-link/babel.config.js
- packages/ui-link/src/Link/__examples__/Link.examples.ts
- packages/ui-link/src/Link/__tests__/Link.test.tsx
- packages/ui-link/src/Link/index.tsx
- packages/ui-link/src/Link/props.ts
- packages/ui-view/src/View/props.ts
- packages/ui-view/src/index.ts
> chore(ui-link): add TS types to `ui-link` package

- packages/ui-list/babel.config.js
- packages/ui-list/src/InlineList/InlineListItem/index.tsx
- packages/ui-list/src/InlineList/InlineListItem/props.ts
- packages/ui-list/src/InlineList/__examples__/InlineList.examples.tsx
- packages/ui-list/src/InlineList/index.tsx
- packages/ui-list/src/InlineList/props.ts
- packages/ui-list/src/List/ListItem/index.tsx
- packages/ui-list/src/List/ListItem/props.ts
- packages/ui-list/src/List/__examples__/List.examples.tsx
- packages/ui-list/src/List/index.tsx
- packages/ui-list/src/List/props.ts
- packages/ui-select/src/Select/index.tsx
> chore(ui-icons,ui-list): add types to ui-list (INSTUI-3058)

- packages/ui-date-input/src/DateInput/index.tsx
- packages/ui-form-field/src/FormField/props.ts
- packages/ui-form-field/src/FormFieldLayout/index.tsx
- packages/ui-form-field/src/FormFieldLayout/props.ts
- packages/ui-grid/src/GridCol/index.tsx
- packages/ui-grid/src/GridCol/props.ts
- packages/ui-select/babel.config.js
- packages/ui-select/src/Select/Group/index.tsx
- packages/ui-select/src/Select/Group/props.ts
- packages/ui-select/src/Select/Option/index.tsx
- packages/ui-select/src/Select/Option/props.ts
- packages/ui-select/src/Select/__examples__/Select.examples.tsx
- packages/ui-select/src/Select/__tests__/Select.test.tsx
- packages/ui-select/src/Select/index.tsx
- packages/ui-select/src/Select/props.ts
- packages/ui-selectable/src/Selectable/index.tsx
- packages/ui-selectable/src/Selectable/props.ts
- packages/ui-simple-select/src/SimpleSelect/index.tsx
- packages/ui-text-input/src/TextInput/props.ts
- packages/ui-time-select/src/TimeSelect/index.tsx
> chore(ui-select): add TS types to `ui-select` package

- packages/ui-menu/src/Menu/MenuItem/index.tsx
- packages/ui-menu/src/Menu/MenuItem/props.ts
- packages/ui-menu/src/Menu/MenuItemGroup/index.tsx
- packages/ui-menu/src/Menu/MenuItemGroup/props.ts
- packages/ui-menu/src/Menu/MenuItemSeparator/index.tsx
- packages/ui-menu/src/Menu/__examples__/Menu.examples.tsx
- packages/ui-menu/src/Menu/__tests__/Menu.test.tsx
- packages/ui-menu/src/Menu/index.tsx
- packages/ui-menu/src/Menu/props.ts
- packages/ui-menu/src/MenuContext.ts
> chore(ui-menu): type ui-menu

- packages/ui-text-area/babel.config.js
- packages/ui-text-area/src/TextArea/__examples__/TextArea.examples.ts
- packages/ui-text-area/src/TextArea/__tests__/TextArea.test.tsx
- packages/ui-text-area/src/TextArea/index.tsx
- packages/ui-text-area/src/TextArea/props.ts
> chore(ui-text-area): type ui-text-area (INSTUI-3088)

- packages/ui-tag/babel.config.js
- packages/ui-tag/src/Tag/__examples__/Tag.examples.ts
- packages/ui-tag/src/Tag/__tests__/Tag.test.tsx
- packages/ui-tag/src/Tag/index.tsx
- packages/ui-tag/src/Tag/props.ts
> chore(ui-tag): add TS types to `ui-tag` package

- packages/ui-modal/README.md
A small and first, but not last :wink: contribution.
> docs(ui-modal): readme

- packages/__docs__/src/Properties/index.js
- packages/shared-types/src/CommonProps.ts
- packages/ui-buttons/src/BaseButton/__tests__/BaseButton.test.tsx
- packages/ui-buttons/src/BaseButton/index.tsx
- packages/ui-buttons/src/BaseButton/props.ts
- packages/ui-buttons/src/BaseButton/theme.ts
- packages/ui-buttons/src/Button/__examples__/Button.examples.tsx
- packages/ui-buttons/src/Button/__tests__/Button.test.tsx
- packages/ui-buttons/src/Button/index.tsx
- packages/ui-buttons/src/Button/props.ts
- packages/ui-buttons/src/CloseButton/index.tsx
- packages/ui-buttons/src/CloseButton/props.ts
- packages/ui-buttons/src/CondensedButton/__examples__/CondensedButton.examples.tsx
- packages/ui-buttons/src/CondensedButton/__tests__/CondensedButton.test.tsx
- packages/ui-buttons/src/CondensedButton/index.tsx
- packages/ui-buttons/src/CondensedButton/props.ts
- packages/ui-buttons/src/IconButton/__examples__/IconButton.examples.tsx
- packages/ui-buttons/src/IconButton/__tests__/IconButton.test.tsx
- packages/ui-buttons/src/IconButton/index.tsx
- packages/ui-buttons/src/IconButton/props.ts
- packages/ui-buttons/src/ToggleButton/__examples__/ToggleButton.examples.tsx
- packages/ui-buttons/src/ToggleButton/__tests__/ToggleButton.test.tsx
- packages/ui-buttons/src/ToggleButton/index.tsx
- packages/ui-buttons/src/ToggleButton/props.ts
- packages/ui-link/src/Link/props.ts
- packages/ui-react-utils/src/getElementType.ts
> chore(ui-buttons): add TS types to `ui-buttons` package

- packages/ui-drawer-layout/src/DrawerLayout/index.tsx
> fix(ui-drawer-layout): fix tray direction calculation (INSTUI-3348)

- packages/ui-tabs/babel.config.js
- packages/ui-tabs/src/Tabs/Panel/index.tsx
- packages/ui-tabs/src/Tabs/Panel/props.ts
- packages/ui-tabs/src/Tabs/Tab/index.tsx
- packages/ui-tabs/src/Tabs/Tab/props.ts
- packages/ui-tabs/src/Tabs/__examples__/Tabs.examples.tsx
- packages/ui-tabs/src/Tabs/__tests__/Tabs.test.tsx
- packages/ui-tabs/src/Tabs/index.tsx
- packages/ui-tabs/src/Tabs/props.ts
> chore(ui-tabs): add TS types to `ui-tabs` package

- packages/ui-radio-input/babel.config.js
- packages/ui-radio-input/src/RadioInput/__examples__/RadioInput.examples.ts
- packages/ui-radio-input/src/RadioInput/__tests__/RadioInput.test.tsx
- packages/ui-radio-input/src/RadioInput/index.tsx
- packages/ui-radio-input/src/RadioInput/props.ts
- packages/ui-radio-input/src/RadioInputGroup/__examples__/RadioInputGroup.examples.tsx
- packages/ui-radio-input/src/RadioInputGroup/index.tsx
- packages/ui-radio-input/src/RadioInputGroup/props.ts
> chore(ui-radio-input): add TS types to `ui-radio-input` package

- packages/ui-form-field/src/FormField/props.ts
- packages/ui-form-field/src/index.ts
- packages/ui-number-input/babel.config.js
- packages/ui-number-input/src/NumberInput/__examples__/NumberInput.examples.ts
- packages/ui-number-input/src/NumberInput/__tests__/NumberInput.test.tsx
- packages/ui-number-input/src/NumberInput/index.tsx
- packages/ui-number-input/src/NumberInput/props.ts
- packages/ui-pagination/src/Pagination/PaginationArrowButton/props.ts
- packages/ui-pagination/src/Pagination/PaginationButton/props.ts
- packages/ui-pagination/src/Pagination/PaginationPageInput/__tests__/PaginationPageInput.test.tsx
- packages/ui-pagination/src/Pagination/PaginationPageInput/index.tsx
- packages/ui-pagination/src/Pagination/PaginationPageInput/props.ts
- packages/ui-pagination/src/Pagination/index.tsx
- packages/ui-text-area/src/TextArea/props.ts
> chore(ui-number-input): add TS types to `ui-number-input` package

- packages/emotion/src/InstUISettingsProvider/index.tsx
- packages/ui-i18n/src/ApplyTextDirection/__tests__/ApplyTextDirection.test.tsx
- packages/ui-i18n/src/ApplyTextDirection/props.ts
- packages/ui-i18n/src/TextDirectionContext.ts
- packages/ui-i18n/src/bidirectional.tsx
- packages/ui-i18n/src/getTextDirection.ts
throw warning when 'auto' dir is passed to the TextDirectionContext
Closes: INSTUI-3306
> chore(emotion,ui-i18n): throw warning when 'auto' dir (INSTUI-3306)

- packages/shared-types/src/UtilityTypes.ts
- packages/shared-types/src/index.ts
- packages/ui-number-input/src/NumberInput/props.ts
- packages/ui-range-input/babel.config.js
- packages/ui-range-input/src/RangeInput/__examples__/RangeInput.examples.ts
- packages/ui-range-input/src/RangeInput/__tests__/RangeInput.test.tsx
- packages/ui-range-input/src/RangeInput/index.tsx
- packages/ui-range-input/src/RangeInput/props.ts
- packages/ui-text-area/src/TextArea/props.ts
> chore(ui-range-input): add TS types to `ui-range-input` package

- packages/ui-billboard/babel.config.js
- packages/ui-billboard/src/Billboard/__examples__/Billboard.examples.tsx
- packages/ui-billboard/src/Billboard/__tests__/Billboard.test.tsx
- packages/ui-billboard/src/Billboard/index.tsx
- packages/ui-billboard/src/Billboard/props.ts
> chore(ui-billboard): add TS types to `ui-billboard` package

- packages/ui-popover/src/Popover/props.ts
- packages/ui-popover/src/index.ts
- packages/ui-tooltip/babel.config.js
- packages/ui-tooltip/src/Tooltip/__tests__/Tooltip.test.tsx
- packages/ui-tooltip/src/Tooltip/index.tsx
- packages/ui-tooltip/src/Tooltip/props.ts
> chore(ui-tooltip): add TS types to `ui-tooltip` package

- packages/ui-select/src/Select/index.tsx
- packages/ui-select/src/Select/props.ts
- packages/ui-select/src/index.ts
- packages/ui-simple-select/babel.config.js
- packages/ui-simple-select/src/SimpleSelect/Group/index.tsx
- packages/ui-simple-select/src/SimpleSelect/Group/props.ts
- packages/ui-simple-select/src/SimpleSelect/Option/index.tsx
- packages/ui-simple-select/src/SimpleSelect/Option/props.ts
- packages/ui-simple-select/src/SimpleSelect/__tests__/SimpleSelect.test.tsx
- packages/ui-simple-select/src/SimpleSelect/index.tsx
- packages/ui-simple-select/src/SimpleSelect/props.ts
- packages/ui-table/src/Table/Head/index.tsx
> chore(ui-simple-select): add TS types to `ui-simple-select` package

- packages/ui-pagination/babel.config.js
- packages/ui-pagination/src/Pagination/PaginationArrowButton/index.tsx
- packages/ui-pagination/src/Pagination/PaginationArrowButton/props.ts
- packages/ui-pagination/src/Pagination/PaginationButton/index.tsx
- packages/ui-pagination/src/Pagination/PaginationButton/props.ts
- packages/ui-pagination/src/Pagination/PaginationPageInput/index.tsx
- packages/ui-pagination/src/Pagination/PaginationPageInput/props.ts
- packages/ui-pagination/src/Pagination/__tests__/Pagination.test.tsx
- packages/ui-pagination/src/Pagination/index.tsx
- packages/ui-pagination/src/Pagination/props.ts
> chore(ui-pagination): add TS types to `ui-pagination` package

- docs/patterns/DrilldownMenu.md
- packages/__docs__/components.js
- packages/__docs__/package.json
- packages/__docs__/resolve.js
- packages/__docs__/src/Nav/index.js
- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-drilldown/.eslintignore
- packages/ui-drilldown/.gitignore
- packages/ui-drilldown/.npmignore
- packages/ui-drilldown/CHANGELOG.md
- packages/ui-drilldown/README.md
- packages/ui-drilldown/babel.config.js
- packages/ui-drilldown/package.json
- packages/ui-drilldown/src/Drilldown/DrilldownLocator.ts
- packages/ui-drilldown/src/Drilldown/README.md
- packages/ui-drilldown/src/Drilldown/__examples__/Drilldown.examples.tsx
- packages/ui-drilldown/src/Drilldown/__tests__/Drilldown.test.tsx
- packages/ui-drilldown/src/Drilldown/__tests__/theme.test.ts
- packages/ui-drilldown/src/Drilldown/index.tsx
- packages/ui-drilldown/src/Drilldown/locator.ts
- packages/ui-drilldown/src/Drilldown/props.ts
- packages/ui-drilldown/src/Drilldown/styles.ts
- packages/ui-drilldown/src/Drilldown/theme.ts
- packages/ui-drilldown/src/index.ts
- packages/ui-drilldown/tsconfig.build.json
- packages/ui-drilldown/tsconfig.json
> chore(ui-drilldown): add base of `ui-drilldown` package (WIP)

- packages/ui-drawer-layout/babel.config.js
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/__tests__/DrawerContent.test.tsx
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/index.tsx
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/props.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/styles.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/index.tsx
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/props.ts
- packages/ui-drawer-layout/src/DrawerLayout/__fixtures__/DrawerLayout.fixture.tsx
- packages/ui-drawer-layout/src/DrawerLayout/index.tsx
- packages/ui-drawer-layout/src/DrawerLayout/props.ts
> chore(ui-drawer-layout): add TS types to `ui-drawer-layout` package

- packages/ui-code-editor/src/CodeEditor/index.tsx
> fix(ui-code-editor): should tab out from the editor when it's readonly

- packages/ui-table/babel.config.js
- packages/ui-table/src/Table/Body/index.tsx
- packages/ui-table/src/Table/Body/props.ts
- packages/ui-table/src/Table/Cell/index.tsx
- packages/ui-table/src/Table/Cell/props.ts
- packages/ui-table/src/Table/ColHeader/index.tsx
- packages/ui-table/src/Table/ColHeader/props.ts
- packages/ui-table/src/Table/Head/index.tsx
- packages/ui-table/src/Table/Head/props.ts
- packages/ui-table/src/Table/Row/index.tsx
- packages/ui-table/src/Table/Row/props.ts
- packages/ui-table/src/Table/RowHeader/index.tsx
- packages/ui-table/src/Table/RowHeader/props.ts
- packages/ui-table/src/Table/__tests__/Table.test.tsx
- packages/ui-table/src/Table/index.tsx
- packages/ui-table/src/Table/props.ts
> chore(ui-table): type ui-table package (INSTUI-3083)

- packages/ui-checkbox/babel.config.js
- packages/ui-checkbox/src/Checkbox/CheckboxFacade/index.tsx
- packages/ui-checkbox/src/Checkbox/CheckboxFacade/props.ts
- packages/ui-checkbox/src/Checkbox/ToggleFacade/index.tsx
- packages/ui-checkbox/src/Checkbox/ToggleFacade/props.ts
- packages/ui-checkbox/src/Checkbox/__tests__/Checkbox.test.tsx
- packages/ui-checkbox/src/Checkbox/index.tsx
- packages/ui-checkbox/src/Checkbox/props.ts
- packages/ui-checkbox/src/Checkbox/styles.ts
- packages/ui-checkbox/src/CheckboxGroup/index.tsx
- packages/ui-checkbox/src/CheckboxGroup/props.ts
> chore(ui-checkbox): Type UI checkbox (INSTUI-3039)

- package.json
- packages/ui-file-drop/src/FileDrop/index.tsx
- yarn.lock
> chore: update TS version to `4.5.5`

- packages/ui-alerts/babel.config.js
- packages/ui-alerts/src/Alert/__tests__/Alert.test.tsx
- packages/ui-alerts/src/Alert/index.tsx
- packages/ui-alerts/src/Alert/props.ts
> chore(ui-alerts): ts type ui-alerts

- packages/ui-docs-client/src/CodePenButton/index.js
backport for https://github.com/instructure/instructure-ui/pull/896
> refactor(ui-docs-client): fix codepen links for v7 docs

- packages/ui-radio-input/src/RadioInput/styles.ts
> fix(ui-radio-input): fix cursor of radioinput, version toggle in Safari

- docs/guides/server-side-rendering.md
Updated the server side render guide with section explaining how to install packages and to not install the meta package.
> docs: update ssr guide with note about meta package

- packages/__docs__/src/Header/index.tsx
> docs: fix typing for nav when switching between versions

- packages/ui-rating/babel.config.js
- packages/ui-rating/src/Rating/__tests__/Rating.test.tsx
- packages/ui-rating/src/Rating/index.tsx
- packages/ui-rating/src/Rating/props.ts
- packages/ui-rating/src/RatingIcon/__tests__/RatingIcon.test.tsx
- packages/ui-rating/src/RatingIcon/index.tsx
> chore(ui-rating): add TS types to `ui-rating` package

- packages/ui-text-input/src/TextInput/index.tsx
So the focusring will appear as intended
Possible explanation: https://github.com/facebook/react/issues/17894#issuecomment-591643059
Closes: INSTUI-3435
> fix(ui-text-input): fix Event handling for textinput

- packages/ui-drilldown/README.md
- packages/ui-drilldown/package.json
- packages/ui-drilldown/src/Drilldown/DrilldownGroup/__tests__/DrilldownGroup.test.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownGroup/index.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownGroup/props.ts
- packages/ui-drilldown/src/Drilldown/DrilldownLocator.ts
- packages/ui-drilldown/src/Drilldown/DrilldownOption/__tests__/DrilldownOption.test.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownOption/index.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownOption/props.ts
- packages/ui-drilldown/src/Drilldown/DrilldownPage/__tests__/DrilldownPage.test.tsx
- packages/ui-drilldown/src/Drilldown/README.md
- packages/ui-drilldown/src/Drilldown/__tests__/Drilldown.test.tsx
- packages/ui-drilldown/src/Drilldown/index.tsx
- packages/ui-drilldown/src/Drilldown/props.ts
- packages/ui-options/src/Options/index.tsx
- packages/ui-options/src/Options/props.ts
- packages/ui-select/src/Select/index.tsx
- packages/ui-simple-select/src/SimpleSelect/index.tsx
> docs: add docs and examples to Drilldown

- docs/guides/v8-upgrade-guide.md
- packages/ui-codemods/README.md
> fix(ui-codemods): fix codemod paths in docs (`.ts` instead of `.js`)

- packages/__docs__/buildScripts/build-docs.ts
- packages/__docs__/src/Document/index.tsx
- packages/emotion/src/EmotionThemeProvider/index.tsx
- packages/emotion/src/InstUISettingsProvider/index.tsx
- packages/ui-view/src/View/index.tsx
Removes @module and some text from source files that was not needed (check EmotionThemeProvider and View)
> INSTUI-3459 remove random not needed info from docs pages

- packages/ui-modal/babel.config.js
- packages/ui-modal/src/Modal/ModalBody/__tests__/ModalBody.test.tsx
- packages/ui-modal/src/Modal/ModalBody/index.tsx
- packages/ui-modal/src/Modal/ModalFooter/index.tsx
- packages/ui-modal/src/Modal/ModalHeader/index.tsx
- packages/ui-modal/src/Modal/__tests__/Modal.test.tsx
- packages/ui-modal/src/Modal/index.tsx
- packages/ui-modal/src/Modal/props.ts
> chore(ui-modal): add TS types to `ui-modal` package

- packages/ui-date-time-input/src/DateTimeInput/README.md
- packages/ui-date-time-input/src/DateTimeInput/__examples__/DateTimeInput.examples.ts
- packages/ui-date-time-input/src/DateTimeInput/__tests__/DateTimeInput.test.tsx
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
- packages/ui-date-time-input/src/DateTimeInput/props.ts
One can either specify an array of ISO dates or a function that will get called for each time a date needs to be validated.
> INSTUI-3488 Allow to disable dates in DateTimeInput

- packages/ui-navigation/babel.config.js
- packages/ui-navigation/src/AppNav/Item/index.tsx
- packages/ui-navigation/src/AppNav/Item/props.ts
- packages/ui-navigation/src/AppNav/__tests__/AppNav.test.tsx
- packages/ui-navigation/src/AppNav/index.tsx
- packages/ui-navigation/src/AppNav/props.ts
- packages/ui-navigation/src/Navigation/NavigationItem/index.tsx
- packages/ui-navigation/src/Navigation/NavigationItem/props.ts
- packages/ui-navigation/src/Navigation/index.tsx
- packages/ui-navigation/src/Navigation/props.ts
> INSTUI-3063-TS-typing-ui-navigation

- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-dialog/src/Dialog/index.tsx
- packages/ui-modal/src/Modal/__tests__/Modal.test.tsx
Closes: INSTUI-3490
TEST PLAN:
use https://codesandbox.io/s/functional-comp-based-modal-dismiss-lph8yt as a base, then place the code in our docs app and verify that the fix works
> fix(ui-a11y-utils,ui-dialog,ui-modal): calling stale callbacks

- packages/ui-grid/package.json
- packages/ui-grid/src/Grid/README.md
- packages/ui-grid/src/GridCol/index.tsx
- packages/ui-grid/src/GridCol/props.ts
- packages/ui-grid/tsconfig.build.json
- yarn.lock
fix(ui-grid): modify Ts types for GridCol to accept prositive fractions as well
Closes: INSTUI-3513
> fix(ui-grid): modify Ts types for GridCol

- packages/ui-editable/src/Editable/__tests__/Editable.test.tsx
- packages/ui-editable/src/Editable/index.tsx
- packages/ui-editable/src/Editable/props.ts
- packages/ui-editable/src/InPlaceEdit/__tests__/InPlaceEdit.test.tsx
- packages/ui-editable/src/InPlaceEdit/index.tsx
- packages/ui-editable/src/InPlaceEdit/props.ts
chore(ui-editable): add TS type in `InplaceEdit` component
> chore(ui-editable): add TS type in `Editable` component

- packages/ui-billboard/src/Billboard/__examples__/Billboard.examples.tsx
- packages/ui-menu/src/Menu/__examples__/Menu.examples.tsx
- packages/ui-tabs/src/Tabs/__examples__/Tabs.examples.tsx
> test(ui-billboard,ui-menu,ui-tabs): fix flaky VRT

- packages/ui-date-time-input/src/DateTimeInput/index.tsx
In React 16 events are reused so one cannot use one after a timeout. This commit fixes this edge
case.
To test: set React to "^16" in the main package.json's Resolution field.
> INSTUI-3556 fix enter not applying date

- packages/ui-position/src/calculateElementPosition.ts
Closes: INSTUI-3505
Added the fix for the offset string value parsing in positioned components. This is a breaking
change, so comments were added and the fix is disabled for now. Turn it on in V9 with the
appropriate release notes.
> chore(ui-position): prepare offset string value fix for V9

- CODE_OF_CONDUCT.md
- packages/__docs__/buildScripts/build-docs.ts
> fix: code of Conduct and License pages not show

- packages/ui-menu/src/Menu/__examples__/Menu.examples.tsx
- packages/ui-text-input/src/TextInput/__examples__/TextInput.examples.tsx
- packages/ui-tree-browser/src/TreeBrowser/__examples__/TreeBrowser.examples.ts
The Menu tests keep failing, because the positioning px rounding is not consistent, so we are
testing Chromatics `diffThreshold` setting.
> test(ui-menu,ui-tree-browser): add threshold to Menu vrt tests

- packages/ui-tree-browser/src/TreeBrowser/TreeButton/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/__tests__/TreeNode.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/styles.css
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/theme.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
> fix(ui-tree-browser): fix TreeButton theme overrides

- docs/guides/server-side-rendering.md
- packages/ui-dialog/src/Dialog/props.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/props.ts
- packages/ui-modal/src/Modal/props.ts
- packages/ui-popover/src/Popover/props.ts
- packages/ui-tray/src/Tray/props.ts
- packages/ui/__tests__/ui.spec.js
- packages/ui/jest.config.js
Note that this requires a polyfill for Element if you do server-side-rendering.
> fix: fix propType for liveRegion

- packages/ui-dom-utils/src/__tests__/isCustomElement.test.ts
- packages/ui-dom-utils/src/findFocusable.ts
- packages/ui-dom-utils/src/isDefinedCustomElement.ts
This PR adds some additional checks to `ui-dom-utils` which lets us use that package in the webcomponent based repository together with `ui-a11y-utils`.
> feat(ui-dom-utils): add webcomponent support for certain utility functions

- packages/ui-tree-browser/src/TreeBrowser/README.md
where render before/after example won't react to keyboard input
Closes: INSTUI-3618
> docs(ui-tree-browser): fix docs

- packages/ui-text-input/src/TextInput/index.tsx
> fix(ui-text-input): remove focusring when receiving disabled prop

- docs/design/getting-started.md
- packages/__docs__/src/Document/index.tsx
- packages/__docs__/src/Search/index.tsx
> docs: add design section to docs and "edit in github" link

- packages/ui-img/src/Img/__examples__/Img.examples.ts
- packages/ui-img/src/Img/index.tsx
- packages/ui-img/src/Img/props.ts
> feat(ui-img): add 'loading' prop to Img component

- packages/__docs__/buildScripts/samplemedia/placeholder-image.js
> docs: fix placeholder images in Img docs example

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/styles.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/theme.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/styles.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/theme.ts
> feat(ui-drawer-layout): expose `overflow` css props as themeable variables

- packages/__docs__/buildScripts/DataTypes.ts
- packages/__docs__/buildScripts/utils/getPathInfo.ts
- packages/__docs__/src/Document/index.tsx
> docs: provide link to the Github theme variables

- packages/__examples__/buildScripts/parsePropValues.js
- packages/__examples__/package.json
- packages/ui-color-picker/src/ColorIndicator/__tests__/ColorIndicator.test.tsx
- packages/ui-drilldown/src/Drilldown/__tests__/Drilldown.test.tsx
- packages/ui-eslint-config/lib/index.js
- packages/ui-options/src/Options/README.md
- packages/ui-options/src/Options/__tests__/Options.test.tsx
- yarn.lock
> chore: update dependencies

- packages/ui-modal/package.json
- packages/ui-modal/src/Modal/ModalBody/index.js
Closes: INSTUI-3722
Backports INSTUI-3701
> INSTUI-3722 - fix modal focus

- packages/ui-metric/src/Metric/README.md
TEST PLAN:
Load the docs page for metric component, it shouldn't be broken anymore.
> docs(ui-metric): add line breaks to the metric docs

- packages/ui-badge/src/Badge/__examples__/Badge.examples.tsx
- packages/ui-badge/src/Badge/index.tsx
- packages/ui-badge/src/Badge/props.ts
- packages/ui-badge/src/Badge/styles.ts
> feat(ui-badge): add `display` prop to Badge

- packages/ui-source-code-editor/src/SourceCodeEditor/SourceCodeEditorLocator.ts
- packages/ui-source-code-editor/src/SourceCodeEditor/__tests__/SourceCodeEditor.test.tsx
- packages/ui-source-code-editor/src/SourceCodeEditor/index.tsx
- packages/ui-source-code-editor/src/SourceCodeEditor/props.ts
- packages/ui-source-code-editor/src/SourceCodeEditor/styles.ts
> feat(ui-source-code-editor): add `height` and `width` props to SourceCodeEditor

- packages/ui-icons/README.md
Updated the "Adding and Modifying Icons" section of https://instructure.design/#ui-icons page.
Closes: INSTUI-3768
> docs(ui-icons): update docs for adding new icons

- packages/ui-radio-input/src/RadioInput/props.ts
> docs(ui-radio-input): explain type of onChange's event.target.value

- docs/guides/release.md
> docs: add docs for release process

- packages/ui-navigation/src/Navigation/README.md
- packages/ui-navigation/src/Navigation/index.tsx
mark it as experimental because there could be large changes in it
> docs(ui-navigation): un-deprecate Navigation

- packages/ui-text-area/src/TextArea/README.md
- packages/ui-text-area/src/TextArea/index.tsx
> fix(ui-text-area): fix focusring issues in case of horizontal resize

- packages/ui-text-input/src/TextInput/index.tsx
> fix(ui-text-input): fix textInput, where onFocus fires twice.

- packages/ui-flex/src/Flex/README.md
Previous wording was a bit confusing
> fix(ui-flex): documentation wording

- packages/ui-select/src/Select/README.md
INSTUI-3810
test plan:
- open the new example in safari
- turn on voiceover
- open the select menu and use arrow keys or mouse to navigate options
- voiceover should announce every option when highlighted
> voiceover in safari doesn't read grouped select options

- packages/theme-registry/src/ThemeRegistry.ts
> chore(theme-registry): remove warning of multiple theme registry import

- packages/ui-scripts/lib/utils/git.js
INSTUI-3833
- `yarn bump` should run and create a new commit
> chore(ui-scripts): don't run git hooks from ui-scripts

- packages/ui-source-code-editor/package.json
- packages/ui-source-code-editor/src/SourceCodeEditor/__new-tests__/SourceCodeEditor.test.tsx
- yarn.lock
added unit test for syntax highlight
Closes: INSTUI-3831
TEST PLAN:
check example code in docs app and see if syntax highlight works
> fix(ui-source-code-editor): fix broken codemirror syntax highlight and add unit test

- packages/__examples__/.storybook/stories/stories.ts
INSTUI-3837
this seems to work but I'm not 100%, my suggestion is to merge this and get back to the issue if we still have false positives in chromatic
> chore: increase chromatic threshold to avoid false positives

- packages/ui-text-area/src/TextArea/index.tsx
> fix(ui-text-area): fix textarea so selenium tests will pass

- packages/ui-color-picker/src/ColorMixer/ColorPalette/index.tsx
test plan:
- tests in CI should pass
> test(ui-color-picker): fix failing axe test for ColorPalette

- packages/ui-number-input/src/NumberInput/styles.ts
> fix(ui-number-input): increase specificity for numberinput's input styles

- packages/ui-grid/src/Grid/props.ts
- packages/ui-grid/src/GridCol/props.ts
- packages/ui-grid/src/GridCol/styles.ts
- packages/ui-grid/src/GridRow/props.ts
- packages/ui-grid/src/GridRow/styles.ts
My goal with this PR is to be able to stretch grid cells, so that if one cell is taller then the others then they can all get the same height.
> feat(grid): add stretch option to vAlign

- package-lock.json
- packages/ui-badge/package.json
- packages/ui-badge/src/Badge/__new-tests__/Badge.test.tsx
- packages/ui-badge/tsconfig.build.json
> test(ui-badge): migrate old Badge tests

- karma.conf.js
> chore: remove coverage threshold requirement for old tests in CI

- packages/ui-utils/src/getBrowser.ts
> chore(ui-utils): add chromium based browser to browser check

- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/index.tsx
- packages/ui-tray/src/Tray/index.tsx
> fix(ui-drawer-layout,ui-tray): fix multiple mounting during transition

- regression-test/package.json
this should fix the CI errors on our master
> chore: downgrade esbuild for regression tests

- packages/ui-side-nav-bar/src/SideNavBar/SideNavBarItem/styles.ts
> fix(ui-side-nav-bar): don't allow SideNavBar.Item to inherit global styles

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-side-nav-bar/src/SideNavBar/SideNavBarItem/theme.ts
> fix(ui-side-nav-bar): increase SideNavBar.Item font weight to 400

- packages/ui-side-nav-bar/src/SideNavBar/SideNavBarItem/styles.ts
- packages/ui-side-nav-bar/src/SideNavBar/SideNavBarItem/theme.ts
> feat(ui-side-nav-bar): change hover bahaviour of SideNavBar

- packages/ui-top-nav-bar/src/TopNavBar/README.md
> docs(ui-top-nav-bar): add example to TopNavBar, showing color overrides

- packages/ui-list/src/List/styles.ts
> fix(ui-list): add fix for nested list items

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-heading/src/Heading/theme.ts
> fix(shared-types,ui-heading): set h1 weight to 700

- package-lock.json
- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-dialog/src/Dialog/__new-tests__/Dialog.test.tsx
- packages/ui-popover/package.json
- packages/ui-popover/src/Popover/__new-tests__/Popover.test.tsx
INSTUI-3942
I wasn't able to write tests for some scenarios as the behaviour is not always the same in jest as in the browser.
> test(ui-popover): add focus region related tests and fix modal not dismissible with touch

- package-lock.json
- packages/ui-avatar/src/Avatar/README.md
- packages/ui-avatar/src/Avatar/__examples__/Avatar.examples.tsx
- packages/ui-avatar/src/Avatar/index.tsx
- packages/ui-avatar/src/Avatar/props.ts
- packages/ui-avatar/src/Avatar/styles.ts
- packages/ui-side-nav-bar/src/SideNavBar/README.md
INSTUI-3951
fixes #1346
test plan:
- check the new `Border` section in the docs for the Avatar
- try out all options with the new prop
> feat(ui-avatar): add showBorder prop to Avatar

- packages/ui-top-nav-bar/src/TopNavBar/README.md
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarActionItems/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/props.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarUser/__new-tests__/TopNavBarUser.test.tsx
- packages/ui-top-nav-bar/src/TopNavBar/utils/exampleHelpers.tsx
> feat(ui-top-nav-bar): add a new variant 'forceIconWithLabel' for  TopNavBar.Item

- packages/ui-top-nav-bar/src/TopNavBar/README.md
> docs(ui-top-nav-bar): add note of removal for topnavbar brand to docs

- packages/console/src/console.ts
- packages/ui-testable/src/testable.ts
- packages/ui-view/src/View/index.tsx
Closes: INSTUI-3963
**Test plan**: create a project as described in this [issue](https://github.com/instructure/instructure-ui/issues/1404) and check if any error message pops up.
> fix(console,ui-view): fix process is not defined issue

- package-lock.json
- packages/ui-pill/src/Pill/README.md
> docs(ui-pill): adjust Pill's guidelines to comply with new changes

- packages/__examples__/.storybook/stories/SourceCodeEditorExamples.tsx
- packages/template-component/template/src/{NAME}/README.md.ejs
- packages/ui-a11y-content/src/AccessibleContent/README.md
- packages/ui-a11y-content/src/PresentationContent/README.md
- packages/ui-a11y-content/src/ScreenReaderContent/README.md
- packages/ui-avatar/src/Avatar/README.md
- packages/ui-code-editor/src/CodeEditor/README.md
- packages/ui-dialog/src/Dialog/README.md
- packages/ui-focusable/src/Focusable/README.md
- packages/ui-form-field/src/FormFieldLabel/index.tsx
- packages/ui-form-field/src/FormFieldMessage/index.tsx
- packages/ui-form-field/src/FormFieldMessages/index.tsx
- packages/ui-grid/src/Grid/README.md
- packages/ui-portal/src/Portal/README.md
- packages/ui-position/src/Position/README.md
- packages/ui-source-code-editor/src/SourceCodeEditor/README.md
> docs: refactor broken docs examples

- packages/__docs__/src/Playground/index.tsx
> docs: fix fullscreen mode and remove FindDomNode

- packages/ui-overlays/src/Mask/MaskCounter.ts
- packages/ui-overlays/src/Mask/index.tsx
**Test**: create a nested Modal setup and check if scrollbar is visible upon the closure of the nested modal.
Closes: INSTUI-3855
> fix(ui-overlays): add maskcounter

- package-lock.json
- packages/ui-utils/package.json
- packages/ui-utils/src/__new-tests__/camelize.test.tsx
- packages/ui-utils/src/__new-tests__/cloneArray.test.tsx
- packages/ui-utils/src/__new-tests__/createChainedFunction.test.tsx
- packages/ui-utils/src/__new-tests__/generateId.test.tsx
- packages/ui-utils/src/__new-tests__/hash.test.tsx
- packages/ui-utils/src/__new-tests__/mergeDeep.test.tsx
- packages/ui-utils/src/__new-tests__/ms.test.tsx
- packages/ui-utils/src/__new-tests__/parseUnit.test.tsx
- packages/ui-utils/src/__new-tests__/pascalize.test.tsx
- packages/ui-utils/src/__new-tests__/px.test.tsx
- packages/ui-utils/src/__new-tests__/within.test.tsx
- packages/ui-utils/tsconfig.build.json
> test(ui-utils): migrate old Utils tests

- package-lock.json
- packages/ui-date-time-input/src/DateTimeInput/__new-tests__/DateTimeInput.test.tsx
- packages/ui-themes/package.json
- packages/ui-themes/src/__new-tests__/themes.test.tsx
- packages/ui-themes/tsconfig.build.json
> test(ui-themes): migrate old Themes tests

- .github/ISSUE_TEMPLATE/accessability-issue.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/question.md
> chore: update issues template with notice

- packages/ui-select/src/Select/index.tsx
- packages/ui-select/src/Select/props.ts
> feat(ui-select): expose prop to control auto-scrolling in select component

- docs/contributor-docs/v9-upgrade-guide.md
- packages/__docs__/src/compileMarkdown.tsx
> docs(ui): update the v9 upgrade guide and fix docs table markdown render

- packages/__docs__/globals.js
- packages/ui-date-time-input/src/DateTimeInput/README.md
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
- packages/ui-date-time-input/src/DateTimeInput/props.ts
> feat(ui-date-time-input): make resetting programatically possible

- packages/ui-tray/src/Tray/index.tsx
INSTUI-4021
test plan:
- open the tray component
- hit tab a couple of times -> the component should contain focus
> fix(ui-tray): focus trapping

- packages/ui-buttons/src/BaseButton/styles.ts
> feat(ui-buttons): add stronger css rules for focused links

- packages/ui-tabs/src/Tabs/Tab/index.tsx
- packages/ui-tabs/src/Tabs/index.tsx
> fix(ui-tabs): fix automatic id generation in tabs

- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/DesktopLayout/theme.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/theme.ts
Closes: INSTUI-4036
BREAKING CHANGE:
topnavbar secondary color changes
Test plan: please check if TopNavBar secondary color (inverse mode) is porcelaine.
> fix(ui-top-nav-bar): change topnavbar secondary color to porcelaine

- packages/ui-buttons/src/BaseButton/index.tsx
- packages/ui-buttons/src/BaseButton/props.ts
- packages/ui-buttons/src/CloseButton/props.ts
- packages/ui-text/src/Text/props.ts
- packages/ui-text/src/Text/styles.ts
> [Breaking] feat(ui-buttons,ui-text): remove deprecated prop values

- packages/ui-overlays/src/Mask/index.tsx
- packages/ui-overlays/src/Mask/props.ts
- packages/ui-overlays/src/Overlay/index.tsx
- packages/ui-overlays/src/Overlay/props.ts
INSTUI-4040
BREAKING CHANGE:
removed onDismiss prop from Mask and applicationElement from Overlay
> [Breaking] feat(ui-overlays): remove deprecated props from Mask and Overlay

- packages/ui-dialog/src/Dialog/index.tsx
INSTUI-4053
this reverts [this](#1477) PR
> fix(ui-dialog): revert ecc0ee8

- packages/ui-tabs/src/Tabs/Tab/index.tsx
[INSTUI-4057](https://instructure.atlassian.net/browse/INSTUI-4057)
[INSTUI-4057]: https://instructure.atlassian.net/browse/INSTUI-4057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(ui-tabs): mark Tab as utility component

- docs/contributor-docs/v9-upgrade-guide.md
> docs: explain commonjs deprecation in v9 upgrade guide

- package-lock.json
- package.json
- packages/ui-color-picker/src/ColorContrast/ColorContrastLocator.ts
- packages/ui-color-picker/src/ColorPicker/ColorPickerLocator.ts
- packages/ui-color-picker/src/ColorPreset/ColorPresetLocator.ts
- packages/ui-color-picker/src/ColorPreset/__tests__/ColorPreset.test.tsx
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/DrawerTrayLocator.ts
- packages/ui-drilldown/src/Drilldown/DrilldownLocator.ts
- packages/ui-drilldown/src/Drilldown/__tests__/Drilldown.test.tsx
- packages/ui-eslint-config/lib/index.js
- packages/ui-pagination/src/Pagination/PaginationArrowButton/PaginationArrowButtonLocator.ts
- packages/ui-pagination/src/Pagination/PaginationPageInput/PaginationPageInputLocator.ts
- packages/ui-pill/src/Pill/PillLocator.ts
- packages/ui-popover/src/Popover/PopoverLocator.ts
- packages/ui-select/src/Select/SelectLocator.ts
- packages/ui-select/src/Select/__tests__/Select.test.tsx
- packages/ui-side-nav-bar/src/SideNavBar/SideNavBarItem/SideNavBarItemLocator.ts
- packages/ui-simple-select/src/SimpleSelect/SimpleSelectLocator.ts
- packages/ui-table/src/Table/__tests__/Table.test.tsx
- packages/ui-time-select/src/TimeSelect/TimeSelectLocator.ts
- packages/ui-tooltip/src/Tooltip/TooltipLocator.ts
> chore(many): update typescript

- packages/ui-tabs/src/Tabs/index.tsx
> fix(ui-tabs): fix id generation when null is present as children

- packages/ui-buttons/src/CondensedButton/props.ts
> fix(ui-buttons): allow `secondary` option for CondensedButton color

- packages/ui-tabs/src/Tabs/Panel/index.tsx
- packages/ui-tabs/src/Tabs/Panel/props.ts
- packages/ui-tabs/src/Tabs/Panel/styles.ts
- packages/ui-tabs/src/Tabs/README.md
- packages/ui-tabs/src/Tabs/index.tsx
> Tabs refactor

- packages/ui-tabs/src/Tabs/index.tsx
> fix(ui-tabs): fix horizontal scrolling with keyboard navigation

- packages/ui-menu/src/Menu/props.ts
- packages/ui-menu/src/Menu/styles.ts
> feat(ui-menu): add maxHeight functionality to Menu

- packages/ui-buttons/src/CondensedButton/props.ts
> [v8 backport] fix(ui-buttons): allow secondary option for CondensedButton color

- packages/ui-color-picker/src/ColorPreset/index.tsx
- packages/ui-color-picker/src/ColorPreset/styles.ts
> fix(ui-color-picker): add styling for disabled state

- packages/ui-react-utils/src/DeterministicIdContext/DeterministicIdContextProvider.tsx
> fix(ui-react-utils): remove defaultProps from DeterministicContextProvider

- package-lock.json
- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-calendar/package.json
- packages/ui-calendar/src/Calendar/README.md
- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-calendar/src/Calendar/props.ts
- packages/ui-calendar/src/Calendar/styles.ts
- packages/ui-calendar/src/Calendar/theme.ts
- packages/ui-calendar/tsconfig.build.json
- packages/ui-select/src/Select/index.tsx
Closes: INSTUI-4086, INSTUI-4087
This also FIXES ui-select, where autoscroll was turned off by default
> feat(shared-types,ui-calendar,ui-select): add yearpicker functionality to calendar

- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/props.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/styles.ts
Closes: INSTUI-4085
**Test plan:**
Use the big example in the TopNavBar section of the docs app. Check if the TopNavBar.Item (all of the titles are TopNavBar.Item in the nav bar) container width remains unchanged and does not move left or right, when clicked.
> fix(ui-top-nav-bar): fix topnavbar item width changing

- packages/ui-menu/src/Menu/MenuItem/index.tsx
- packages/ui-menu/src/Menu/MenuItem/props.ts
- packages/ui-menu/src/Menu/MenuItemGroup/index.tsx
- packages/ui-menu/src/Menu/MenuItemGroup/props.ts
- packages/ui-navigation/src/AppNav/Item/index.tsx
- packages/ui-navigation/src/AppNav/Item/props.ts
> chore(ui-menu,ui-navigation): improve typing

- packages/ui-table/src/Table/Body/index.tsx
- packages/ui-table/src/Table/Body/props.ts
- packages/ui-table/src/Table/Head/props.ts
- packages/ui-table/src/Table/README.md
- packages/ui-table/src/Table/Row/index.tsx
- packages/ui-table/src/Table/Row/props.ts
- packages/ui-table/src/Table/__tests__/Table.test.tsx
- packages/ui-table/src/Table/index.tsx
- packages/ui-table/src/Table/props.ts
> feat(ui-table): remove restriction for children types and add documentation

- packages/emotion/src/InstUISettingsProvider/index.tsx
- packages/ui-buttons/src/Button/README.md
- packages/ui-i18n/src/ApplyLocale/index.tsx
> chore(emotion,ui-buttons,ui-i18n): remove defaultProps

- package-lock.json
- packages/ui-text/package.json
- packages/ui-text/src/Text/__new-tests__/Text.test.tsx
- packages/ui-text/tsconfig.build.json
> test(ui-text): migrate old Text tests

- package-lock.json
- packages/ui-tray/package.json
- packages/ui-tray/src/Tray/index.tsx
- packages/ui-tray/src/Tray/props.ts
- packages/ui-tray/tsconfig.build.json
Closes: INSTUI-3991
**Test**
Add the `enableMask` prop to Tray and see if `Mask` appears on open.
> feat(ui-tray): add optional mask overlay to tray

- package-lock.json
- packages/ui-portal/package.json
- packages/ui-portal/src/Portal/__new-tests__/Portal.test.tsx
- packages/ui-portal/tsconfig.build.json
> test(ui-portal): migrate old Portal tests

- cypress/component/Pill.cy.tsx
- packages/ui-pill/src/Pill/__new-tests__/Pill.test.tsx
> test(ui-pill): migrate old Pill tests

- regression-test/package-lock.json
> update regression test package lock

- .github/workflows/cypress.yml
- .github/workflows/manual-deploy-docs.yml
- .github/workflows/manual-release-from-pr.yml
- .github/workflows/pr-validation.yml
- .github/workflows/release.yml
- .github/workflows/vrt.yml
- package-lock.json
- packages/ui-tag/package.json
Fix typecheck and downgrade node from 22 to 20 because `netlify-cli` doesn't work with it nicely. It time out the `npm install` and failed all CI checks.
> chore(ui-tag): fix typecheck error

- packages/ui-date-input/src/DateInput2/__examples__/DateInput2.examples.tsx
part of INSTUI-4138
test plan:
- check chromatic examples if they look normal
> chore(ui-date-input): add storybook examples for DateInput2

- .github/workflows/release.yml
the npm script `test:patchset` was missing so the action always failed
> chore: fix gh action on master

- cypress/component/Table.cy.tsx
- package-lock.json
- packages/ui-table/package.json
- packages/ui-table/src/Table/__new-tests__/Table.test.tsx
- packages/ui-table/tsconfig.build.json
> test(ui-table): migrate old Table tests

- packages/ui-modal/src/Modal/ModalHeader/styles.ts
INSTUI-4146
test plan: check the top left and top right radius of the modal
> fix(ui-modal): inherit border radius for ModalHeader

- regression-test/src/app/components/BREADCRUMB_IUI.js
This fixes the failing regression test on master.
> chore: change url in regression test

- docs/contributor-docs/release.md
INSTUI-4147
test plan:
https://instructure.github.io/instructure-ui/pr-preview/pr-1600/#release/#Release%20Process%20for%20Major%20updates
> docs: update release docs with major update info

- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/__tests__/DrawerContent.test.tsx
> test(ui-drawer-layout): fix failing unit test

- .github/workflows/deploy-docs-to-netlify.yml
- .github/workflows/deploy.yml
- .github/workflows/manual-release-from-pr.yml
- .github/workflows/manual-release-to-npm.yml
- .github/workflows/preview.yml
- .github/workflows/vrt.yml
updated version and clarified some descriptions but most importantly removed the reference for `test:patchset` script which does not exist anymore. I didn't replace it with anything because running the tests before release I very redundant since we run them on each PR separately, the release PR and when merged in so if there's an issue, this won't catch that
> chore: update github actions

- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/__tests__/DrawerContent.test.tsx
same as https://github.com/instructure/instructure-ui/pull/1619 and  https://github.com/instructure/instructure-ui/pull/1620 just for the v8 branch
> refactor(ui-drawer-layout): fix failing test likely due to a Chrome update

- packages/ui-drilldown/src/Drilldown/README.md
> docs(ui-drilldown): function based examples are added to Drilldown

- package-lock.json
- packages/ui-grid/package.json
- packages/ui-grid/src/Grid/__new-tests__/Grid.test.tsx
- packages/ui-grid/src/GridCol/__new-tests__/Grid.test.tsx
> test(ui-grid): migrate old Grid tests

- packages/ui-toggle-details/src/ToggleDetails/README.md
- packages/ui-toggle-details/src/ToggleDetails/index.tsx
- packages/ui-toggle-details/src/ToggleDetails/styles.ts
Closes: INSTUI-4190
Test:
Try expanding and closing ToggleDetails controlled and uncontrolled examples in our docs app. Observe if the component flickers.
I tested whether changing properties causes flickering or any other issues, it does not. You can use the below code for testing:
```ts
const Example = () => {
const [state, setState] = useState({
expanded: true,
fluidWidth: true,
iconPosition: 'start',
size: 'small',
variant: 'default'
});
const handleChange = (field, value) => setState(prevState => ({ ...prevState, [field]: value }));
const handleToggle = () => setState(prevState => ({ ...prevState, expanded: !prevState.expanded }));
const renderOptions = () => {
const { fluidWidth, iconPosition, size, variant } = state;
const options = [
{ name: 'iconPosition', values: ['start', …
```
> fix(ui-toggle-details): fix ToggleDetails flickering

- packages/ui-calendar/src/Calendar/index.tsx
backport of https://github.com/instructure/instructure-ui/pull/1681 to v9
> [v9] fix(ui-calendar): fix code to remove unnecessary warnings

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-table/src/Table/ColHeader/index.tsx
- packages/ui-table/src/Table/ColHeader/props.ts
- packages/ui-table/src/Table/ColHeader/styles.ts
- packages/ui-table/src/Table/ColHeader/theme.ts
> fix(shared-types,ui-table): fix color contrast for table sorting icons

- packages/ui-table/src/Table/Body/index.tsx
- packages/ui-table/src/Table/Row/index.tsx
- packages/ui-table/src/Table/__new-tests__/Table.test.tsx
- packages/ui-table/src/Table/index.tsx
> fix(ui-table): non standrd Row children props

- packages/ui-buttons/src/BaseButton/theme.ts
Test plan: check if button's ic-brand variables can be overridden and the changes apply or not
Closes: INSTUI-4338
> fix(ui-buttons): add back ic-brand theme tokens to basebutton

- packages/ui-number-input/src/NumberInput/README.md
- packages/ui-number-input/src/NumberInput/index.tsx
- packages/ui-number-input/src/NumberInput/props.ts
- packages/ui-table/src/Table/Head/index.tsx
> fix(ui-number-input): add back options for string input

- packages/ui-view/src/View/theme.ts
> fix(ui-view): fix view success colors

- cypress/component/DateInput2.cy.tsx
- packages/ui-date-input/src/DateInput2/__new-tests__/DateInput2.test.tsx
> test(ui-date-input): add new tests for DateInput2

- packages/ui-link/src/Link/theme.ts
- packages/ui-themes/src/themes/canvas/index.ts
> feat(ui-link): update Link's color

- packages/ui-rating/src/Rating/README.md
- packages/ui-rating/src/RatingIcon/index.tsx
Also remove a not needed div and make the icon aria-hidden because VO reads sometimes a lots of empty groups
closes: INSTUI-4307
> fix(ui-rating): add text value to Rating examples

- docs/contributor-docs/v10-upgrade-guide.md
> docs: fix typos in the v10 upgrade guide

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-text/src/Text/README.md
- packages/ui-text/src/Text/props.ts
- packages/ui-text/src/Text/styles.ts
- packages/ui-text/src/Text/theme.ts
> feat(ui-text,shared-types): add warningColor to Text component

- cypress/component/Tooltip.cy.tsx
INSTUI-4479
This PR adds tests to cover issues fixed in this PR: https://github.com/instructure/instructure-ui/pull/1889
TEST PLAN:
- review the new tests
> test: add tests for Tooltip bug fix

- package-lock.json
- packages/ui-breadcrumb/package.json
- packages/ui-breadcrumb/tsconfig.build.json
- packages/ui-buttons/src/BaseButton/__new-tests__/BaseButton.test.tsx
- packages/ui-buttons/src/BaseButton/index.tsx
This is added by the browser for interactive element. Also fix builds failing due to missing import in Breadcrumb
Fixes INSTUI-4499
> fix(ui-buttons): fix tabindex=0 added unnecessarly to Buttons

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-buttons/src/BaseButton/theme.ts
- packages/ui-color-picker/src/ColorIndicator/theme.ts
- packages/ui-color-picker/src/ColorMixer/ColorPalette/theme.ts
- packages/ui-color-picker/src/ColorMixer/Slider/theme.ts
- packages/ui-color-picker/src/ColorPicker/theme.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/theme.ts
- packages/ui-file-drop/src/FileDrop/theme.ts
- packages/ui-heading/src/Heading/theme.ts
- packages/ui-modal/src/Modal/ModalFooter/theme.ts
- packages/ui-modal/src/Modal/ModalHeader/theme.ts
- packages/ui-navigation/src/AppNav/theme.ts
- packages/ui-number-input/src/NumberInput/theme.ts
- packages/ui-table/src/Table/Cell/theme.ts
- packages/ui-tag/src/Tag/theme.ts
- packages/ui-toggle-details/src/ToggleDetails/theme.ts
- packages/ui-tray/src/Tray/theme.ts
- packages/ui-view/src/ContextView/theme.ts
TEST_PLAN: 
Check all the blue outlined values in this document:
[docs](https://docs.google.com/spreadsheets/d/16_GjG_LvCvvvkdvFNTcrC11P81GwwSRyWGxKbc5RWeE/edit?pli=1&gid=0#gid=0)
They need to be changed in the `theme.ts` files of their respective components and in the `packages/shared-types/src/ComponentThemeVariables.ts` file as well
Closes: INSTUI-4503
> fix(ui-buttons): fix button border color

- packages/ui-menu/src/Menu/MenuItem/styles.ts
- packages/ui-options/src/Options/Item/styles.ts
TEST PLAN:
check options and menu hover animations. They should look better now. Whatever better means :D 
(on hover the color changes should be instant, on mouse leave it should have a 200ms transition time)
INSTUI-4502
> fix(ui-options,ui-menu): improve hover animations

- packages/ui-scripts/lib/icons/generate-react-components.js
> feat(ui-scripts): add new ai-colored icon (temp solution)

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-list/src/InlineList/InlineListItem/styles.ts
- packages/ui-list/src/InlineList/InlineListItem/theme.ts
INSTUI-4569
Test
1. Override delimiterColor of InlineList.Item and check if delimiter color changes
> feat(ui-list,shared-types): ability to override delimiter color

- packages/emotion/src/InstUISettingsProvider/index.tsx
TEST_PLAN: check the docs locally to see if any proptype related issues pop up when visiting any components
INSTUI-4566
> fix(emotion): fix proptype definition

- packages/ui-buttons/src/BaseButton/styles.ts
TEST_PLAN: check if circular ai icon buttons look ok
INSTUI-4627
> feat(ui-buttons): add circular ai icon buttons

- packages/ui-heading/src/Heading/styles.ts
test plan: print the ai heading page and check the gradient text shows up in black
INSTUI-4692
> fix(ui-heading): fix ai heading not showing up on print

- packages/ui-buttons/src/BaseButton/index.tsx
- packages/ui-buttons/src/BaseButton/props.ts
- packages/ui-view/src/View/index.tsx
- packages/ui-view/src/View/props.ts
Test plan: Check and think about what could go wrong since this change narrows the type of all View elements to HTMLElement from Element
INSTUI-4696
> fix(ui-view,ui-buttons): clarify typing of elementRefs

- package-lock.json
- packages/ui-view/package.json
`ui-prop-types` no longer exists in v11
> fix(ui-view): remove ui-prop-types dependency that was left in accidentally after the v11 release
