- .travis.yml
- README.md
Before merging this PR please enable Travis integration:
1. Open https://travis-ci.org/profile/instructure
2. Slick Sync (if necessary)
3. Slide-enable `instructure-ui`
The image badge will be broken until this is merged into master and run for the first time.
I tested it in my fork and looks good: [![build-status][build-status]][build-status-url]
[build-status]: https://travis-ci.org/elgalu/instructure-ui.svg?branch=add-travis-ci
[build-status-url]: https://travis-ci.org/elgalu/instructure-ui "Travis CI"
> build(ci): Add TravisCI integration

- packages/ui-testable/package.json
If the project ui-testable is used in isn’t pulling in a newish version of table then you can end up getting an error of:
Module not found: Error: Can't resolve '@babel/runtime/helpers/esm/createSuper' 
This makes this module explicitly depend on a newer version of @babel/runtime so that this can’t happen.
Fixes #94
> Fixes for createSuper being undefined.

- packages/ui-a11y-utils/src/ScreenReaderFocusRegion.js
- packages/ui-a11y-utils/src/__tests__/ScreenReaderFocusRegion.test.js
ScreenReaderFocusRegion hides a bunch of nodes when modals, trays,
etc open so the SR can focus on their content. We shouldn't hide
elements with aria-live=[assertive|polite] since these tags instruct
the SR to read a message ASAP.
fixes INSTUI-2700
refs LS-1532
Test plan:
- Go to Canvas Dashboard
- Click the hamburger menu button on one of the courses
- Open dev tools and inspect the page
- #flash_screenreader_holder should NOT be aria-hidden
> fix(ui-a11y-utils): don't hide elements with aria-live

- packages/ui-view/src/View/index.js
- packages/ui-view/src/View/styles.js
Some styles still need to be added as inline styles so it overrides the class style values and
defaults from the component.
TEST PLAN:
Properties like margin update well when passed as props to View, overriding defaults in the
component style.js
> fix(ui-view): view component should use inline styles again

- packages/ui-scripts/lib/generate-types.js
Closes: INSTUI-2813
some files are using newer JS features (e.g. `?.` ) and the TypeScript definition generation script
needed to be updated to handle this.
Also add better error handling, it was not outputting which file caused the failure
> chore(ui-scripts): fix TypeScript type definition build for files that use newer syntax

- packages/ui-img/src/Img/__tests__/Img.test.js
- packages/ui-img/src/Img/index.js
- packages/ui-img/src/Img/styles.js
Closes: INSTUI-2824
Refactored Img component to handle cover-contain constrains and filters well again. Fixed tests and
turned them back on.
TEST PLAN:
Img displays correctly with contain and/or filters set.
> INSTUI-2824 - fix img component constrain, filter and tests

- packages/console/macro.js
This will get rid of the warnings in WebStorm and add nice hints how to use it.
> docs(console): add documentation for the log commands

- packages/babel-plugin-transform-imports/lib/index.js
node 12 did some weird thing with the require.resolve method, its likely responsible for this bug. 
see e.g. https://github.com/aws/aws-cdk/commit/286866aa2a0c01adf90923524fce2fd2c6ff9c25 and https://github.com/nodejs/node/issues/27583
It also fixes the error messages during build that look like `[babel-plugin-transform-imports] no modules match '${importName}' in '${packageName}'....`
> chore(babel-plugin-transform-imports): fix docs build

- packages/babel-plugin-transform-imports/lib/index.js
same as https://github.com/instructure/instructure-ui/pull/339 just on `next` branch
> chore(babel-plugin-transform-imports): fix docs:bundle build on Next branch

- packages/ui-icons-build/package.json
- yarn.lock
it was using an old version of node-gyp, which had this issue: https://github.com/nodejs/node-gyp/issues/1927
> chore(ui-icons-build): upgrade gulp-iconfont to prevent build issues on OSX Catalina

- packages/ui-popover/src/Popover/index.js
- packages/ui-tooltip/src/Tooltip/README.md
- packages/ui-tooltip/src/Tooltip/__tests__/Tooltip.test.js
https://www.w3.org/WAI/WCAG21/Understanding/content-on-hover-or-focus.html
Persistent
The intent of this condition is to ensure users have adequate time to perceive the additional content after it becomes visible. Users with disabilities may require more time for many reasons, such as to change magnification, move the pointer, or simply to bring the new content into their visual field. Once it appears, the content should remain visible until:
The user removes hover or focus from the trigger and the additional content, consistent with the typical user experience
> INSTUI-2698 Tooltips don't dismiss when hovered over

- packages/ui-buttons/src/ToggleButton/ToggleButtonLocator.js
- packages/ui-calendar/src/index.js
- packages/ui-date-input/src/DateInput/DateInputLocator.js
- packages/ui-menu/src/Menu/MenuLocator.js
- packages/ui-navigation/src/Navigation/NavigationItem/NavigationItemLocator.js
- packages/ui-options/src/index.js
- packages/ui-pagination/src/Pagination/PaginationArrowButton/PaginationArrowButtonLocator.js
- packages/ui-pill/src/Pill/PillLocator.js
- packages/ui-popover/src/Popover/PopoverLocator.js
- packages/ui-popover/src/index.js
- packages/ui-position/src/index.js
- packages/ui-select/src/Select/SelectLocator.js
- packages/ui-select/src/index.js
- packages/ui-simple-select/src/SimpleSelect/SimpleSelectLocator.js
- packages/ui-time-select/src/TimeSelect/TimeSelectLocator.js
- packages/ui-tooltip/src/Tooltip/TooltipLocator.js
- packages/ui-tooltip/src/index.js
This is a revert of this commit: https://github.com/instructure/instructure-ui/commit/579ab2f4f0bfe9e46590e25a4c5743b28a445761 
This is no longer needed because with module type = commonJS we can import from any place again. Also it broke apps because `ui-test-locator` is declared as a `devDependency `
> refactor(XXLocator): Allow importing from es/ again.

- packages/ui-tabs/src/Tabs/Tab/__tests__/theme.test.js
- packages/ui-tabs/src/Tabs/Tab/styles.js
- packages/ui-tabs/src/Tabs/Tab/theme.js
This will keep the colors of normal and secondary tabs consistent
TEST PLAN:
check changes in docs app; run tests
BREAKING CHANGE:
SecondarySelectedColor style was removed, now just secondaryColor determines the color of the
secondary tab.
VISUAL CHANGE:
SecondaryColor changed to textDarkest, in the Canvas theme to
ic-brand-font-color-dark
> INSTUI-2835 change the color of unselected tabs to the same as selected ones

- packages/ui-webpack-config/package.json
- yarn.lock
its also used by ui-scripts/package.json by @codesandbox/common": "^1.0.8, but this is its latest version, I've left a comment to nag them https://github.com/codesandbox/codesandbox-client/pull/5384 
Fixes https://github.com/instructure/instructure-ui/issues/409
needs to be done in the `master` branch too
> INSTUI-2890: update react-dev-utils to update immer

- packages/ui-docs-client/src/Glyph/index.js
- packages/ui-docs-client/src/Glyph/styles.js
- packages/ui-docs-client/src/Glyph/theme.js
Closes: INSTUI-2895
To improve performance of the iconography page, refactored the Glyph component not to use
IconButton. It is a html button with its own styling now.
TEST PLAN:
Iconography page looks the same as before, just loads faster.
> INSTUI-2895 - speed up iconography page

- packages/ui-docs-client/src/App/index.js
Show CHANGELOG for the last 2 major versions. Below that, link to the GitHub changelog page for
later versions.
Closes: INSTUI-2898
> INSTUI-2898 - show changelog only for the last 2 major versions

- packages/ui-themes/package.json
Looks like `@instructure/ui-themes` is missing a CommonJS build, which Canvas needs since it requires in those themes in several places where we run Jest tests.
> fix: Add CommonJS build to @instructure/ui-themes

- packages/ui-position/src/calculateElementPosition.js
Closes: INSTUI-2863
After the "themeable to emotion" migration of the tooltip component it started jumping on show. The
fix was found in `ui-position`: we should hide the component offscreen until it has a non-zero
height and width to measure for the positioning.
> INSTUI-2863 -  stop tooltip from "jumping" on show

- packages/ui-checkbox/package.json
- packages/ui-checkbox/src/Checkbox/index.js
Closes: INSTUI-2808
Fixed bug: added spacing between the single checkbox and its error/info messages.
TEST PLAN:
When `messages` are passed to a single `Checkbox`, the messages are not supposed to be pressed up to
the label anymore.
BREAKING CHANGE:
VISUAL CHANGE: Since there is more space between the checkbox and the messages, it can potentially break layouts (vertically more pixels).
> INSTUI-2808 - add spacing between single checkbox and messages

- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/__tests__/TreeButton.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/styles.css
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/__tests__/TreeCollection.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/__tests__/TreeNode.test.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/index.js
- packages/ui-tree-browser/src/TreeBrowser/__tests__/TreeBrowser.test.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
closes OUT-4216
test-plan:
- run docs app locally
- ensure before/afterCollection props work as expected
- test the above with VO/NVDA
> feat(ui-tree-browser): allow tree browser to render before, after nodes

- packages/__examples__/babel.config.js
- packages/ui-babel-preset/lib/index.js
Added back the ie field to the browserlists config in case of storybook build.
There is an issue with the storybook production build with babel-preset env when the browserlists config does not contain the ie reference. The issue might be that our own `component-examples-loader` cannot process such syntax that is outputted by the babel-loader.
I tried to pinpoint which babel-preset plugin could be missing by comparing the used plugins when ie is in our browserlists config and when it is not, but I could not find a plugin configuration that would output correct code.
Here is the plugins used by babel-loader when ie is in the browserlists config:
```js
with IE
[storybook]   proposal-numeric-separator { "ie":"11" }
[storybook]   proposal-logical-assignment-operators { "ie":"11", "ios":"13.4", …
```
> chore(ui-babel-preset): add option to change browserlists config to babel-preset

- packages/ui-icons-build/lib/tasks/generate-react/component.ejs
it had a value in v7, but was removed by the removal of the postCSS plugin
> INSTUI-2913 Add displayName to icons

- packages/ui-byline/src/Byline/styles.js
- packages/ui-form-field/src/FormFieldLabel/styles.js
- packages/ui-heading/src/Heading/styles.js
- packages/ui-link/src/Link/index.js
- packages/ui-link/src/Link/styles.js
- packages/ui-menu/src/Menu/MenuItem/styles.js
- packages/ui-navigation/src/AppNav/Item/styles.js
- packages/ui-radio-input/src/RadioInput/styles.js
- packages/ui-text/src/Text/styles.js
During the Emotion Migration we used a workaround to style items with selectors strengthened with html tag selectors, eg.: `input.root[type]`.
This turned out to be a bad decision, because most of our components accept an "as" property (if you want to render the component "as button" instead of the default "as a" for example). If you pass a complex component instead of a string to the "as" prop though, the new solution didn't apply the styles, because the elementType was a function instead of a valid html tag name.
Refactored the code to use the css `&:is(input)` selectors, because they apply as css classes once the DOM is fully rendered and the component is boiled down to the final html element.
> INSTUI-2908 - fix html tag based styling

- packages/ui-byline/src/Byline/styles.js
- packages/ui-form-field/src/FormFieldLabel/styles.js
- packages/ui-heading/src/Heading/styles.js
- packages/ui-link/src/Link/styles.js
- packages/ui-menu/src/Menu/MenuItem/styles.js
- packages/ui-navigation/src/AppNav/Item/styles.js
- packages/ui-radio-input/src/RadioInput/styles.js
- packages/ui-text/src/Text/styles.js
Closes: INSTUI-2917
Chromatic tests use Chrome v84 for snapshots, which doesn't support the newer `:is()` css selector.
Extend the usages with the older `:-webkit-any()` selector.
> INSTUI-2917 - refactor: add css :-webkit-any() selector to :is()

- packages/ui-byline/src/Byline/styles.js
- packages/ui-form-field/src/FormFieldLabel/styles.js
- packages/ui-heading/src/Heading/styles.js
- packages/ui-link/src/Link/styles.js
- packages/ui-menu/src/Menu/MenuItem/styles.js
- packages/ui-navigation/src/AppNav/Item/styles.js
- packages/ui-radio-input/src/RadioInput/styles.js
- packages/ui-text/src/Text/styles.js
Closes: INSTUI-2918
Needed to separate the vendor prefixed css selectors to different groups, because if any one of them
in the group is invalid in a browser, the whole group counts as invalid. See more info here:
https://www.w3.org/TR/selectors-3/#grouping.
> INSTUI-2918 - fix prefixed css selector grouping

- docs/guides/themeable-to-emotion-migration-guide.md
- packages/instui-config/codemod-configs/v8/imports.config.js
Closes: INSTUI-2892
Some utils were moved from `ui-themeable` to `emotion` package, so we made a codemod to take care of
the import transforms.
> INSTUI-2892 - add codemod for themeable util imports

- packages/ui-code-editor/package.json
- yarn.lock
Closes: INSTUI-2918
Codemirror was updated, and the new version was causing vertical scrollbars to appear even if the
content fit the box. Downgraded to version 5.48.4 with which it worked as intended.
> INSTUI-2928 - fix vertical scrollbar on code editors

- packages/ui-tag/src/Tag/styles.js
Closes: INSTUI-2923
Refactored the code so the ':before' object doesn't get overwritten, thus breaking the focus state
indicator.
> INSTUI-2923 - fix dismissable tag focus state

- packages/ui-select/src/Select/index.js
Select crashes in multi select mode when selecting all elements and then clicking outside the component
> INSTUI-2957: fix null pointer exception in Select

- package.json
- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/styles.css
Closes: INSTUI-2956
Backporting fix from PR #460: Tweaked the vertical line of "large" sized collections not to extend
into the collection icon.
Also tweaked the "small" sized collection to have the line ending closer
to the icon.
Added a size selector in the first example of TreeBrowser to be able to preview all
available sizes.
> INSTUI-2956 - backport fix to remove line extending into root icon

- packages/canvas-high-contrast-theme/README.md
- packages/canvas-theme/README.md
- packages/instructure-theme/README.md
- packages/ui-docs-client/src/App/index.js
- packages/ui-docs-client/src/Theme/index.js
- packages/ui-themes/README.md
Closes: INSTUI-2959
There were a few places in the docs where we still showed the deprecated "theme.use()" method.
Updated it to the v8 version.
> INSTUI-2959 - docs: update deprecated theme usage info in docs

- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/TreeButton/styles.js
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/TreeNode/index.js
- packages/ui-tree-browser/src/TreeBrowser/__tests__/TreeBrowser.test.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
Closes: INSTUI-2964
Fixed the error when the items of the root collection are not rendered when `showRootCollection` is
set to `false`. Added an interactive example on the docs page to show how `showRootCollection`
works.
TEST PLAN:
Root items are rendered too when `showRootCollection` is set to false. The `aria-level` values are
correct on every level.
> INSTUI-2964 - list root items too when `showRootCollection` is `false`

- packages/template-app/package.json
- packages/template-app/template/webpack.config.js.ejs
- packages/ui-template-scripts/lib/utils/createFromTemplate.js
- yarn.lock
template-app was throwing an error when running.
To test:
1. Add the following to the main `package.json` in the `scripts` part: `"generate:app": "instui create app --name packages/test123",`
2. run this command
3. in the genrated app in package.json rename name to `test123`
4. try out the scripts in the generated `package.json`
> INSTUI-2975: fix template app generation error

- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/TreeCollection/index.js
- packages/ui-tree-browser/src/TreeBrowser/__tests__/TreeBrowser.test.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
Closes: INSTUI-2965
Backport of fix on v8 (INSTUI-2964, PR #476). Fixed the error when the items of the root collection are not rendered when `showRootCollection` is
set to `false`. Added an interactive example on the docs page to show how `showRootCollection`
works.
TEST PLAN:
Root items are rendered too when `showRootCollection` is set to false. The `aria-level` values are
correct on every level.
> INSTUI-2965 - list root items too when `showRootCollection` is `false`

- docs/guides/v8-deprecations.md
- packages/ui-dom-utils/src/addResizeListener.js
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/index.js
- packages/ui-navigation/src/AppNav/index.js
- packages/ui-responsive/src/addElementQueryMatchListener.js
- packages/ui-tabs/src/Tabs/index.js
- packages/ui-text-area/src/TextArea/index.js
- packages/ui-truncate-text/src/TruncateText/index.js
Closes: INSTUI-2875
Refactor `addResizeListener` to the native DOM ResizeObserver API in all places.
Created v8
deprecation guide.
Add info about deprecation to the `addResizeListener` doc page.
TEST PLAN:
Test the affected components.
> refactor: refactor `addResizeListener` usage to ResizeObserver

- packages/ui-drawer-layout/src/DrawerLayout/__examples__/DrawerLayout.examples.js
This test is very flaky, probably because of the animation (chromatic screenshots have few px diff).
Couldn't find any fix for it so far. Added TODO to try again later (maybe better tools or configs
will be available).
> test(ui-drawer-layout): deactivate flaky VRT check

- packages/ui-scripts/lib/tag.js
Imported missing `confirm` util from `@instructure/command-utils`.
> chore(ui-scripts): fix npm tag script

- lerna.json
The prop is no longer used, see https://github.com/lerna/lerna#legacy-fields
> refactor: remove unused prop in lerna.json

- packages/ui-link/src/Link/styles.js
Link outline was not showing because of a CSS issue
> INSTUI-2976 : Fix ui-link not displaying outline on focus

- .github/workflows/vrt.yml
Added v7_maintenance branch to the vrt worflow, so chromatic tests run on push events and PR-s.
> chore: add vrt checks on v7_maintenance branch

- .github/workflows/manual-release-to-npm-and-deploy-to-legacy-gh-pages.yml
- .github/workflows/manual-release-to-npm.yml
- packages/ui-scripts/lib/fix-publish.js
- packages/ui-scripts/lib/publish.js
not on current version release tag: vx_maintenance
Closes: INSTUI-2979
> chore(ui-scripts): fix release tagging on npm (INSTUI-2979)

- packages/ui-menu/src/Menu/MenuItem/index.js
- packages/ui-menu/src/Menu/index.js
Closes: INSTUI-2983
Fixed a bug where you couldn't highlight a submenu trigger with keyboard navigation.
TEST PLAN:
You can tab through all items in the Menu, including the submenu triggers.
> fix(ui-menu): fix Menu keyboard navigation on submenus

- packages/ui-list/src/List/__examples__/List.examples.js
- packages/ui-list/src/List/index.js
- packages/ui-view/src/View/__examples__/View.examples.js
- packages/ui-view/src/View/index.js
Reverted to the usage of `deprecated.deprecatePropValues()` in View and List, so it doesn't spam the
console with invalid deprecation errors on View's `background` and List's `delimiter` props. Also
made some filters for View's Storybook example generation.
Closes: INSTUI-2992
> fix(ui-list,ui-view): remove invalid "deprecated prop value" warnings

- packages/ui-babel-preset/lib/index.js
- packages/ui-babel-preset/package.json
- yarn.lock
Remove Babel plugins for object spread and optional chaining. These are supported in recent
browsers, shimming them will just result in performance degradation and larger code size
> Feat(ui-babel-preset): remove not needed Babel plugins

- packages/ui-babel-preset/lib/index.js
- packages/ui-babel-preset/package.json
Removed `babel-plugin-add-import-extension` because it interfered with `webpack` since we are using the
`babel-loader` to transpile `.ts` files on the fly in development and this plugin injected `.js` extensions to the
imports which made the `docs-app` unusable in dev mode.
> Remove babel-plugin-add-import-extension

- packages/ui-docs-client/tsconfig.build.json
- packages/ui-docs-client/tsconfig.json
- packages/ui-docs-plugin/tsconfig.build.json
- packages/ui-docs-plugin/tsconfig.json
- packages/ui-postcss-config/tsconfig.build.json
- packages/ui-postcss-config/tsconfig.json
- packages/ui-stylesheet/tsconfig.build.json
- packages/ui-stylesheet/tsconfig.json
- packages/ui-themeable/tsconfig.build.json
- packages/ui-themeable/tsconfig.json
Some of our formerly deleted packages reappeared when running a script generating typescript configs
in all packages. Removed unnecessary packages and config files.
> chore: delete accidentally reappeared deprecated packages

- packages/ui-webpack-config/package.json
- yarn.lock
The verion of `terser-webpack-plugin` which we used had a [dependency](https://github.com/webpack-contrib/terser-webpack-plugin/blob/v2.3.8/package.json#L44) on `cacache@13` which had a [dependency](https://github.com/npm/cacache/blob/v13.0.1/package.json#L77) on `ssri@v7` which had a [security issue](https://snyk.io/vuln/SNYK-JS-SSRI-1085630) in it.
This fix updates the `terser-webpack-plugin` to a [version](https://github.com/webpack-contrib/terser-webpack-plugin/blob/v4.2.3/package.json#L44) which depends on a [version of](https://github.com/npm/cacache/blob/v15.0.6/package.json#L75) `cacache` which contains the fixed `ssri` package.
https://github.com/npm/ssri/blob/v6/CHANGELOG.md#602-2021-04-07
https://github.com/npm/ssri/blob/latest/CHANGELOG.md#801-2021-01-27
> Update `terser-webpack-plugin` dependency

- packages/__docs__/babel.config.js
Also the EsModules parameter was not passed correctly thus not allowing tree shaking
> INSTUI-3013 : fix: documentation app was not reloading on changes

- packages/__examples__/package.json
- packages/__examples__/renderExample.js
- packages/ui-dialog/src/Dialog/index.tsx
- packages/ui-menu/src/Menu/__examples__/Menu.examples.tsx
Closes: INSTUI-3008
If a Dialog contains a focusable item, that item gets focused when the dialog opens. The browsers
automatically scroll the the focused element, but if the content and its css is not yet fully
loaded, the position of the focusable item might be not yet calculated, making the page jump to the
top. Now we wait a heartbeat before focusing the element. This fix affects other components using
`Dialog` under the hood: `DrawerLayout`, `Modal`, `Overlay`, `Popover` and `Tray`, and components
using these (e.g. Menu).
> fix(ui-dialog): fix page scrolling up when Menu opens

- packages/ui-dialog/src/Dialog/index.js
Closes: INSTUI-3016
If a Dialog contains a focusable item, that item gets focused when the dialog opens. The browsers
automatically scroll the the focused element, but if the content and its css is not yet fully
loaded, the position of the focusable item might be not yet calculated, making the page jump to the
top. Now we wait a heartbeat before focusing the element. This fix affects other components using
`Dialog` under the hood: `DrawerLayout`, `Modal`, `Overlay`, `Popover` and `Tray`, and components
using these (e.g. Menu).
> INSTUI-3016 - menu fix v7 backport

- packages/ui-dialog/src/Dialog/index.js
refs: INSTUI-3017
If a Dialog contains a focusable item, that item gets focused when the dialog opens. The browsers
automatically scroll the the focused element, but if the content and its css is not yet fully
loaded, the position of the focusable item might be not yet calculated, making the page jump to the
top. Now we wait a heartbeat before focusing the element. This fix affects other components using
`Dialog` under the hood: `DrawerLayout`, `Modal`, `Overlay`, `Popover` and `Tray`, and components
using these (e.g. Menu).
> INSTUI-3017 - fix page scrolling up when Menu opens

- packages/__docs__/buildScripts/build-docs.js
only the readme.md file will be shown for this package
> chore: remove `ui-scripts` source code from docs app

- packages/ui-table/src/Table/ColHeader/index.tsx
- packages/ui-table/src/Table/Head/index.tsx
- packages/ui-table/src/Table/README.md
- packages/ui-table/src/Table/__tests__/Table.test.tsx
Closes: INSTUI-3116
The new `stackedSortByLabel` prop will allow users to set custom strings to the labels appearing in
the "sort by" select of a sortable table with stacked layout. It is using the `id` prop by default,
which is not always a user-friendly string. It will also allow to display longer, more descriptive
labels.
> feat(ui-table): add `stackedSortByLabel` prop to `Table.ColHeader`

- .github/workflows/pr-validation.yml
This PR contains some changes which enhances the current pr_validation workflow with the following:
- build the documentation app from the branch of the PR
- deploy it to netlify
- a github bot will create (and update) a comment with the most recent preview URL
> chore: add deploy preview to PR validation workflow

- packages/__docs__/src/Search/index.js
Had to change how the current way of handling the location change works for the main search bar (on the top of the page at the #index page), because the current solution overrides the selected version in the url.
Changed it so it only rewrites the #hash part of the url.
> chore: fix location handling in main search bar

- packages/ui-docs-client/src/Search/index.js
Had to change how the current way of handling the location change works for the main search bar (on the top of the page at the #index page), because the current solution overrides the selected version in the url.
Changed it so it only rewrites the #hash part of the url.
> chore(ui-docs-client): change location handling in main searchbar --V7

- .github/workflows/deploy-docs-to-netlify.yml
- .github/workflows/release.yml
replaced the current github pages docs steps with the netlify deploy in the release workflow
> chore: deploy docs to netlfiy instead of github pages when releasing

- packages/ui-tree-browser/src/TreeBrowser/__tests__/TreeBrowser.test.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
TEST PLAN:
Render a TreeBrowser with several collections, one of which has id === 0. Specify rootId={0} and
showRootCollection={false}. The root collection should be properly hidden.
> fix(ui-tree-browser): properly hide root collection if rootId === 0

- packages/ui-buttons/package.json
- packages/ui-buttons/src/BaseButton/index.tsx
- packages/ui-buttons/src/BaseButton/styles.ts
- packages/ui-buttons/src/BaseButton/theme.ts
Replace the Flex component with simple span inside BaseButton for better performance. In the testing tool it resulted in ~40% performance improvement testing 100 times with a Button that has an icon and text:
BUTTON_ICON_IUIx100	832.9ms  // old, 8.4.0 code
BUTTON_ICON_IUIx100	504.4ms  // new code in this PR
It should improve performance with other types of button too, albeit to a lesser degree
> INSTUI-2932 : Replace <Flex> with <span> in Button to improve performance

- packages/ui-options/src/Options/Item/__tests__/Item.test.tsx
- packages/ui-options/src/Options/Item/index.tsx
- packages/ui-options/src/Options/README.md
- packages/ui-select/src/Select/README.md
- packages/ui-select/src/Select/__tests__/Select.test.tsx
- packages/ui-select/src/Select/index.tsx
- packages/ui-simple-select/package.json
- packages/ui-simple-select/src/SimpleSelect/README.md
- packages/ui-simple-select/src/SimpleSelect/__tests__/SimpleSelect.test.tsx
- packages/ui-simple-select/src/SimpleSelect/index.tsx
Closes: INSTUI-2903
If a function is passed to `renderBeforeLabel` or `renderAfterLabel` prop, the function will have a
`props` parameter. This way the the properties of that `Option.Item` (e.g. the current `variant`) is
accessible in the render function, and can be used to set different colors to that icon for
different option state (variant).
> feat(ui-options): add option to recolor the icon of Option.Item

- packages/ui-popover/src/Popover/index.js
> V7: fix(ui-popover): inverse color Popover without arrow shouldn't have light border

- packages/ui-popover/src/Popover/index.tsx
Closes: INSTUI-3157
The 3 props, `offsetX`, `offsetY` and `placement` were used from the state, and didn't update if any
of these 3 props changed (e.g. when set from the `Responsive` component). They only updated if the
position of the `Popover` changed, now it updates and recalculates correctly on prop change as well.
> fix(ui-popover): recalculate offset and position on prop change

- packages/__docs__/components.js
- packages/emotion/src/EmotionThemeProvider/README.md
Import our themes for the docs app so it can be used in example codes
Wrap EmotionThemeProvider examples `<EmotionThemeProvider>` tags, so its clear that they are needed and users can easily edit the code to change its values.
This makes the whole page more clear, helping with issues like https://github.com/instructure/instructure-ui/issues/612
> Fix emotion examples

- packages/__docs__/src/App/index.js
- packages/__docs__/src/App/styles.js
- packages/__docs__/src/Header/index.js
- packages/__docs__/src/index.html
- packages/__docs__/src/versionData.js
Closes: INSTUI-3148
If someone is viewing the docs page of a legacy version, we want to display a warning on the bottom of
the page.
> docs: add warning stripe on legacy doc pages

- packages/__docs__/buildScripts/build-docs.js
- packages/ui-scripts/bin/specify-commonjs-format.js
- packages/ui-template-scripts/lib/handlers/handleCreateFromTemplate.js
Fixes errors during build like:
```
@instructure/ui-form-field: [] internal/fs/utils.js:308
@instructure/ui-form-field: []     throw err;
@instructure/ui-form-field: []     ^
@instructure/ui-form-field: [] 
@instructure/ui-form-field: [] Error: EEXIST: file already exists, mkdir 'lib'
@instructure/ui-form-field: []     at Object.mkdirSync (fs.js:987:3)
@instructure/ui-form-field: []     at Object.<anonymous> (/instructure-ui/packages/ui-scripts/bin/specify-commonjs-format.js:30:6)
@instructure/ui-form-field: []     at Module._compile (internal/modules/cjs/loader.js:1063:30)
```
> Fix rare race condition in mkdirSync code

- packages/ui-dialog/src/Dialog/index.tsx
Closes: #623
Fixes race condition where Dialog may unmount before the immediate setTimeout completes, causing
dangling focus region
> fix(ui-dialog): cleanup pending timeouts on unmount

- packages/ui-icons-build/lib/tasks/optimize-svgs/index.js
- packages/ui-icons-build/package.json
- yarn.lock
Closes: INSTUI-3199
Thus commit also contains a new custom svgo plugin for new icons. If the svg file has multiple paths
as children, this plugin will wrap them into a `<g>` group, because svg files have to have a single
child to display correctly.
> feat(ui-icons-build): update `gulp-svgmin` dependency to v4

- packages/ui-options/src/Options/index.tsx
Closes: INSTUI-3203
Fixes the bug where `Select.Group` labels counted as "groups" when VoiceOver announced select groups
(e.g. 2 groups counted as 4), even if you couldn't select t..
> fix(ui-options): add aria-hidden to Options label span

- packages/ui-billboard/src/Billboard/styles.ts
Changed margin-top for heading when `size` property is set to `small`. Now it's
`componentTheme.mediumMargin` instead of `componentTheme.largeMargin`
TEST PLAN:
Open documentation for the Billboard component. Check that margin is correct in the example with
`size` set to `small`
> fix(ui-billboard): fix heading margin when `size` is `small`

- packages/__docs__/buildScripts/utils/getReactDoc.js
- packages/__docs__/package.json
- yarn.lock
This PR fix the issue with our current solution for importing propTypes and TS types not showing up in the documentation.
It uses an upcoming feature of `react-docgen`, thus I bumped its version from 5 to 6.alpha
For more info: https://github.com/reactjs/react-docgen/pull/352
> docs: fix imported types not showing up in docs

- packages/ui-position/src/PositionPropTypes.ts
- packages/ui-position/src/calculateElementPosition.ts
Marked as `refactor` instead of `fix`, because the problematic code was not released yet (in the ui-position typing PR).
Closes: INSTUI-3237
> refactor(ui-position): fix offset calculation for Position

- packages/__docs__/src/Hero/index.js
Closes: INSTUI-3244
The A11y team's audit concluded, that JAWS in other browsers works well as well
> docs: removing 'firefox only' note for JAWS in docs (INSTUI-3244)

- packages/emotion/src/withStyle.tsx
- packages/ui-i18n/src/bidirectional.tsx
When using the decorator the decorated method did not have the "allowedProps" static property, this
fix adds them back.
> fix(emotion,ui-i18n): decorator adds allowedProps property

- packages/__examples__/buildScripts/parsePropValues.js
- packages/ui-tabs/src/Tabs/Panel/styles.ts
- packages/ui-tabs/src/Tabs/README.md
- packages/ui-tabs/src/Tabs/__examples__/Tabs.examples.tsx
- packages/ui-tabs/src/Tabs/index.tsx
- packages/ui-tabs/src/Tabs/props.ts
- packages/ui-tabs/src/Tabs/styles.ts
Closes: INSTUI-3258
Refactored the DOM structure and CSS of Tabs component to have an extra wrapper for panels and use
flex layout under the hood. This makes it easier to handle the fix, min and max heights of the
component. Added a `fixHeight` prop to set a fix height, which can be set to `100%` now to fill the
parent element. Also added a few new examples.
> chore(ui-tabs): add 'fixHeight' prop to Tabs

- packages/ui-tabs/src/Tabs/README.md
Just a small correction to the first tab panel's `isSelected` prop name. Thanks!
> Fix small typo in ui-tabs readme

- packages/ui-popover/src/Popover/index.tsx
Closes: INSTUI-3261
Popover did not update when either plavement, shouldAlignArrow, or withArrow was changed. It
calculated placementOffset incorrectly when withArrow was false
> fix(ui-popover): popover does not update on certain prop changes (INSTUI-3261)

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-modal/src/Modal/ModalHeader/__tests__/ModalHeader.test.tsx
- packages/ui-modal/src/Modal/ModalHeader/index.tsx
- packages/ui-modal/src/Modal/ModalHeader/props.ts
- packages/ui-modal/src/Modal/ModalHeader/styles.ts
- packages/ui-modal/src/Modal/ModalHeader/theme.ts
- packages/ui-modal/src/Modal/README.md
Closes: INSTUI-3283
The new `spacing` prop allows setting a `compact` value to reduce the padding of the modal header.
This is used on smaller viewports.
> feat(ui-modal): add `spacing` prop to `Modal.Header`

- packages/ui-svg-images/src/InlineSVG/styles.css
Closes: INSTUI-3292
When applying zoom to the browser window, the edges of some icons could get chipped off due to the
fractional pixel size of the container. This happened because the user agent stylesheet applies
`svg:not(:root) { overflow: hidden }` on the SVG-s. We can allow overflow here, because all InstUI
icons are drawn to fit the square canvas, so there won't be any unwanted overflows, but lets the
cropped of edges to show in scaled windows. Backports the V8 version from INSTUI-3214, PR #746.
> fix(ui-svg-images): fix icons getting cropped in zoomed windows

- packages/ui-tabs/src/Tabs/Tab/index.tsx
- packages/ui-tabs/src/Tabs/Tab/styles.ts
- packages/ui-tabs/src/Tabs/index.tsx
Closes: INSTUI-3317
Needed to change the focus indication to display inside of the active tab instead of having a focus
ring around the whole Tab list. This way the Tabs component can be used in tight spaces whithout the
focus ring getting cut off.
> feat(ui-tabs): update Tabs focus styles to inset focus ring

- packages/ui-modal/src/Modal/README.md
Closes: INSTUI-3321
The title in the Modal.Header has to stay a h2 heading for a11y reasons.
> docs(ui-modal): update Modal header spacing example - V7

- packages/ui-time-select/src/TimeSelect/index.tsx
Closes: INSTUI-3308
Sometimes when there is a selected time and the select reopens, the
highlight not starts from the
selection, but rather from the first element
TEST PLAN:
- Pick a time
- set the focus to somewhere above the component
- with keyboard, navigate to the select
- open it
- navigate with arrows and see if the highlight starts from the selected element or not
> fix(ui-time-select): fix timeselect highlight behaviour (INSTUI-3308)

- packages/ui-modal/src/Modal/README.md
Closes: INSTUI-3320
The title in the Modal.Header has to remain a h2 heading for a11y reasons.
> docs(ui-modal): update Modal Header spacing example

- packages/ui-avatar/package.json
- packages/ui-avatar/src/Avatar/README.md
- packages/ui-avatar/src/Avatar/__examples__/Avatar.examples.js
- packages/ui-avatar/src/Avatar/__tests__/Avatar.test.js
- packages/ui-avatar/src/Avatar/__tests__/theme.test.js
- packages/ui-avatar/src/Avatar/index.js
- packages/ui-avatar/src/Avatar/styles.css
Closes: INSTUI-3330
Instead of the initials, an icon can be displayed inside the Avatar with the new `renderIcon`
property. It worls with the `color` and `size` properties as well.
The `hasInverseColor` prop
inverts the background color and the text/icon color. Inverted Avatars have no border.
Add logic
that in case the image is unset in an update, show icons/initials again.
Backports PR #781
> feat(ui-avatar): add `renderIcon` and `hasInverseColor` props to Avatar

- packages/ui-modal/src/Modal/ModalBody/__tests__/ModalBody.test.tsx
- packages/ui-view/src/View/__tests__/View.test.tsx
- packages/ui-view/src/View/index.tsx
- packages/ui-view/src/View/styles.ts
Closes: INSTUI-3271
Adding prop-based styling had no vendor prefixing.
Added inline styles to emotion's css prop and
added !important to every rule in it.
closes https://github.com/instructure/instructure-ui/issues/729
> INSTUI-3271 - feat(ui-view): vendor prefix all view style props

- packages/ui-text-area/src/TextArea/index.tsx
Closes: INSTUI-3332, https://github.com/instructure/instructure-ui/issues/810
when textarea has maxhight set and there are enough lines to have a scrollbar,
if the component is
scrolled up and typed into, it will scroll down on every input.
removing the seemingly useless
scrollheight setter from the code fixes the issue
> fix(ui-text-area): fix jumping scroll issue (INSTUI-3332)

- .github/workflows/pr-validation.yml
- dangerfile.ts
- scripts/calculateBundleSize.js
This PR fixes a couple of things:
- comments by github bot being overridden by the `maintain-one` github action, now instead the `pr-validation` workflow uses an another github action to post bot comments which enables multiple bot comments
- bundle size analysis will not be included in the comment, instead it will be logged out inside the `Calculate bundle size` step
- added threshold variable
> chore: remove bundle analysis from comment, put it inside job console

- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/__tests__/TreeBrowser.test.tsx
- packages/ui-tree-browser/src/TreeBrowser/index.tsx
- packages/ui-tree-browser/src/TreeBrowser/props.ts
According to [this issue](https://github.com/instructure/instructure-ui/issues/752), I have implemented a 'sortOrder' property to rearranged the appearance order of collections and items base on users' need. Closes https://github.com/instructure/instructure-ui/issues/752
> INSTUI-3304 ui-tree-browser: add 'sortOrder' property to TreeBrowser component

- packages/ui-tree-browser/src/TreeBrowser/README.md
- packages/ui-tree-browser/src/TreeBrowser/__tests__/TreeBrowser.test.js
- packages/ui-tree-browser/src/TreeBrowser/index.js
Closes: INSTUI-3339
The new `sortOrder` prop accepts an optional compare function to specify order of the collections
and the items.
Backports https://github.com/instructure/instructure-ui/pull/776
Original feature request: https://github.com/instructure/instructure-ui/issues/752
> INSTUI-3339 - add sortOrder prop to TreeBrowser

- packages/ui-text-area/src/TextArea/index.js
when textarea has maxhight set and there are enough lines to have a scrollbar, if the component
isscrolled up and typed into, it will scroll down on every input.
removing the seemingly useless
scrollheight setter from the code fixes the issue
> fix(ui-text-area): fix jumping scroll issue

- docs/guides/v7-deprecated-props-and-components.md
- packages/ui-text/src/Text/README.md
- packages/ui-text/src/Text/index.js
- packages/ui-text/src/Text/styles.css
- packages/ui-text/src/Text/theme.js
Closes: INSTUI-3355
The `warning` color variant will be removed in version 9.0.0, because it doesn't have sufficient
color contrast with the background (4.5:1) required for text.
Backports PR #856 for ticket INSTUI-3352.
> INSTUI-3355 - deprecate warning text

- packages/ui-options/src/Options/Item/props.ts
- packages/ui-options/src/Options/Item/styles.ts
Accidentally added the new props `beforeLabelContentVAlign` and `afterLabelContentVAlign` as
required types, changed it to optional.
> chore(ui-options): make new props optional

- packages/emotion/src/withStyle.tsx
The `componentOverrides` block of `InstUISettingsProvider` theme prop was not applying to Button and
other button subtypes. This happened because most of the Buttons don't have styling on their own and
just pass the themeOverrides to the underlying BaseButton component. This worked well with the local
`themeOverride={}` prop, but the `withStyle` decorator never passed them to the component. This
wasn't needed most of the components that use the theme in their style generation, but is needed for
components that just pass the themeOverrides on.
> fix(emotion): make theme componentOverrides apply to Buttons

- packages/__docs__/src/CodePenButton/index.tsx
The issue is that if we send layout="top" to Codepen it ignores every option and just shows an empty codepen. Remove this option and add escape quotes because Codepen docs recommend it.
> INSTUI-3402: Docs: Fix Codepen links

- packages/ui-select/src/Select/__tests__/Select.test.js
- packages/ui-select/src/Select/index.js
- packages/ui-simple-select/src/SimpleSelect/index.js
The new prop controls the maxHeight of the options list and if set, overrides the
`visibleOptionsCount` prop.
Closes: INSTUI-3405
> feat(ui-select): add `optionsMaxHeight` prop to Select

- packages/ui-docs-client/src/CodePenButton/index.js
there was some undocumented change that broke it. Backport of https://github.com/instructure/instructure-ui/pull/896
> refactor(ui-docs-client): fix Codepen button for v6 docs

- .github/workflows/pr-validation.yml
- .github/workflows/vrt.yml
A dependency update does not work on Node 16, and Node 15 is end of life already. https://nodejs.org/en/about/releases/
> Update github actions to Node 16

- packages/ui-responsive/src/Responsive/__tests__/Responsive.test.js
- packages/ui-responsive/src/Responsive/index.js
Closes: INSTUI-3412
Changing the overriding prop error to a warning, since this is how it is intended to work: the props
should override each other when the viewport changes like how CSS media queries work. It is still
worth logging a warning about it, but it is not an error.
> feat(ui-responsive): modify Responsive "props override" error to warning

- packages/ui-portal/package.json
- packages/ui-portal/src/Portal/index.tsx
- packages/ui-portal/tsconfig.build.json
`Portal` tried to access the `document` in its lifecylce methods, which is not suitalbe in SSR, so I
added a check in every lifecycle to bail out if we are in a server environment.
> fix(ui-portal): fix `Portal` not being SSR-able

- packages/ui-code-editor/src/CodeEditor/README.md
- packages/ui-code-editor/src/CodeEditor/codemirror.ts
Closes: INSTUI-3394
our `CodeEditor` component dynamically imported `CodeMirror` language options
which was not
transpiled at all by `babel` which ment that we shipped
code that is not usable in browser
environments out of the box.
this change removes those dynamic `require`s and instead statically
imports them.
this might cause issues for users that uses this component and use jest in order to
test their components
I added notes on how to fix those jest related issues
> fix(ui-code-editor): change dynamically imported `CodeMirror` language modes

- packages/ui-code-editor/tsconfig.build.json
- packages/ui-expandable/tsconfig.build.json
- packages/ui-options/tsconfig.build.json
- packages/ui-pages/tsconfig.build.json
- packages/ui-radio-input/tsconfig.build.json
- packages/ui-react-utils/src/omitProps.ts
- packages/ui-react-utils/src/passthroughProps.ts
- packages/ui-selectable/tsconfig.build.json
- packages/ui-simple-select/tsconfig.build.json
- packages/ui-text-input/tsconfig.build.json
- packages/ui-time-select/tsconfig.build.json
- packages/ui-tooltip/tsconfig.build.json
This PR also fixes the TS reference errors popped up on master.
> chore: fix `deterministicId` being passed to html elements

- packages/ui-options/src/Options/Item/theme.js
Closes: INSTUI-3445
The nested Options used to have a little extra padding by default. It has been modified to have no
extra padding by default, but can still be set via the `nestedPadding` theme variable.
> feat(ui-options): remove nested paddin from option groups

- packages/__docs__/buildScripts/build-docs.ts
- packages/__docs__/src/App/index.tsx
- packages/__docs__/src/Params/index.tsx
- packages/__docs__/src/Properties/index.tsx
- docs was not showing TS type descriptions
- theme info was not showing for subcomponents
- if amethod could have multiple param types these were written without space in one large string
- default value for method params was removing quote characters in a buggy way
> refactor: multiple docs fixes

- scripts/clean.js
- yarn.lock
2 small fixes:
- yarn clean was failing if there is a file in `packages` (I had a .DS_store placed there is OSX, it loves to litter the hard drive with these)
- there was a small change in the yarn.lock after my ReactDOM.render PR, I think its needed so it works properly
> Fix clean if there is a file, fix yarn.lock

- packages/ui-scripts/src/utils/npm.ts
`lerna`s publish command tries to verify whether the user who tries to publish packages to npm actually has valid access to push the package to the npm registry.
We use npm's automation tokens and for some reason those tokens can't be checked against npm's registry endpoints.
This is an old issue, I have no idea why we didn't encounter it before, something with the yarn upgrade might triggered it.
Relevant thread:
https://github.com/lerna/lerna/issues/2788
> chore(ui-scripts): use lerna's `--no-verify-access` flag for publishing snapshots

- packages/ui-simple-select/src/SimpleSelect/index.tsx
According to a bug report, this change was causing performance issues
in SimpleSelect when combined with Formik and InstUI Tray, when
the select had 1000+ items.
Closes: INSTUI-3461
> fix(ui-simple-select): revert refactor on SimpleSelect

- packages/__docs__/src/ComponentTheme/index.tsx
- packages/__docs__/src/Description/index.tsx
- packages/__docs__/src/Document/index.tsx
- packages/__docs__/src/Properties/index.tsx
Closes: INSTUI-2954
Adds info and example for themeOverride (and theme overrides in general) under the component Default
Theme Variable section.
> docs: add theme override info on component pages

- packages/ui-scripts/src/bump.ts
In yarn 3 the `yarn install` in CI environments has the flag `--immutable` automatically turned on, which means it will fail when the yarn.lock file has been modified by the install. The bump script actually modifies every package's version so when you do an install after the bump the lockfile will be updated as well.
This PR changes the bump script to automatically include the lockfile change in the bump commit so it won't fail in CI anymore.
> Update `yarn.lock` file after version bump 

- packages/ui-link/src/Link/__examples__/Link.examples.js
- packages/ui-link/src/Link/__tests__/Link.test.js
- packages/ui-link/src/Link/index.js
Closes: INSTUI-3484
Setting the new `forceButtonRole` prop to false turns off the default logic which forced the aria role `button` on Link when it has an onClick handler and is not a button element.
> feat(ui-link): add `role` and `forceButtonRole ` prop to Link component

- packages/ui-range-input/src/RangeInput/README.md
- packages/ui-range-input/src/RangeInput/__tests__/RangeInput.test.js
- packages/ui-range-input/src/RangeInput/index.js
- packages/ui-range-input/src/RangeInput/styles.css
- packages/ui-range-input/src/RangeInput/theme.js
Closes: INSTUI-3462
Backported change from V8: the previous thumb design is not fully accessible (doesn't have
sufficiant color contrast and focus indication), so it has become deprecated. For this feature to be
non-breaking, we indtroduced a new `thumbVariant` prop on the component. The `deprecated` variant
(and connected theme variables) will be removed in V9, please use the `accessible` variant.
> feat(ui-range-input): add accessible variant for RangeInput handle

- packages/ui-time-select/src/TimeSelect/__tests__/TimeSelect.test.tsx
- packages/ui-time-select/src/TimeSelect/index.tsx
In DateTimeInput it was impossible to set a time value that is not divisible by `step`, e.g. it was
not showing "15:02" when the step value was "15".
To test: Enter a non-step divisible value in DateTimeInput
> INSTUI-3487 fix(ui-date-time-input,ui-time-select): setting non step divisible value works

- packages/ui-date-time-input/src/DateTimeInput/__tests__/DateTimeInput.test.tsx
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
- packages/ui-time-select/src/TimeSelect/__tests__/TimeSelect.test.tsx
- packages/ui-time-select/src/TimeSelect/index.tsx
On a DateTimeInput when changing `value` to a different day/timezone the value is lost, this PR fixes this issue.
The root cause was that `TimeSelect` stores the possible selections in a hashmap where the keys are ISO dates, so if one would change the value from e.g. "2022-04-22T16:30" to "2022-04-01T16:30" the selection would be lots since its a different time value. This change also makes it easier to set dates in `DateTimeInput` which needed to adjust the date value for `TimeSelect` every time setting the value on it.
> INSTUI-3492 Setting the value on a DateTimeInput does not change the time

- packages/theme-registry/src/ThemeRegistry.ts
Closes: INSTUI-3499
the v7 and v8 version used the same key for the theme registry.
this could cause issues when one
part of the application is still on v7 but another part is already on v8
> fix(theme-registry): fix theme registry name collision

- packages/emotion/src/getTheme.ts
- packages/emotion/src/withStyle.tsx
Hey, I was analysing the size of my own bundle when I noticed that the entire lodash package is included.
Before and after images of the change using rollup-plugin-visualizer:
Before             |  After
:-------------------------:|:-------------------------:
The sizes are very misleading in the images, but the effect of the change is noticeable in the bundled vendor chunk:
```
Before
dist/assets/vendor.1f7b611d.js   625.92 KiB / gzip: 180.75 KiB
After
dist/assets/vendor.ed38cdcb.js   574.10 KiB / gzip: 163.07 KiB
```
> refactor(emotion): import lodash functions directly to leverage tree-shaking

- packages/emotion/package.json
- packages/emotion/src/getTheme.ts
- packages/emotion/src/withStyle.tsx
- yarn.lock
Reverts instructure/instructure-ui#1015 because it might end up creating a bigger bundle size for consumers that are not using the same imports (eg `import {debounce} from 'lodash/debounce'`) as we do in the library.
I.e. we might be better off if we did specific imports like import {debounce} from 'lodash/debounce'; but unless we did that everywhere then some stuff would be bringing in the individual files while other stuff would still be bringing in all of lodash, and it’s a net loss.
Discussion:
https://instructure.slack.com/archives/CNRQZ6J8P/p1653310039694569
> revert: "refactor(emotion): import lodash functions directly to leverage tree-shaking"

- packages/ui-babel-preset/lib/index.js
- packages/ui-babel-preset/package.json
- yarn.lock
For some reason after a Babel update 'static' variable modifiers have started to appear in the
compiled es/ and lib/ folders. https://diff.intrinsic.com/@instructure/ui-avatar/8.25.0/8.25.1-snapshot-10 T. This was causing issues with Webpack 4 build. This commit reverts this by adding the `proposal-class-properties` Babel plugin back.
> Refactor(ui-babel-preset): Revert accidental build change

- packages/ui-responsive/src/Responsive/__tests__/Responsive.test.tsx
- packages/ui-responsive/src/Responsive/index.tsx
- packages/ui-responsive/src/Responsive/props.ts
Closes: INSTUI-3540
The Responsive component is rendered as a `<div>`, so it has `display="block"` by default, but can
be changed with the new `display` prop.
> feat(ui-responsive): add `display` prop to Responsive

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-tabs/src/Tabs/Panel/styles.ts
- packages/ui-tabs/src/Tabs/Panel/theme.ts
Closes: INSTUI-3553
This theme variable allows the default `overflowY` to be set to `visible` on Tabs.Panel. It is
useful, when there is a 100% width interactive element (e.g. Button) in the panel, in which case the
focus ring would be cropped. Note, that this only works when the panel is not scrollable vertically.
> feat(ui-tabs): expose `defaultOverflowY` theme variable on Tabs.Panel

- packages/ui-text-input/src/TextInput/styles.ts
Closes: INSTUI-3569
The before/after icons don’t receive any color in TextInput, so they have “color: inherit“ by
default, and that ends up being black. All colors should come from theme variables.
It is fixed in TextInput, but it affects other components based on it: Select, SimpleSelect, DateInput,
DateTimeInput, TimeSelect, ColorMixer.
> fix(ui-date-input,ui-select,ui-text-input): before/after elements should inherit input color

- packages/ui-drilldown/src/Drilldown/README.md
The old example didn't show any visual feedback for the options actually being selected. Changed it
to a selectable group.
> docs(ui-drilldown): better example for `shouldHideOnSelect`

- packages/ui-drilldown/src/Drilldown/index.tsx
- packages/ui-tabs/src/Tabs/__tests__/Tabs.test.tsx
Closes: INSTUI-3567
Note: when testing, a lot of tests will break on React 16 (`focusIn`, `focusOut` and `calledWithMatch` is not working), but fixing those would break the React 17 tests.
> chore(ui-drilldown,ui-tabs): modify lines that throw errors in React 16

- packages/ui-date-input/package.json
- packages/ui-date-input/src/DateInput/__examples__/DateInput.examples.js
- packages/ui-date-input/src/DateInput/index.js
- packages/ui-date-input/src/DateInput/styles.css
Closes: INSTUI-3574
Adding the `display` prop allows the currently hard-coded `display: inline-block` to be overridden
on the root element in order to make it fill its container element.
> fix(ui-date-input): add `display` prop to DateInput

- packages/__docs__/src/Hero/index.tsx
- packages/__docs__/src/Preview/index.tsx
- packages/__docs__/src/index.html
- packages/__docs__/src/index.js
Update syntax to the Ract 18 one.
Also fix "The resource
https://instui-docs.s3.us-east-2.amazonaws.com/hero2.jpg was preloaded using link preload but not
used within a few seconds from the window's load event." warnings
> INSTUI-3575 : fix ReactDOM.render warnings in docs

- packages/shared-types/src/CommonTypes.ts
- packages/ui-a11y-utils/src/ScreenReaderFocusRegion.ts
- packages/ui-dialog/src/Dialog/props.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/props.ts
- packages/ui-modal/src/Modal/props.ts
- packages/ui-popover/src/Popover/props.ts
- packages/ui-tray/src/Tray/props.ts
`liveRegion` can be a function that returns an array of DOM elements. Also its propType was
erroneously allowing React elements when it should only allow native DOM elements triggering false
prop validation errors.
> INSTUI-3576 fix TS type and propType for liveRegion prop

- .github/workflows/codeql-analysis.yml
- .github/workflows/manual-deploy-docs.yml
- .github/workflows/manual-legacy-release-to-npm.yml
- .github/workflows/pr-validation.yml
- .github/workflows/release.yml
- .github/workflows/vrt.yml
Also updated `actions/checkout` from v2 to v3, and `actions/setup-node` from v2 to v3 and added global package caching according to https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data.
> chore: update used action versions

- dangerfile.ts
- packages/ui-code-editor/.eslintignore
- packages/ui-code-editor/package.json
- packages/ui-code-editor/src/CodeEditor/index.tsx
- packages/ui-code-editor/src/CodeEditor/props.ts
- packages/ui-code-editor/src/CodeEditor/styles.ts
- packages/ui-code-editor/src/CodeMirrorWrapper/index.node.tsx
- packages/ui-code-editor/src/CodeMirrorWrapper/index.tsx
- yarn.lock
This PR fixes the `global is undefined` issue when using the `@instructure/ui` meta package with `esbuild/vite`.
The issue was that in the currently released version of `react-codemirror2` (7.2.1) there was a [bug](https://github.com/scniro/react-codemirror2/issues/259) which came up when the user does not use webpack for bundling.
This issue has been fixed and merged since to the source code of `react-codemirror2`, but the maintainers said that they won't release it, because they are not using the project anymore. ([link](https://github.com/scniro/react-codemirror2/pull/260#issuecomment-1023202972))
I cloned the code down, and stripped the parts that we didn't use and moved the wrappers code in the `ui-code-editor` package.
The other issue I faced and fixed in this PR is the dynamic …
> Fix CodeEditor

- dangerfile.ts
The last change in the dangerfile caused the action ending with `master` being checked out, and the docs build action after was working from the master resources. Added a fix the switch back to the feature branch.
> chore: fix dangerfile to render the correct docs

- dangerfile.ts
- packages/emotion/package.json
- packages/emotion/src/getTheme.ts
- packages/ui-babel-preset/lib/index.js
- packages/ui-babel-preset/package.json
- packages/ui-source-code-editor/package.json
- packages/ui-source-code-editor/src/SourceCodeEditor/index.tsx
- yarn.lock
This PR removes our dependency on `lodash` for consumer facing packages (emotion, ui-source-code-editor), this could be achieved by using our internal utility functions instead of relying on `lodash`. 
I created 2 applications with the same code, but with different @instrucutre/ui dependencies:
- one with `lodash` still used internally:
- another one with this PR applied:
> Remove `lodash` dependency from component packages

- packages/ui-drilldown/src/Drilldown/DrilldownGroup/__tests__/DrilldownGroup.test.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownOption/__tests__/DrilldownOption.test.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownOption/props.ts
- packages/ui-drilldown/src/Drilldown/__tests__/Drilldown.test.tsx
- packages/ui-drilldown/src/Drilldown/index.tsx
- packages/ui-drilldown/src/Drilldown/props.ts
- packages/ui-tray/src/Tray/__tests__/Tray.test.tsx
Closes: INSTUI-3685
users now are allowed to set a newly added `selected` property on `Drilldown.Option` which allows them to control the
selection logic from outside of the component fix `selectableType=single`allowing de-selecting options
TEST PLAN:
run the test cases, verify that
[this](https://codesandbox.io/s/flamboyant-glitter-2dt3bg?file=/index.js) use case is working as expected
> feat(ui-drilldown): allow controlled functionality when selecting options

- packages/ui-top-nav-bar/src/TopNavBar/README.md
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/index.tsx
The menu mount element was covering the page content. Set the height to 0 when menu is not open.
> fix(ui-top-nav-bar): fix TopNavBar `smallViewport mode` example

- packages/ui-modal/package.json
- packages/ui-modal/src/Modal/ModalBody/index.tsx
- packages/ui-modal/src/Modal/ModalBody/props.ts
- packages/ui-modal/tsconfig.build.json
- yarn.lock
Screenreader was skipping modal content in Chrome because we made a View focusable. This fix makes the View unfocusable
> INSTUI-3701 fix(ui-modal): fix screenreader focus order in Chrome

- packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/props.ts
We had to add available Link prop types to Breadcrumb.Link, since we are passing them through to the underlying component.
> fix(ui-breadcrumb): fix prop typing for `Breadcrumb.Link`

- packages/ui-time-select/src/TimeSelect/index.tsx
- packages/ui-time-select/src/TimeSelect/props.ts
For components like `Select` and `Popover` custom `mountNode` property can be passed. `TimeSelect` does not allow to set it, despite the fact that it is using those components under the hood.
This is quite necessary for one of scenarios in our Impact app.
> feat(ui-time-select): mountNode property

- packages/ui-i18n/src/DateTime.ts
- packages/ui-time-select/package.json
- packages/ui-time-select/src/TimeSelect/README.md
- packages/ui-time-select/src/TimeSelect/__tests__/TimeSelect.test.tsx
- packages/ui-time-select/src/TimeSelect/index.tsx
- packages/ui-time-select/src/TimeSelect/props.ts
- packages/ui-time-select/tsconfig.build.json
- yarn.lock
When setting `allowNonStepInput` to `true` one can enter any valid time value. It needs to be typed exactly (except for upper/lowercase)
> feat(ui-time-select): allow non-step input value with new prop

- packages/ui-dom-utils/src/findFocusable.ts
findFocusable doesn’t match elements with `contenteditable=true`. In my case, it causes it to skip the next element and goes straight to the close button. Somehow going backward works fine 🤷 
Before:
https://user-images.githubusercontent.com/1939060/223365814-ea9ce84f-005a-4e28-a858-0130aababc95.mov
After:
https://user-images.githubusercontent.com/1939060/223365875-43c15442-5dcf-46e4-9974-2d7443c93af2.mov
> Inst UI 3740/add contenteditable to focusableSelector

- packages/ui-text-input/src/TextInput/index.tsx
Closes: INSTUI-3748
This is a workaround for an edge-case, when the TextInput's parent is hidden on load, so the element is not visible either. In this case the computed width is going to be 'auto', so we assume it has width so that the padding won't be removed. This fix affects all TextInput based components, e.g.: Select, SimpleSelect, DateSelect, etc.
> fix(ui-text-input): fix padding calculation for before/after element

- packages/ui-options/src/Options/index.tsx
- packages/ui-select/src/Select/index.tsx
This PR aims to fix the rendering performance of `Select` and `SimpleSelect` in case of large amount of `Select.Option`s are passed to them.
This "fix" is more of a temporary solution since it only addresses the problem in `Select`.
The main issue is that component that use the `<Option>` sub-component are prone to this performance problem because they often just expose a wrapper Option component (like `Select.Option`, that is essentially a facade, just used for proptype checking) and then internally map from this wrapper to the `Option` component, and because of this re-mapping it is hard to use common optimization techniques to get better performance.
This PR add a new memoed layer between to this mapping of `Select.Option` => `Options.Item`. The main problem was that in case the …
> perf(ui-select): improve perf for large amount of items

- packages/ui-date-time-input/src/DateTimeInput/README.md
- packages/ui-date-time-input/src/DateTimeInput/__tests__/DateTimeInput.test.tsx
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
- packages/ui-date-time-input/src/DateTimeInput/props.ts
note that there is a slight visual change, now if you move with the arrows the input text wont change.
Also now triggering the invalid date message is more consistent, it triggers on empty inputs if `isRequired` is true and does not if its false.
> INSTUI-3756 fix(ui-date-time-input): dateTimeInput does not trigger invalidDateTimeMessage on blur

- packages/ui-progress/src/ProgressBar/README.md
- packages/ui-progress/src/ProgressBar/__examples__/ProgressBar.examples.tsx
- packages/ui-progress/src/ProgressBar/index.tsx
- packages/ui-progress/src/ProgressBar/props.ts
- packages/ui-progress/src/ProgressBar/styles.ts
Closes: INSTUI-3751
This change adds the `shouldAnimate` prop to ProgressBar, which makes animates the change between values. To implement this feature, the complement had to be be refactored to "hide" the HTML `<progress>` element in the DOM and render a custom progress bar in front of it. There are two reasons for this: it was impossible to style the HTML progress to animate in Firefox as well, but we had to keep it for accessibility purposes.
> feat(ui-progress): add `shouldAnimate` prop to ProgressBar

- packages/ui-date-time-input/src/DateTimeInput/README.md
- packages/ui-date-time-input/src/DateTimeInput/__examples__/DateTimeInput.examples.ts
- packages/ui-date-time-input/src/DateTimeInput/__tests__/DateTimeInput.test.tsx
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
- packages/ui-date-time-input/src/DateTimeInput/props.ts
Closes: INSTUI-3766
This exposes the `allowNonStepInput` prop from the underlying `TimeSelect`, it should behave the same way
> DateTimeInput: Allow the user to enter non-step divisible time values

- packages/ui-date-time-input/src/DateTimeInput/__tests__/DateTimeInput.test.tsx
- packages/ui-time-select/src/TimeSelect/README.md
- packages/ui-time-select/src/TimeSelect/__tests__/TimeSelect.test.tsx
- packages/ui-time-select/src/TimeSelect/index.tsx
- packages/ui-time-select/src/TimeSelect/props.ts
The autocomplete behaviour is now different if `allowNonStepInput` is `true`:   
- if the user types in 1 or 2 letters it offers the step inputs as choices. 
- if more it will show all the minutes
Now one can enter a value with the following methods:   
1. User clicks/presses enter on an option in the dropdown and focuses away
2. User enters a valid time manually and focuses away
To test:
test all the examples of `TimeSelect` and `DateTimeInput`
> INSTUI-3772 Refactor(ui-time-select): rewrite logic if allowNonStepInput is true

- packages/ui-a11y-utils/src/KeyboardFocusRegion.ts
- packages/ui-dialog/src/Dialog/index.tsx
Fix for this issue: https://github.com/instructure/instructure-ui/issues/1181
* Remove `React.StrictMode` tag from `packages/__docs__/src/index.js`
* Replace content of `packages/__docs__/src/App/index.tsx` with:
```jsx
import { Button } from '@instructure/ui-buttons'
import { Menu } from '@instructure/ui-menu'
import React from 'react'
export const App: React.FC = () => {
const triggerButton = <Button>Trigger</Button>
return (
<>
<p style={{ fontSize: '150px' }}>
Somthing big to require scrolling for button
</p>
{new Array(100).fill(null).map((_, index) => (
<Menu key={index} trigger={triggerButton}>
{new Array(12).fill(null).map((_, index) => (
<Menu.Item key={index}>{index}</Menu.Item>
))}
</Menu>
))}
</>
)
}
```
* Trigger any button a few times, eventually it should scroll to the top …
> bug(ui-dialog,ui-a11y-utils): fix focusing not yet positioned elements

- packages/ui-scripts/lib/commands/publish.js
- packages/ui-scripts/lib/utils/git.js
We cannot use temp credentials set for just the `commit` command because the actual commit is done by `git-cz` and it doesnt have an option to set username/email. Instead it sets these to the CI user if nothing is found
> INSTUI-3795 chore(ui-scripts): fix accidentally committing with CI username and email

- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-color-picker/src/ColorPicker/__tests__/ColorPicker.test.tsx
- packages/ui-dialog/src/Dialog/__tests__/Dialog.test.tsx
- packages/ui-menu/src/Menu/__tests__/Menu.test.tsx
- packages/ui-modal/src/Modal/__tests__/Modal.test.tsx
- packages/ui-popover/src/Popover/__tests__/Popover.test.tsx
should fix the bug introduced with [this pr](#1194 )
Closes: INSTUI-3790
test plan 1:
- open a modal
- click on modal and drag the mouse outside and release
- the modal shouldn't close
test plan 2:
- open drilldown in popover
- click on the button again
- the popover should close
> fix(ui-a11y-utils): Drilldown keeps reopening when clicking on the trigger

- packages/ui-a11y-utils/src/FocusRegion.ts
Closes: INSTUI-3804
probably should wait until #1228 is merged
test plan:
- use firefox (the bug was not present in chrome)
- add an  `<input type="file"/>` inside a `Tray`/`Dialog`/`Modal`/etc component
- open the dialog then the file browser
- press escape when the file browser is open
- the dialog shouldn't close
> A11y: Pressing escape on an open media picker in a tray will close the tray too

- package.json
INSTUI-3830
from the [official husky docs](https://typicode.github.io/husky/getting-started.html#yarn-2)
- make a fresh clone of this repo
- checkout this PR
- run `yarn install` and `yarn bootstrap`
- create some changes
- commit the changes -> a husky hook should run commitizen/commitlint
> chore: fix yarn2 not running prepare script for hooks

- packages/ui-color-picker/src/ColorIndicator/styles.ts
INSTUI-3828
`babel-plugin-transform-imports` has a bug which sometimes breaks the commonjs build. This is a workaround for that.
- build the project (`yarn bootstrap`)
- modify the `ColorPicker` example to use the commonjs build:
- in `ui-color-picker/src/index.ts` modify the `ColorPicker` import to `export { ColorPicker } from '../lib/ColorPicker'`
- check the docs example if it's working
> fix(ui-color-picker): fix broken commonjs import for color-picker

- packages/emotion/src/styleUtils/ThemeablePropValues.ts
- packages/shared-types/src/BaseTheme.ts
- packages/ui-theme-tokens/src/canvas/spacing.ts
- packages/ui-theme-tokens/src/instructure/spacing.ts
Closes: INSTUI-3829
IMSG (InstUI Mini Style Guide) adds a new unit for spacing called: mediumSmall. 
- Canvas/High contrast: 16px
- Instructure: 20px
Test plan:
1. run the documentation app
2. under Themes menu check if the above spacing options are present for every theme
3. pick a component and change its margin value to mediumSmall
4. check if the component's margin changed accordingly (16px for Canvas/High Contrast themes, 20px for Instucture)
> feat(emotion,shared-types,ui-theme-tokens): add mediumSmall spacing to themes

- packages/__docs__/src/App/index.tsx
- packages/__docs__/src/App/props.ts
- packages/__docs__/src/Methods/index.tsx
- packages/__docs__/src/Preview/props.ts
- packages/__docs__/src/Properties/props.ts
- packages/__docs__/src/Returns/index.tsx
- packages/__docs__/src/Returns/props.ts
- packages/__docs__/tsconfig.build.json
- packages/__docs__/webpack.config.js
- packages/command-utils/lib/index.js
- packages/command-utils/package.json
- packages/ui-scripts/lib/test/lint.js
We treated it as something that returns a Promise when it does not. This fixes it by wrapping it in a Promise
TEST PLAN:
Change some command temporarly (e.g. ui-scripts tag) so it uses RunCommandAsync and output its return value, e.g.
```
try {
const res = await runCommandAsync("ls", [], {}, {stdio: 'pipe', stderr: 'pipe'})
console.log(res)
} catch (err) {
console.log("RESULT", err)
}
```
> refactor(command-utils): fix runCommandAsync

- packages/ui-dom-utils/src/elementMatches.ts
- packages/ui-dom-utils/src/findDOMNode.ts
- packages/ui-dom-utils/src/findFocusable.ts
- packages/ui-dom-utils/src/getComputedStyle.ts
the positioned function was throwing sometimes a nullpointer exception in Canvas tests. Also some minor typing fixes.
This PR supersedes this one: https://github.com/instructure/instructure-ui/pull/1265/files
TEST PLAN:
just check the code
> fix(ui-dom-utils): fix findFocusable throwing nullpointer exceptions

- packages/ui-responsive/src/Responsive/README.md
- packages/ui-responsive/src/Responsive/__tests__/Responsive.test.tsx
- packages/ui-responsive/src/jsonToMediaQuery.ts
Add support for multiple breakpoints in media queries.
**Test plan:**
1. Go to the Responsive component page of the InstUI docs app
2. Add extra breakpoints (`minWidth`, `maxWidth`) into the query part of the Responsive component
3. Check if errors are popping up & newly added breakpoints work as intended to CSS specifications & the appropriate part of the HTML is getting rendered
> Inst UI 3832 responsive breakpoints

- packages/__docs__/src/Description/index.tsx
Closes: INSTUI-3838
TEST PLAN:
Open up the docs app. Change something in the playground. Resize the screen. check if the playground reset or not
> docs: fix playground reset on resize

- packages/ui-responsive/src/addElementQueryMatchListener.ts
Closes: INSTUI-3785
If dimensions are fractions, integer breakpoints are not going to match with them. Rounding width and height values solves this issue.
1. Set up breakpoints in a Responsive component (or use the example code added in a followup)
2. Resize width and check if props object is not empty
> fix(ui-responsive): round dimensions for query matcher

- docs/guides/release.md
One should check the CHANGELOG.md instead of the README.md as part of the release process. Documentation got corrected.
> docs: add checking the CHANGELOG as part of the release process

- .github/workflows/release.yml
[previously](https://github.com/instructure/instructure-ui/blob/1800e2886180119af392f1d0f43e101a088b0ff7/.github/workflows/release.yml#L95) with yarn we didn't use a lock file for regression test, this change copies that behaviour
test plan: you can't. it only runs on master
> chore: dont use package-lock for regression test in ci

- packages/ui-tree-browser/src/TreeBrowser/index.tsx
In the current implementation, when the `TreeBrowser` component is placed as the last focusable element within a modal, attempting to navigate forward using the Tab button disrupts the tab navigation cycle.
This happens because `stopPropagation` is called on all keydown events by default in `handleKeyDown`.
https://github.com/instructure/instructure-ui/assets/15729147/7c7db4ca-4c3c-48fd-b537-23a3219c2e83
https://github.com/instructure/instructure-ui/assets/15729147/0fb3af21-b83b-4b5b-8927-d1407608d473
> fix(ui-tree-browser): improve TreeBrowser keyboard only navigation

- packages/ui-color-picker/src/ColorPicker/index.tsx
- packages/ui-color-picker/src/ColorPicker/props.ts
- packages/ui-color-picker/src/ColorPicker/styles.ts
Closes: INSTUI-3867
Adding a padding to color picker button calculated by the text input children element's label height and margin.
This should be replaced in INSTUI v9 with a better solution.
**Test plan**
Add 
```      
renderMessages={() => [{ type: "error", text: "Long error message" }]}
```
to a Color Picker as an attribute and check if the input field and the botton stays aligned.
> fix(ui-color-picker): add a padding to colorpicker button

- package-lock.json
- packages/ui-number-input/package.json
- packages/ui-number-input/src/NumberInput/__new-tests__/NumberInput.test.tsx
- packages/ui-number-input/tsconfig.build.json
- packages/ui-scripts/lib/test/generateA11yTests.tsx
- packages/ui-scripts/lib/test/generateComponentExamples.tsx
- packages/ui-scripts/lib/test/generatePropCombinations.ts
INSTUI-3875
- pick a random component that uses `generateA11yTests` in its tests
- comment out everything else in that test file (besides the `generateA11yTests` part) and run that test with `npm run test -- --path packages/ui-component-name` (with the actual path to that component)
- note down how many tests were run (should be around 1-4)
- next to that components `__tests__` folder create a `__new-tests__` folder
- create a test file named `ComponentName.test.tsx` (replace `ComponentName` with the actual name of the component)
- add the following code to that test:
```ts
import { render } from '@testing-library/react'
import { runAxeCheck } from '@instructure/ui-axe-check'
import { ComponentName } from '../index'
import ComponentNameExamples from …
```
> chore(ui-scripts,ui-test-utils): move test utils

- package-lock.json
- packages/ui-spinner/package.json
- packages/ui-spinner/src/Spinner/README.md
- packages/ui-spinner/src/Spinner/__new-tests__/Spinner.test.tsx
- packages/ui-spinner/src/Spinner/index.tsx
- packages/ui-spinner/src/Spinner/props.ts
> feat(ui-spinner): add delay prop and functionality to the Spinner

- packages/ui-react-utils/src/DeterministicIdContext/DeterministicIdContext.ts
- packages/ui-react-utils/src/DeterministicIdContext/DeterministicIdContextProvider.tsx
- packages/ui-react-utils/src/__tests__/DeterministicIdContext.test.tsx
> fix(ui-react-utils): fix ID counter wrong when not in context

- packages/ui-date-time-input/src/DateTimeInput/README.md
- packages/ui-date-time-input/src/DateTimeInput/__tests__/DateTimeInput.test.tsx
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
TEST PLAN:
make a DateTimeInput with `isRequired = false`. When you clear the date value the time value and the message should clear.
When isRequired = true it should display an invalid date message.
> INSTUI-3877 fix(ui-date-time-input): clear TimeSelect value when DateInput value is cleared

- packages/instui-config/codemod-configs/v7/propNames.config.json
TEST PLAN:
Run the v7 codemods for a file that contains BreadcrumbLink and FlexItem
> fix(instui-config): v7 codemods were not run for BreadcrumbLink and FlexItem

- package-lock.json
- packages/ui-tabs/package.json
- packages/ui-tabs/src/Tabs/Panel/index.tsx
- packages/ui-tabs/src/Tabs/Panel/props.ts
- packages/ui-tabs/src/Tabs/README.md
- packages/ui-tabs/src/Tabs/__new-tests__/Tabs.test.tsx
- packages/ui-tabs/src/Tabs/index.tsx
Closes: INSTUI-3876
Add support for multiple tabs->one tab panel. This makes using React Router easier with less boilerplate code.
Test plan: check if the new example in the Tabs page works fine.
> feat(ui-tabs): add active property to tabs

- package-lock.json
- packages/emotion/package.json
- packages/emotion/src/__tests__/withStyle.test.tsx
- packages/emotion/src/withStyle.tsx
- packages/ui-i18n/package.json
- packages/ui-i18n/src/__tests__/bidirectional.test.tsx
- packages/ui-i18n/src/bidirectional.tsx
- packages/ui-react-utils/src/DeterministicIdContext/withDeterministicId.tsx
- packages/ui-react-utils/src/__tests__/DeterministicIdContext.test.tsx
> support ReactTestUtils in decorators that use forwardRef

- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/__tests__/TopNavBarItem.test.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/props.ts
> feat(ui-top-nav-bar): add as property to TopNavBarItem

- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-dialog/src/Dialog/__new-tests__/Dialog.test.tsx
- packages/ui-menu/src/Menu/__tests__/Menu.test.tsx
- packages/ui-modal/src/Modal/__tests__/Modal.test.tsx
- packages/ui-popover/src/Popover/__tests__/Popover.test.tsx
INSTUI-3907
explanation: for `shouldCloseOnDocumentClick` we used to have two mousedown listeners: one for capturing the document click (store the target) and one for handling it (close document if target is outside the context, e.g. modal). the latter were converted to a click listener to fix the order of execution but that introduced this bug because the click listener can also capture events like pressing space on a checkbox (for a11y reasons). the solution is to use a mouseup listener instead of a click listener which isn't triggered by the spacebar
https://stackoverflow.com/questions/27878940/spacebar-triggering-click-event-on-checkbox
- open the docs app at the modal example
- use this code:
```jsx
<div style={{ padding: '0 0 11rem 0', margin: '0 auto' }}>
<Button …
```
> fix(ui-a11y-utils): handleDocumentClick should only capture mouse events

- packages/ui-tray/src/Tray/index.tsx
- packages/ui-tray/src/Tray/props.ts
INSTUI-3923
test plan
- open docs app at the `Tray` component and paste the following code:
```jsx
function TrayContent() {
React.useEffect(() => {
console.log("TrayContent is loaded");
return () => console.log("Tray content is unloaded");
}, []);
return <>This is a test.</>;
}
const FPO = lorem.paragraph()
class Example extends React.Component {
constructor (props) {
super(props)
this.state = {
open: false
}
}
hideTray = () => {
this.setState({
open: false
})
}
renderCloseButton () {
return (
<Flex>
<Flex.Item shouldGrow shouldShrink>
<Heading>Hello</Heading>
</Flex.Item>
<Flex.Item>
<CloseButton
placement="end"
offset="small"
screenReaderLabel="Close"
onClick={this.hideTray}
/>
</Flex.Item>
</Flex>
)
}
render () {
return (
<div style={{ padding: '0 0 16rem 0', margin: '0 auto' }}> …
```
> fix(ui-tray): fix Tray component unmounting twice when closed

- packages/ui-drilldown/src/Drilldown/index.tsx
INSTUI-3924
test plan:
- in the TopNavBar Drilldown examples change a drilldown item's href to some url (e.g. `https://google.com`)
- cmd+click on that item -> it should open on a new tab as expected
> fix(ui-drilldown): fix cmd+click not working on drilldown items

- packages/ui-a11y-utils/src/FocusRegion.ts
INSTUI-3925
test plan:
- go to the Popover components page
- go to the "Controllerd Popover" section
- click on the "Sign in" button to open the popover
- click on it again -> the popover should close
> fix(ui-a11y-utils): fix popover reopen when clicking the trigger

- packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/__new-tests__/BreadcrumbLink.test.tsx
- packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/index.tsx
- packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/props.ts
- packages/ui-link/src/Link/__tests__/Link.test.tsx
- packages/ui-link/src/Link/index.tsx
- packages/ui-link/src/Link/props.ts
> feat(ui-breadcrumb,ui-link): add onMouseEnter prop

- packages/ui-modal/src/Modal/index.tsx
- packages/ui-modal/src/Modal/props.ts
INSTUI-3929
test plan:
- use the following modal example:
```tsx
const fpo = lorem.paragraphs(5)
class Example extends React.Component {
constructor (props) {
super(props)
this.state = {
open: false,
open2: false,
}
}
handleButtonClick = () => {
this.setState(function (state) {
return { open: !state.open }
})
};
handleButton2Click = (event) => {
this.setState(function (state) {
return { open2: !state.open2 }
})
console.log('kettes bezar')
};
renderCloseButton () {
return (
<CloseButton
placement="end"
offset="small"
onClick={this.handleButtonClick}
screenReaderLabel="Close"
/>
)
}
renderCloseButton2 () {
return (
<CloseButton
placement="end"
offset="small"
onClick={this.handleButton2Click}
screenReaderLabel="Close"
/>
)
}
render () {
return (
<div style={{ padding: '0 0 11rem 0', margin: …
```
> fix(ui-modal): fix second modal closing the first one if two of them are open

- packages/ui-tray/src/Tray/index.tsx
> fix(ui-tray): fix `shouldCloseOnDocumentClick` not working when a second Tray is opened

- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-popover/src/Popover/index.tsx
- packages/ui-tooltip/src/Tooltip/index.tsx
INSTUI-3938
this PR fixes several issues related to the `shouldCloseOnDocumentClick` option in focus region. these are:
1. changing the content of a dialog (modal/popover/etc) dismisses it which can be observed in the [Drilldown Menu pattern](https://instructure.design/#DrilldownMenu) or in this [example](https://codesandbox.io/s/laughing-euclid-5gzdq3?file=/src/App.js)
2. if a dialog has an input field and you highlight the text with mouse and you release the mouse button when the cursor is outside the dialog then the dialog closes (which was fixed previously but reoccured recently)
3. tooltips closed on click as they were having the `shouldCloseOnDocumentClick` option set to true
- go to the [Drilldown Menu example](https://1371--preview-instui.netlify.app/#DrilldownMenu) and test the …
> fix focus region issues

- packages/ui-a11y-utils/src/FocusRegion.ts
this was fixed in #1332 and reappeared in #1371
this should be a more sufficient solution
- open the docs app at the modal example
- use this code:
```jsx
<div style={{ padding: '0 0 11rem 0', margin: '0 auto' }}>
<Button onClick={this.handleButtonClick}>
{this.state.open ? 'Close' : 'Open'} the Modal
</Button>
<Modal
as="form"
open={this.state.open}
onDismiss={() => { this.setState({ open: false }) }}
onSubmit={this.handleFormSubmit}
size="auto"
label="Modal Dialog: Hello World"
shouldCloseOnDocumentClick
>
<Modal.Header>
{this.renderCloseButton()}
<Heading>Hello World</Heading>
</Modal.Header>
<Modal.Body>
<TextInput renderLabel="Example" placeholder="if you hit enter here, it should submit the form" />
<Text lineHeight="double">{fpo}</Text>
<Checkbox label={lorem.sentence()} …
```
> fix(ui-a11y-utils): fix regression in focus region

- packages/ui-selectable/src/Selectable/index.tsx
Closes: INSTUI-3945
**Test plan**: check if you can select the label of a Select component (for copying it elsewhere)
> fix(ui-selectable): fix label can't be selected issue

- docs/patterns/Search.md
Closes: INSTUI-3940
**Test**: check if TextInputs break in mobile view on Patterns\Search page.
> docs: fix textinputs breaking on search page

- packages/ui-a11y-utils/src/FocusRegion.ts
INSTUI-3956
test:
- open the docs on safari or firefox
- open a modal and try to dismiss it by clicking on the document
- the modal should close as expected
> fix(ui-a11y-utils): use event.detail instead of event.pointerType for safari/firefox

- packages/ui-truncate-text/src/TruncateText/index.tsx
INSTUI-3952
previously in `componentDidMount` we checked whether the component size changed from the original to update the truncation but in certain cases that didn't work e.g. if the component got resized to its original width
> fix(ui-truncate-text): resizing TruncateText to its original width doesn't work

- packages/ui-date-time-input/src/DateTimeInput/__tests__/DateTimeInput.test.tsx
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
- packages/ui-date-time-input/src/DateTimeInput/props.ts
This new prop enables to hide the date/time/error messages beneath the input fields. Default is true, the messages are shown. It does not hide user-supplied messages in the 'messages' field.
TEST PLAN:
set `showMessages` to false and check that no datetime/error messages are shown.
> INSTUI-3954 feat(ui-date-time-input): add showMessages prop

- packages/__docs__/src/Playground/index.tsx
- packages/__docs__/src/Preview/index.tsx
- packages/__docs__/src/Preview/props.ts
cleaned up and fixed the error handling for the`<Preview/>` component in the docs page
- go to the docs page and open a code example
- modify the example to get a ReferenceError (e.g. add a new prop `some={example}`)
- the preview should display the error
- modify the code to get rid of the error
- the error should disappear and the component preview should be displayed again
> fix Preview errors in docs page

- packages/ui-drilldown/src/Drilldown/DrilldownOption/index.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownOption/props.ts
- packages/ui-drilldown/src/Drilldown/props.ts
- packages/ui-top-nav-bar/src/TopNavBar/README.md
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/props.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/__new-tests__/TopNavBarSmallViewportLayout.test.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/utils/mapItemsForDrilldown.tsx
Closes: INSTUI-3911
This property only works in smallViewPort mode.
**Test:** to make testing easier, you can use the code from the test case, which I added. Put it into a playground and observe, what happens with the menu with different value's of the `shouldCloseOnClick` prop.
**Expected behaviors for values:**
- `always`: the `Tray` should always close, when an option with `always` is selected
- `never`: the `Tray` should never close, when an option with `never` is selected
- `auto`: the `Tray` should close, if `href` property is added to the option, otherwise it should not!
> feat(ui-drilldown,ui-top-nav-bar): add shouldCloseOnClick

- docs/contributor-docs/storybook-examples.md
- docs/guides/storybook-examples.md
> docs: add storybook example guide to guides

- packages/__docs__/buildScripts/build-docs.mts
Closes: INSTUI-3984
Test plan:
Check if MaxLengthInputPrompt is still at the root of the docs navigation
> docs: remove internal tool's doc (MaxLengthInputPrompt) page from docs

- package-lock.json
- packages/ui-source-code-editor/package.json
- packages/ui-source-code-editor/src/SourceCodeEditor/README.md
- packages/ui-source-code-editor/src/SourceCodeEditor/SearchPanel.tsx
- packages/ui-source-code-editor/src/SourceCodeEditor/index.tsx
- packages/ui-source-code-editor/src/SourceCodeEditor/props.ts
- packages/ui-source-code-editor/tsconfig.build.json
INSTUI-3961
test plan:
- go to the search example at the SourceCodeEditor in docs
- hit cmd+f -> the search panel should open
- start typing -> matches should be highlighted
- hit enter on a search -> it should jump to the next occurrence of the word
- try the up and down arrows -> it should jump to the prev/next occurrence of the word
- hit escape -> the search panel should close
- check documentation for the search panel
- try the `searchConfig` prop
> feat(ui-source-code-editor): add custom search panel

- package-lock.json
- packages/ui-source-code-editor/package.json
- packages/ui-source-code-editor/src/SourceCodeEditor/SearchPanel.tsx
fixes issue in last release where `SourceCodeEditor` can only be used in react 18 due to `react-dom` api change
> Fix: only import react-dom/client if exists

- package-lock.json
- packages/ui-date-time-input/src/DateTimeInput/__new-tests__/DateTimeInput.test.tsx
- packages/ui-prop-types/package.json
- packages/ui-prop-types/src/__new-tests__/children.test.tsx
- packages/ui-prop-types/src/__new-tests__/childrenOrValue.test.tsx
- packages/ui-prop-types/src/__new-tests__/controllable.test.tsx
- packages/ui-prop-types/src/__new-tests__/makeRequirable.test.tsx
- packages/ui-prop-types/src/__new-tests__/xor.test.tsx
- packages/ui-prop-types/tsconfig.build.json
> test(ui-prop-types): migrate old Prop-types tests

- packages/ui-select/src/Select/README.md
INSTUI-3994
#1334 
test plan:
- go to the multiselect example in docs (`/#Select/#Highlighting%20and%20selecting%20options`)
- turn on voiceover
- add and remove an option
- `<option name> removed` should be read by the screen reader
> docs(ui-select): add example for voiceover announcement for multiselect option removal

- packages/ui-dialog/src/Dialog/index.tsx
INSTUI-4023
test plan:
- use the following `Menu` example:
```jsx
class Example extends React.Component {
constructor (props) {
super(props)
this.state = {
singleSelection: ['itemOne'],
multipleSelection: ['optionOne', 'optionThree']
}
}
handleSingleSelect = (e, newSelected) => {
alert(newSelected)
this.setState({
singleSelection: newSelected
})
};
handleNoSelect = (e, newSelected) => {
alert('no select')
e.preventDefault()
e.stopPropagation()
};
render () {
return (
<View padding="medium" textAlign="center">
<Menu
placement="bottom"
trigger={
<Button>Menu</Button>
}
onSelect={this.handleSingleSelect}
mountNode={() => document.getElementById('main')}
>
<Menu.Item value="mastery">Learning Mastery</Menu.Item>
<Menu.Item href="https://instructure.github.io/instructure-ui/">Default (Grid …
```
> fix(ui-dialog): menu closes when clicking on submenu

- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/props.ts
- packages/ui-top-nav-bar/src/TopNavBar/utils/mapItemsForDrilldown.tsx
INSTUI-4058
test plan:
- go to a navbar example
- add the new `onHiddenClick` prop and `href` to the items
- visible items should behave as a link and not have the onclick behaviour
- hidden/truncated items should not be a link and have the onclick fn
> feat(ui-top-nav-bar): add onclick prop for hidden menu items

- packages/__docs__/_redirects
this fixes the redirect for the v8 docs so https://instructure.design/v8/ works
> chore: add redirect for v8 docs

- .github/workflows/vrt.yml
This will mark the Chromatic check red in a PR until either the change is accepted or there is no change.
see: https://www.chromatic.com/docs/github-actions/#command-exit-code-for-required-checks
Also update Chromatic GH action runner versions
> chore: do not allow PR merge if there is a Chromatic change

- packages/ui-drilldown/src/Drilldown/DrilldownOption/props.ts
Closes: INSTUI-3926
test plan:
- open docs for Drilldown component
- check props for Drilldown.Option -> it should be clear how to use the `as` prop
- check if you can set the `as` prop following the docs and inspect the element if it had worked (e.g. try setting it `as="form"`)
> docs(ui-drilldown): clarify usage of `as` prop for Drilldown.Option

- packages/ui-file-drop/src/FileDrop/index.tsx
TEST PLAN:
Read a FileDrop with a screen reader. When there is an error it should say the error message and 'invalid data'
> INSTUI-4110  fix(ui-file-drop): set aria-invalid to true when there are error messages

- packages/ui-number-input/src/NumberInput/__tests__/NumberInput.test.tsx
- packages/ui-number-input/src/NumberInput/index.tsx
- packages/ui-number-input/src/NumberInput/styles.ts
- packages/ui-pagination/src/Pagination/PaginationPageInput/__new-tests__/PaginationPageInput.test.tsx
- packages/ui-pagination/src/Pagination/__new-tests__/Pagination.test.tsx
Closes: INSTUI-3857
**Test**
Observe if `NumberInput` component has type `number`. Default arrows of the html input component should be hidden in every browser. Please check this in multiple browsers.
> fix(ui-number-input): set numberinput type to number

- packages/ui-drilldown/src/Drilldown/index.tsx
Closes: INSTUI-4098
test plan:
- open drilldown in the docs
- go to the `shouldHideOnSelect` example
- modify the example so the Drilldown.Options have numbers as ids in a random order (e.g.:
```
<Drilldown.Option value="1" id="2">
Option 1
</Drilldown.Option>
<Drilldown.Option value="2" id="1">
Option 2
</Drilldown.Option>
<Drilldown.Option value="3" id="3">
Option 3
</Drilldown.Option>
```
- use arrow keys to navigate between options
- the highlighted option should change as expected (for the incorrect behaviour see our currently deployed docs page)
> fix(ui-drilldown): index drilldown options to always preserve the correct order

- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/DesktopLayout/styles.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/DesktopLayout/theme.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/theme.ts
INSTUI-4116
explanation:
- topnavbar desktop layout z-index didn't have any effect because of the missing `position: relative`
- topnavbar was positioned above everything else (including tray/modal/popovers/etc) which is not the desired behavior according to the design team
test plan:
- add a tray component and a topnavbar to the same page and check if tray is above topnavbar is both small viewport and desktop
- add a select/popover/menu to tray and check if the stacking order is still correct (no menu behind navbar or tray)
> fix(ui-top-nav-bar): lowered topnavbar zindex so it goes below trays/popovers/modals/etc

- packages/ui-buttons/src/CondensedButton/props.ts
TEST PLAN:
set CondensedButton's color prop to secondary. There should be no failed prop type warning in the console
> INSTUI-4130 Do not emit failed prop type warning when setting CondensedButton's color to 'secondary'

- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/props.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/props.ts
INSTUI-4121
test plan:
- open topnav example
- resize viewport to display smallviewportlayout
- add `renderNavbarStartDangerousHack` prop to the `smallViewportConfig`
- test if the "hack" shows up in small viewport (and not in desktop view)
> feat(ui-top-nav-bar): add workaround hack for new topnav design with the old api

- .github/workflows/deploy.yml
- .github/workflows/pr-validation.yml
- .github/workflows/preview.yml
INSTUI-4139
this pr creates 2 new actions:
- one to build and deploy the docs app from a PR to `gh-pages`
- and another to build and deploy the docs app on master push to `gh-pages` 
(note that this doesn't replace [instructure.design](instructure.design) and only creates a parallel copy with the url [https://instructure.github.io/instructure-ui/](https://instructure.github.io/instructure-ui/); a full replacement needs some additional things like the legacy docs and should be done in a separate ticket)
this pr also removes a part of the pr validation action (which runs the unit tests) which builds and deploys the docs to netlify
> deploy the docs app from a PR to gh-pages

- packages/ui-menu/src/Menu/MenuItem/index.tsx
- packages/ui-menu/src/Menu/MenuItem/props.ts
This is uses MenuItemProps instead, this type is exported. Also added some documentation for some props.
Same as https://github.com/instructure/instructure-ui/pull/1597 just for the v8 branch
TEST PLAN:
import this component and check in the IDE that you can use the onSelect prop in TypeScript
> INSTUI-4145 MenuItem's onSelect type did not expose its value and selected types (v8)

- packages/ui-date-input/src/DateInput2/README.md
- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-date-input/src/DateInput2/props.ts
- packages/ui-text-input/src/TextInput/styles.ts
> feat(ui-date-input,ui-text-input): add custom validation function

- packages/ui-menu/src/Menu/MenuItem/index.tsx
- packages/ui-menu/src/Menu/MenuItem/props.ts
This is uses MenuItemProps instead, this type is exported. Also added some documentation for some props.
TEST PLAN:
import this component and check in the IDE that you can use the onSelect prop in TypeScript
> INSTUI-4145 MenuItem's `onSelect` type did not expose its value and selected types

- packages/babel-plugin-transform-imports/README.md
- packages/ui-color-picker/src/ColorContrast/index.tsx
- packages/ui-color-picker/src/ColorIndicator/styles.ts
- packages/ui-color-picker/src/ColorMixer/__new-tests__/ColorMixer.test.tsx
- packages/ui-color-picker/src/ColorMixer/index.tsx
- packages/ui-color-picker/src/ColorPicker/__new-tests__/ColorPicker.test.tsx
- packages/ui-color-picker/src/ColorPicker/index.tsx
- packages/ui-color-picker/src/ColorPreset/index.tsx
- packages/ui-color-utils/src/index.ts
babel-plugin-transform-imports cannot handle if there are multiple exports from a file. This commit adds a default export which works with this plugin
TEST PLAN:
make sure the CJS builds do not try to run function from color utils without importing them
> INSTUI-4143 ui-color-picker,ui-color-utils: fix corrupted CJS build

- packages/ui-codemods/__testfixtures__/updateV10Breaking/colors.input.js
- packages/ui-codemods/__testfixtures__/updateV10Breaking/colors.output.js
- packages/ui-codemods/__testfixtures__/updateV10Breaking/colors2.input.tsx
- packages/ui-codemods/__testfixtures__/updateV10Breaking/colors2.output.tsx
- packages/ui-codemods/__tests__/updateV10Breaking.test.js
- packages/ui-codemods/lib/updateV10Breaking.ts
- packages/ui-codemods/lib/utils/updateToV10Colors.ts
Closes: INSTUI-4144
You can use this command to run the test for this codemod: 
` npx jest /packages/ui-codemods/__tests__/updateV10Colors.test.js`
> feat(ui-codemods): add codemod for v10 color update

- package-lock.json
- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-date-input/src/DateInput2/props.ts
- packages/ui-date-input/src/index.ts
INSTUI-4155
test plan:
- try inputting dates manually into DateInput2 (in ISO format) -> validation should pass and date should be selected in the calendar popover
- after setting a date in iso format it should be formatted according to the locale
- try different locales, also ones that doesn't use the latin script for number (e.g.: arabic, hindi, etc.) -> formatting and validation should still work as expected
- try the above mentioned locales with the year picker -> logic for the year picker should work as expected (like the start and end year config)
> fix(ui-calendar,ui-date-input): fix date formatting and validation for different locales

- package-lock.json
- package.json
- packages/__docs__/build-docs.mjs
- packages/__docs__/buildScripts/build-docs.mts
- packages/__docs__/package.json
- packages/instui-config/package.json
- packages/ui-scripts/lib/icons/build-icons.js
not fully fixed yet, cant commit due to https://github.com/conventional-changelog/commitlint/issues/4106
what works:
- `bootstrap`
- `dev`
- `test:vitest` almost  (1 test fails for some reason)
> chore: fix build on Windows

- packages/babel-plugin-transform-imports/README.md
- packages/ui-color-picker/src/ColorContrast/index.tsx
- packages/ui-color-picker/src/ColorIndicator/styles.ts
- packages/ui-color-picker/src/ColorMixer/index.tsx
- packages/ui-color-picker/src/ColorPicker/index.tsx
- packages/ui-color-picker/src/ColorPreset/index.tsx
- packages/ui-color-utils/src/index.ts
Same as https://github.com/instructure/instructure-ui/pull/1609 just for the v8 branch.
For some reason most CI items are not triggering, I've ran them manually and they are OK
> Fix cjs build in the v8 branch

- packages/ui-menu/src/Menu/MenuItem/props.ts
- packages/ui-menu/src/Menu/README.md
INSTUI-4020
adding `target` to MenuItem already worked but now it's documented
> docs(ui-menu): `target` prop support for MenuItem

- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-date-input/src/DateInput2/README.md
- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-date-input/src/DateInput2/props.ts
INSTUI-4167
this PR adds:
- return iso dateString from the `onChange` callback
- `formatDate` prop
- extend documentation
test plan:
- check docs for DateInput2
- check if the return values in the `onChange` callback are good (esp the dateString and whether you can parse it back to `Date`)
- try a custom `formatDate` function and see if it works as expected
> feat(ui-calendar,ui-date-input): improve DateInput2

- package.json
- scripts/clean.js
This new script deletes all `node_modules` folders recursively which is useful when `npm install` fails for some reason and these folders are in a corrupted state
TEST PLAN:
run `npm run clean-node` and observe that all `node_modules` folders are deleted
> chore: add script to delete node_modules recursively

- packages/ui-radio-input/src/RadioInput/props.ts
- packages/ui-radio-input/src/RadioInputGroup/README.md
- packages/ui-radio-input/src/RadioInputGroup/index.tsx
- packages/ui-radio-input/src/RadioInputGroup/props.ts
choosing a bad name for your `RadioInputGroup` can cause them to interfere with each other, e.g. try out this code:
```jsx
<div>
<RadioInputGroup name="abc">
<RadioInput label="Off" value="off"/>
<RadioInput label="Allow" value="allow" />
<RadioInput label="On" value="on" />
</RadioInputGroup>
This is a different group but because they have the same name both are broken
<RadioInputGroup name="abc">
<RadioInput label="Off" value="off"/>
<RadioInput label="Allow" value="allow" />
<RadioInput label="On" value="on" />
</RadioInputGroup>
</div>
```
> RadioInput: Better docs for name and value props

- docs/contributor-docs/v11-upgrade-guide.md
- packages/__docs__/components.js
- packages/ui-table/src/Table/Body/index.tsx
- packages/ui-table/src/Table/Body/props.ts
- packages/ui-table/src/Table/Body/styles.ts
- packages/ui-table/src/Table/Cell/index.tsx
- packages/ui-table/src/Table/Cell/props.ts
- packages/ui-table/src/Table/ColHeader/props.ts
- packages/ui-table/src/Table/ColHeader/styles.ts
- packages/ui-table/src/Table/Head/index.tsx
- packages/ui-table/src/Table/Head/props.ts
- packages/ui-table/src/Table/Head/styles.ts
- packages/ui-table/src/Table/README.md
- packages/ui-table/src/Table/Row/index.tsx
- packages/ui-table/src/Table/Row/props.ts
- packages/ui-table/src/Table/Row/styles.ts
- packages/ui-table/src/Table/RowHeader/index.tsx
- packages/ui-table/src/Table/RowHeader/props.ts
- packages/ui-table/src/Table/TableContext.ts
- packages/ui-table/src/Table/__new-tests__/Table.test.tsx
- packages/ui-table/src/Table/index.tsx
- packages/ui-table/src/Table/props.ts
- packages/ui-table/src/index.ts
To test:
- Check out the new examples and play with them.   
- Try to add custom components as children that just wrap existing components.               
- Try to make fully new custom components.  
- Add stupid things as children to components (see one of the new tests), it should not result in an exception
>   INSTUI-4188 New Table API to allow custom children

- packages/ui-checkbox/src/Checkbox/index.tsx
- packages/ui-checkbox/src/Checkbox/props.ts
- packages/ui-checkbox/src/Checkbox/styles.ts
- packages/ui-radio-input/src/RadioInput/index.tsx
- packages/ui-radio-input/src/RadioInput/props.ts
- packages/ui-radio-input/src/RadioInput/styles.ts
Closes: INSTUI-4197
**Test plan**
Go through all of the RadioInput/RadioInputGroup examples in the docs app:
- Check whether the design is not broken
- click events should be registered if you click on the radio group icon or label. If you click on the remaining area of the radio input, click should not be registered.
> fix(ui-radio-input): only radio button and label are clickable

- packages/ui-selectable/src/Selectable/__tests__/Selectable.test.tsx
- packages/ui-selectable/src/Selectable/index.tsx
`aria-owns` seems to be misused here. It rearranges the DOM seen by the screenreader, so the [subtree owned by the element will be its child](https://tink.uk/using-the-aria-owns-attribute/). In our case it meant that a popup will the the child of an `input` component.
Also its very rarely used, see https://www.makethingsaccessible.com/guides/aria-controls-vs-aria-owns/ , there is just one sample use case for it at W3C ([a navigation treeview](https://www.w3.org/WAI/ARIA/apg/example-index/#examples_by_role_label))
To test:
- Test all examples of Select, SimpleSelect, Selectable with keyboard navigation and VoiceOver. Test on mobile devices with TalkBack/VoiceOver and Windows too if possible
Note: This will need to be ported to InstUI v8 and v9
> INSTUI-4080 fix(ui-selectable): fix Select options not being selectable on iOS Safari with VoiceOver on

- packages/__docs__/src/CodeSandboxButton/index.tsx
Closes: INSTUI-4201
test plan:
- test if examples in Select, SimpleSelect, Selectable are opened without error in CodeSandbox
> chore: codeSandbox error fixed in Select, SimpleSelect, Selectable

- packages/ui-menu/src/Menu/MenuItem/index.tsx
- packages/ui-menu/src/Menu/MenuItem/props.ts
- packages/ui-menu/src/Menu/MenuItem/styles.ts
- packages/ui-menu/src/Menu/index.tsx
- packages/ui-menu/src/Menu/props.ts
Closes: INSTUI-4192
Add `renderLabelInfo` - either a string or a React.Node - prop to a `Menu`. It should be shown near the label. Override the `minWidth` theme variable if the width is not enough for the renderLabelInfo content.
> feat(ui-menu): add renderLabelInfo to Menu

- packages/ui-color-picker/src/ColorPicker/__tests__/ColorPicker.test.tsx
- packages/ui-selectable/src/Selectable/__tests__/Selectable.test.tsx
- packages/ui-selectable/src/Selectable/index.tsx
Backport of https://github.com/instructure/instructure-ui/pull/1668
aria-owns seems to be misused here. It rearranges the DOM seen by the screenreader, so the subtree owned by the element will be its child. In our case it meant that a popup will the the child of an input component. Backport of https://github.com/instructure/instructure-ui/pull/1668
TEST PLAN:
Test all examples of Select, SimpleSelect, Selectable with keyboard navigation and VoiceOver. Test on mobile devices with TalkBack/VoiceOver and Windows too if possible
> [v8] fix(ui-selectable): fix Select options not being selectable on iOS Safari with VoiceOver on

- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-color-picker/src/ColorPicker/__tests__/ColorPicker.test.tsx
> fix(ui-calendar): fix code to remove unnecessary warnings

- packages/ui-buttons/src/CondensedButton/props.ts
port of https://github.com/instructure/instructure-ui/pull/1580 from v9
TEST PLAN:
set CondensedButton's color prop to secondary. There should be no failed prop type warning in the console
> [v8] Fix condensedButton warning when color is set to 'secondary'

- packages/ui-buttons/src/BaseButton/README.md
- packages/ui-buttons/src/Button/README.md
- packages/ui-buttons/src/IconButton/README.md
These are hard to figure out and are asked sometimes on Slack.
To test: Just check the new example in the docs app
> docs(ui-buttons): add theming override example for Button and IconButton

- .github/workflows/manual-release-from-pr.yml
- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-date-input/src/DateInput/README.md
- packages/ui-date-input/src/DateInput2/README.md
- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-date-input/src/DateInput2/props.ts
/INSTUI-4219
this PR simplifies and improves the `DateInput2` api
the docs are also extended to address the experimental nature of the component and elaborate on usage
test plan:
try the following things in a couple different locales (e.g. `it-it`, `ar-eg`,  `pt-br`)
- try setting a date by typing it in manually and blurring the input
- try selecting a date from the picker
- check if the picker shows the correct date after manually typing or selecting from the picker and closing it
- try the year picker: see if the correct year is selected after closing or typing the date manually
- check the custom date validation, customize it and see if it works as expected
- test the default validation: try setting an invalid date
- try the date formatting: modify the example and see if it works as …
> feat(ui-date-input): improve DateInput2 api, extend docs

- packages/ui-selectable/src/Selectable/__tests__/Selectable.test.tsx
- packages/ui-selectable/src/Selectable/index.tsx
`aria-owns` seems to be misused here. It rearranges the DOM seen by the screenreader, so the subtree owned by the element will be its child. Backport of https://github.com/instructure/instructure-ui/pull/1668
TEST PLAN:
Test all examples of Select, SimpleSelect, Selectable with keyboard navigation and VoiceOver. Test on mobile devices with TalkBack/VoiceOver and Windows too if possible
> [v9] fix(ui-selectable): fix Select options not being selectable on iOS Safari with VoiceOver on

- packages/ui-simple-select/src/SimpleSelect/__new-tests__/SimpleSelect.test.tsx
- packages/ui-simple-select/src/SimpleSelect/index.tsx
- Fixed an issue where the input value was not updated appropriately when the list of options was changed.
- Implemented behavior to clear the input if the previously selected option is no longer available in the updated options.
- Ensured the input value persists if the previously selected option remains in the updated options list.
> fix(ui-simple-select): ensure input value updates correctly when options change

- packages/__examples__/.storybook/stories/stories.ts
- packages/ui-test-locator/src/index.ts
- packages/ui-test-locator/src/utils/locator.ts
- packages/ui-test-queries/src/index.ts
- packages/ui-test-queries/src/utils/bindElementToUtilities.ts
- packages/ui-test-queries/src/utils/queries.ts
This is an early preparation to use `pnpm`. When migrating to it, TS compilation fails because it cannot infer the types of locator functions properly, likely if someone would use our locators they could not if they use `pnpm`
TEST PLAN:
Just check the code that its not exporting something that it should not have
> refactor(ui-test-locator,ui-test-queries): export types needed for locator functions

- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-date-input/src/DateInput/README.md
- packages/ui-date-input/src/DateInput2/README.md
- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-date-input/src/DateInput2/props.ts
> feat(ui-calendar,ui-date-input): update DateInput2 api, add placeholder hint

- packages/ui-text-input/src/TextInput/styles.ts
Closes: INSTUI-4226
TEST PLAN:
- copy the following code to the code editor of the documentation:
```
<SimpleSelect
defaultValue="option-1"
renderLabel="Option Icons"
renderBeforeInput={<IconCommonsLine />}
>
<SimpleSelect.Option id="opt1" value="option-1">
Option one
</SimpleSelect.Option>
</SimpleSelect>
```
- inspect the parent span of the svg element, and in Developer Tools>Styles, hover the mouse over align-items: center to check if the icon is vertically aligned
- previously the icon wasn't vertically centered
> fix(ui-text-input): icon in SimpleSelect is vertically centered

- packages/ui-calendar/src/Calendar/index.tsx
- packages/ui-date-input/src/DateInput/__new-tests__/DateInput.test.tsx
- packages/ui-date-input/src/DateInput/index.tsx
Closes: INSTUI-4236
Locale and timezone was not passed down to the calendar in "minimal configuration" mode.  Also fixes validation and formatting when locale has changed
TEST PLAN: pass locale to the `<DateInput local="fr"` and see if the weekdaylabels changed and different locale dates are validated correctly
> fix(ui-calendar,ui-date-input): fix locale and timezone for simple api

- .github/workflows/deploy.yml
this was left in from a prev iteration and since the file doesn't exist anymore, the workflow fails
> chore: remove redirect task from deploy action

- packages/ui-date-input/src/DateInput2/index.tsx
test plan:
- check the custom validation example for dateinput2
> fix(ui-date-input): fix messages prop sometimes not populating in DateInput2

- packages/ui-form-field/src/FormField/README.md
- packages/ui-form-field/src/FormField/props.ts
- packages/ui-progress/src/ProgressBar/README.md
- packages/ui-progress/src/ProgressCircle/README.md
- packages/ui-side-nav-bar/src/SideNavBar/README.md
Closes: INSTUI-4292, INSTUI-4283, INSTUI-4255
TEST PLAN:
Just check the new text and the associated INSTUI issue, with 4255 screen readers should read the label too in the example
> fix(ui-progress,ui-side-nav-bar): improve a11y for Progress and SideNavBar examples

- packages/__docs__/src/App/index.tsx
- packages/__docs__/src/Header/index.tsx
- packages/__docs__/src/Hero/index.tsx
- packages/ui-avatar/src/Avatar/README.md
- packages/ui-source-code-editor/src/SourceCodeEditor/README.md
INSTUI-4248
INSTUI-4249
INSTUI-4250
INSTUI-4270
INSTUI-4289
test plan:
- docs landing page "what's new" section now has white bg for better contrast
- docs side nav open button now have `aria-expanded="false` so screenreaders announce that it's closed
- added screen reader label to instructure logo in sidenav
- ui-avatar has `aria-hidden` -> this is now mentioned in the README
- source code editor example for syntax highlight now has a label
> chore(ui-avatar,ui-source-code-editor): fix docs a11y issues

- packages/ui-expandable/src/Expandable/README.md
- packages/ui-expandable/src/Expandable/index.tsx
- packages/ui-expandable/src/Expandable/props.ts
- packages/ui-toggle-details/src/ToggleDetails/__tests__/ToggleDetails.test.tsx
- packages/ui-toggle-details/src/ToggleDetails/index.tsx
Also do not render an empty div for the details in this case. Note that this might break tests since
they might find these DOM parts via these ARIA tags. Also the empty div took up a small space when expanded (0.375rem), this might cause layout changes
TEST PLAN:
Make a ToggleDetails without any children, it should have no aria tags. Should still listen to mouse events
> INSTUI-4241: fix(ui-toggle-details): do not put aria-expanded and aria-controls on  the toggle if there is nothing to toggle

- packages/__docs__/buildScripts/DataTypes.mts
- packages/__docs__/src/App/index.tsx
- packages/__docs__/src/Hero/props.ts
- packages/__docs__/src/Search/index.tsx
- packages/__docs__/src/Search/props.ts
- packages/debounce/src/debounce.ts
- packages/ui-a11y-content/src/ScreenReaderContent/styles.ts
- packages/ui-alerts/src/Alert/index.tsx
- packages/ui-alerts/src/Alert/props.ts
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/index.tsx
- packages/ui-drawer-layout/src/DrawerLayout/DrawerContent/props.ts
- packages/ui-position/src/Position/index.tsx
- packages/ui-tabs/src/Tabs/index.tsx
- packages/ui-text-area/src/TextArea/index.tsx
- packages/ui-truncate-list/src/TruncateList/index.tsx
- packages/ui-truncate-text/src/TruncateText/index.tsx
The issue is that our `ScreenReaderContent` class does not hide its text from Screenreader focus, and this is used by `Alert` to display it in an ARIA live region.
I've tried to fix the `ScreenReaderContent` class, but could not do it, so the solution way to add a timeout to the screenreader alerts, so users will not have time to go back with the focus
Also some better types in the docs app and the debounce utility
TEST PLAN:
Enter some text in the docs in the top search field with screenreader on. After this focus out, and find the beginning of the page. It should not read the search results again
> fix: docs screenreader alerts are no longer screenreader focusable

- .github/workflows/deploy-docs-to-netlify.yml
- .github/workflows/deploy.yml
- .github/workflows/manual-deploy-docs.yml
- .github/workflows/manual-release-to-npm.yml
- .github/workflows/release.yml
Fixes docs-app: `[webpack-cli] TypeError [ERR_INVALID_ARG_TYPE]: The \"paths[0]\" argument must be of type string. Received undefined` in Github actions. 
This became needed when we started using ESM Webpack config files
> chore: fix Github actions build failing with webpack-cli error

- .github/workflows/deploy.yml
this should fix the issue where maintenance builds are getting cleared on new deploys
> chore: fix gh pages deploy action removing previous builds

- packages/ui-alerts/src/Alert/index.tsx
- `onDismiss` was not being fired on `screenReaderOnly` alerts, unless `transition: 'none'` was specified alongside.
- Default transition value is `'fade'`. This change makes `screenReaderOnly` alerts an implicit `transition: 'none'` when executing `onDismiss`.
Credits for finding this bug: @meister245
> fix(ui-alerts): trigger onDismiss for SR-only alerts

- packages/__docs__/src/Nav/index.tsx
Closes: INSTUI-4246
ISSUE:
On the main page, in the navigation panel, there are two navigation landmarks inside each other, which confuses users:
- a nav tag
- and a span with a role="navigation"
The role="navigation" was removed in accordance to LevelAccess' suggestion.
TEST PLAN:
- the menu starting with the "Getting started" option should not be announced as a navigation landmark.
> chore: multiple navigation landmarks are removed from navigation panel

- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-date-input/src/index.ts
this was a minor but annoying bug that prevented the messages prop sometimes to work properly.
to test:
- check the basic and the `Date validation` (last) example with custom messages and valid + invalid dates. See if the messages appear/disappear as they should
> fix(ui-date-input): fix DateInput2 to update messages properly

- packages/ui-themes/src/themes/canvas/index.ts
- packages/ui-themes/src/themes/canvasHighContrast/index.ts
> fix(ui-themes): make all colors available

- packages/__docs__/buildScripts/DataTypes.mts
- packages/__docs__/src/App/index.tsx
- packages/__docs__/src/App/props.ts
- packages/__docs__/src/Document/index.tsx
- packages/__docs__/src/Document/props.ts
- packages/__docs__/src/Icons/index.tsx
- packages/__docs__/src/versionData.ts
Now the focus moved to the 'close' button of the opened sidebar
TEST PLAN:
open and close the menu on the docs app with keyboard. Focus should not get lost. Also test with
screenreaders
Also better typing for some docs TS types.
> INSTUI-4266 : The open/close sidebar button does not cause focus loss

- packages/ui-color-picker/src/ColorContrast/README.md
- packages/ui-color-picker/src/ColorContrast/index.tsx
- packages/ui-color-picker/src/ColorContrast/props.ts
- packages/ui-color-picker/src/ColorPicker/index.tsx
- packages/ui-color-picker/src/ColorPicker/props.ts
- packages/ui-color-utils/src/contrastWithAlpha.ts
- packages/ui-color-utils/src/overlayColors.ts
- packages/ui-color-utils/src/validateContrast.ts
TEST_PLAN:
check if contrast calculation works as before for ColorContrast.
Test if you pass the onContrastChange callback, to ColorContrast or ColorPicker, it really gets called when the color changes.
Check if preciously internally used methods work as before in color utils
Check if validationLevel prop does what it says
Closes: INSTUI-4360
> feat(ui-color-picker,ui-color-utils): add callback for contrast validation information and export validation methods

- packages/ui-number-input/src/NumberInput/index.tsx
- packages/ui-number-input/src/NumberInput/props.ts
this PR fixes a regression introduced in https://github.com/instructure/instructure-ui/pull/1767
original pr: https://github.com/instructure/instructure-ui/pull/1744
> fix(ui-number-input): fix regression and allow string type for NumberInput again

- packages/ui-progress/tsconfig.build.json
- packages/ui-tag/src/Tag/index.tsx
Remove onClick prop from Tag when callback is not provided.
Fix Progress dependency mismatch (test-locator)
Closes: INSTUI-4332
Test:
Check Tag component in the doc App with Safari and VoiceOver.
Tag should not announced as clickable (select with: control+shift+option+arrow buttons)
> fix(ui-tag): Non-interactive components are announced as "clickable" by screen readers

- .github/workflows/deploy.yml
this is needed so a v8 deploy doesn't override other versions (this is backported from v9 and v10)
> chore: update gh pages deploy action

- packages/ui-motion/src/Transition/README.md
- packages/ui-toggle-details/src/ToggleDetails/README.md
Closes: 
INSTUI-4290
INSTUI-4312
INSTUI-4295
ISSUE: button text changes in Transition and ToggleDetail examples are not announced by screenreaders
TEST PLAN:
- In NVDA, the button text changes should be announced by the screenreader in the Transition page examples
- In NVDA, the button text changes should be announced by the screenreader in the second example on the ToggleDetails page
NOTE: unfortuntely putting the aria-live="polite" tag will cause VoiceOver announcing the button text twice. This is a known bug: https://stackoverflow.com/questions/61244988/aria-live-content-read-twice-by-mac-chrome-voiceover After talking about it with Matyi, we concluded it's still better for VoiceOver to read twice and NVDA reading it once than NVDA not reading it at all.
> docs(ui-buttons): button text changes now announced by screenreaders

- docs/guides/using-theme-overrides.md
- packages/__docs__/components.js
- packages/__docs__/src/Theme/index.tsx
- packages/emotion/src/__tests__/useTheme.test.tsx
- packages/emotion/src/getTheme.ts
- packages/emotion/src/useTheme.ts
- packages/theme-registry/src/ThemeRegistry.ts
- packages/theme-registry/src/__tests__/ThemeRegistry.test.ts
- packages/ui-themes/README.md
- packages/ui-themes/src/__new-tests__/themes.test.tsx
- packages/ui-themes/src/index.ts
- packages/ui-themes/src/themes/canvas/index.ts
- packages/ui-themes/src/themes/canvasHighContrast/index.ts
- packages/ui-utils/src/isBaseTheme.ts
The main goal of this PR is to make it possible to run InstUI v8/v9 in the same page as InstUI v10 when the host app uses the older version and a later initialized one v10.
Currently this causes the v10 app to look buggy because `ThemeRegistry` will return an incompatible v8 theme object:
in `canvas.ts`:
```
const theme = ThemeRegistry.registerTheme(__theme)
export default theme
```
in `ThemeRegistry.registerTheme`:
```
if (theme.key && registry.themes[theme.key]) {
return registry.themes[theme.key] as RegisteredTheme<T>
}
```
This PR makes it possible to get the theme directly circumventing `ThemeRegistry` and its theme cache. Also deprecates `ThemeRegistry` (which is used for global themes)
> INSTUI-4322 Make it possible to not use global theme registry. Deprecate global theme registry.

- packages/ui-dialog/src/Dialog/README.md
- packages/ui-dialog/src/Dialog/props.ts
Closes: INSTUI-4293, INSTUI-4291
ISSUES:
- the form labels in the dialog example are not descriptive enough
- the Dialog example does not have a role or appropriate description
TEST PLAN:
- when opening the Dialog example, the screen reader should announce that it is a dialog and read the dialog's label (e.g., "Full name form").
- input labels should be descriptive in the example, such as "First name" instead of just "First", when using a screenreader
- review the added recommendations for dialog accessibility
> docs(ui-dialog): add a11y clarifications to Dialog docs

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-pagination/src/Pagination/PaginationButton/index.tsx
- packages/ui-pagination/src/Pagination/__new-tests__/Pagination.test.tsx
- packages/ui-pagination/src/Pagination/index.tsx
- packages/ui-pagination/src/Pagination/props.ts
- packages/ui-pagination/src/Pagination/theme.ts
- packages/ui-popover/src/Popover/index.tsx
- packages/ui-tooltip/src/Tooltip/index.tsx
INSTUI-4347
INSTUI-4334
INSTUI-4353
test plan:
- check if pagination indicators have an 8px gap now
- inspect pagination indicators: should have a markup with `<ul>` and `<li>`
- voiceover should announce that the indicators are in a list
- tooltips should be dismissable with esc even when you hover on them (and any other way)
> small fixes: tooltip close on esc; pagination indicator gap; pagination displayed as a html list for a11y

- packages/ui-a11y-content/src/AccessibleContent/index.tsx
- packages/ui-a11y-content/src/AccessibleContent/props.ts
- packages/ui-date-input/src/DateInput2/__new-tests__/DateInput2.test.tsx
- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-react-utils/src/getElementType.ts
Closes: INSTUI-4356
NVDA really does not like if we give role=listbox to a table, removing it fixes it getting stuck
TEST PLAN:
Try navigating a DateInput2 example with VO, NVDA, JAWS
> fix(ui-date-input): fix DateInput2 not working at all with NVDA

- packages/__docs__/src/Header/index.tsx
- packages/__docs__/src/Hero/index.tsx
- packages/ui-progress/tsconfig.build.json
Closes: 
INSTUI-4263
INSTUI-4265
INSTUI-4272
ISSUES:
- Quick start/Github/Migration guide buttons are not in list tags but appear as list
- "What's new?" section is nested within navigation landmark despite not being a top-level landmark
- Instructure logo is nested within navigation landmark, but it isn't a top-level landmark
- Instructure side menu container incorrectly has a heading tag
TEST PLAN:
- check if Quick start/Github/Migration guide buttons are in list on the main page
- check if "What's new?" section is a div instead of an aside tag on the main page
- check if inside the navigation bar, the container of the Instructure logo does not have a banner role 
- check if container below the previous element is a div, not a h1 tag
> chore(ui-progress): improve accessibilty on documentation main page

- packages/ui-color-picker/src/ColorPicker/index.tsx
- packages/ui-svg-images/src/InlineSVG/index.tsx
Closes: INSTUI-4259
test plan:
- check colorpicker example with tooltip if voiceover reads the tooltip context correctly
> fix(ui-color-picker): make ColorPicker tooltip VoiceOver focusable

- docs/guides/using-theme-overrides.md
- packages/emotion/README.md
- packages/ui-themes/README.md
Content mostly recovered from the deleted parts in the v9 version, but I also tried to make the examples more clear
> docs: add more documentation on how to do theme overrides

- packages/ui-text-area/src/TextArea/index.tsx
Closes: INSTUI-4380
Test: add the `resize` property to `TextArea` component, resize it and observe whether the focusline follows the resizing properly.
> fix(ui-text-area): make focus line follow resized textarea

- packages/ui-checkbox/src/Checkbox/CheckboxFacade/theme.ts
- packages/ui-checkbox/src/Checkbox/ToggleFacade/theme.ts
- packages/ui-checkbox/src/Checkbox/index.tsx
- packages/ui-number-input/src/NumberInput/index.tsx
- packages/ui-radio-input/src/RadioInputGroup/index.tsx
- packages/ui-text-area/src/TextArea/index.tsx
- packages/ui-text-input/src/TextInput/index.tsx
INSTUI-4374
also fixed 2 instances where the wrong color token was used
test plan:
- check if screen readers ignore the required asterisk in field labels
> fix(many): hide required asterisks from screenreaders

- packages/ui-form-field/src/FormFieldLayout/index.tsx
- packages/ui-react-utils/src/omitProps.ts
- packages/ui-select/src/Select/README.md
- packages/ui-text-input/src/TextInput/README.md
- packages/ui-text-input/src/TextInput/index.tsx
- packages/ui-text-input/src/TextInput/props.ts
- packages/ui-text-input/src/TextInput/styles.ts
Closes: INSTUI-4344
When adding lots of elements like Tags it was overflowing the input field, this commit fixes it
This bug was introduced with https://github.com/instructure/instructure-ui/pull/1696 when we added a Flex layout without wrap.
TEST PLAN:
Add lots of elements to renderBeforeInput to Select,SimpleSelect,TextInput. They should wrap not overflow
> fix(ui-text-input): fix long before elements overflowing in TextInput, Select,SimpleSelect

- packages/__docs__/src/App/index.tsx
Closes: INSTUI-4249
ISSUE:
- the side navigation button is not announced as "expanded" when it is open.
TEST PLAN:
- click on the side navigation button in the documentation to open it
- the screen reader should announce it as "expanded" after the menu opens.
> chore: add expanded state to menu side navigation button

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-link/src/Link/styles.ts
- packages/ui-link/src/Link/theme.ts
Added text-underline-offset option to theme override variables.
Default value is set to auto.
> feat(link): add textUnderlineOffset to Link component theme override

- packages/ui-number-input/src/NumberInput/__examples__/NumberInput.examples.tsx
- packages/ui-number-input/src/NumberInput/__new-tests__/NumberInput.test.tsx
- packages/ui-number-input/src/NumberInput/index.tsx
- packages/ui-number-input/src/NumberInput/props.ts
Closes: [CLX-261](https://instructure.atlassian.net/browse/CLX-261)
Add `renderIcons` prop to make the increase/decrease buttons customizable with externally defined icons
TEST PLAN:
Chromatic test for rendered icons and unit test to ensure unchanged behaviour
[CLX-261]: https://instructure.atlassian.net/browse/CLX-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui-number-input): add renderIcons prop

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-pagination/src/Pagination/PaginationPageInput/styles.ts
- packages/ui-pagination/src/Pagination/PaginationPageInput/theme.ts
Closes: INSTUI-4385
it was unset, so its color was derived from a parent, now its set to our default text color
TEST PLAN:
check the color in devtools
> fix(ui-pagination): fix color of pageInput's label

- packages/ui-simple-select/src/SimpleSelect/index.tsx
Closes: INSTUI-4402
This bug was introduced by https://github.com/instructure/instructure-ui/pull/1674
This issue came up when the Option's value and children differed.
TEST PLAN:
make a SimpleSelect where the Option's value and children are not the same. Select a child and remove a different element from the child list. Selection should stay. Test with this code:
```
const InnerComponent = ({ handleSelect, options, value }) => {
// should work here SimpleSelect.Option's value is opt.name too
return (
<SimpleSelect
renderLabel="Controlled Select"
value={value.toString()}
onChange={handleSelect}
>
{options.map((opt) => (
<SimpleSelect.Option
key={opt.id}
id={opt.id.toString()}
value={opt.id.toString()}
>
{opt.name}
</SimpleSelect.Option>
))}
</SimpleSelect>
);
};
const allOptions = [
{ id: …
```
> fix(ui-simple-select): fix selection getting lost after options have changed

- packages/ui-date-time-input/src/DateTimeInput/index.tsx
Closes: INSTUI-4406
I could only reproduce it in CodeSandbox, but according to React documentation setState is not synchronous so the results are not deterministic.
TEST PLAN:
Enter '2' to the date input here: https://codesandbox.io/p/sandbox/stupefied-almeida-d8qxtr observe that the DateTimeInput's message field displays the correct date. 
Change the dependency to InstUI 10.9.0, reload the preview and do the same. DateTimeInput's value should be wrong
> fix(ui-date-time-input): fix DateTimeInput displaying wrong value of its value is changed in a onChange callback

- docs/guides/typography-system.md
- packages/shared-types/src/BaseTheme.ts
- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-heading/src/Heading/README.md
- packages/ui-heading/src/Heading/__examples__/Heading.examples.ts
- packages/ui-heading/src/Heading/index.tsx
- packages/ui-heading/src/Heading/props.ts
- packages/ui-heading/src/Heading/styles.ts
- packages/ui-heading/src/Heading/theme.ts
- packages/ui-text/src/Text/README.md
- packages/ui-text/src/Text/__examples__/Text.examples.ts
- packages/ui-text/src/Text/index.tsx
- packages/ui-text/src/Text/props.ts
- packages/ui-text/src/Text/styles.ts
- packages/ui-themes/src/sharedThemeTokens/typography.ts
> feat(many): add new Typography tokens and update text and heading

- docs/guides/form-errors.md
- packages/ui-date-time-input/src/DateTimeInput/__new-tests__/DateTimeInput.test.tsx
- packages/ui-date-time-input/src/DateTimeInput/index.tsx
- packages/ui-form-field/src/FormFieldGroup/index.tsx
- packages/ui-form-field/src/FormFieldMessage/index.tsx
Backport of INSTUI-4405 from the v10 branch Github PR #1826
TEST PLAN:
- check the datetimeinput examples in the error forms guide
- setting the isRequired prop should display two separate asterisks for each field
- when required and displaying an error, the asterisks should turn red
- the errors should be displayed under the input field like it was a single field and not a group
> fix(ui-date-time-input,ui-form-field): make DateTimeInput compatible with the new error format

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-buttons/src/BaseButton/styles.ts
- packages/ui-buttons/src/BaseButton/theme.ts
- packages/ui-buttons/src/Button/README.md
> feat(shared-types,ui-buttons): add theme variables for default and hover states for buttons

- packages/ui-menu/src/Menu/MenuItem/index.tsx
Closes: INSTUI-4425
ISUUE:
- Menu.Item does not apply the target prop to the link, so the link always opens in the same tab
TEST PLAN:
- go the Menu component's example
- try the second menu item's (Default (Grid view)) with different target props like "_blank", "_self" or insert an iframe inside the View (above the first Menu.Item) and set the target to "myFrame":
```
<iframe name="myFrame" src="about:blank" width="600" height="400"></iframe>
```
- **the link should open according to the given target prop: "_blank" - new tab, "_self" - same tab, "myFrame" - in the iframe**
> fix(ui-menu): make Menu.Item apply target prop

- packages/ui-select/src/Select/Option/props.ts
- packages/ui-select/src/Select/README.md
- packages/ui-simple-select/src/SimpleSelect/Option/props.ts
- packages/ui-simple-select/src/SimpleSelect/README.md
Note: in the future we should do this differently. This will be a breaking change
> docs(ui-simple-select,ui-select): mention in Select, SimpleSelect docs that option ids must be globally unique

- packages/ui-file-drop/src/FileDrop/__new-tests__/FileDrop.test.tsx
- packages/ui-file-drop/src/FileDrop/index.tsx
- packages/ui-file-drop/src/FileDrop/props.ts
Closes: INSTUI-4431
ISSUE: Filedrop input cannot be focused, it needs a inputRef prop like Select or TextInput
TEST PLAN:
- test the example below in the documentation preview
- fileDrop should accept inputRef prop
- by clicking on the Focus File Input button, the FileDrop should receive focus
- review the updated documentation and new tests
```
class Example extends React.Component {
fileInputElement = null
focusFileInput = () => {
if (this.fileInputElement) {
this.fileInputElement.focus()
}
};
render() {
return (
<div>
<FileDrop
accept="image/*"
onDropAccepted={([file]) => console.log(`File accepted ${file.name}`)}
onDropRejected={([file]) => console.log(`File rejected ${file.name}`)}
inputRef={(el) => {
this.fileInputElement = el;
}}
renderLabel={
<View as="div" padding="xx-large …
```
> feat(ui-filedrop): add inputRef prop to make FileDrop focusable

- cypress/component/TimeSelect.cy.tsx
- docs/contributor-docs/v11-upgrade-guide.md
- packages/ui-time-select/src/TimeSelect/index.tsx
- packages/ui-time-select/src/TimeSelect/props.ts
ISSUE:
In the TimeSelect component, after explicitly setting a value, it cannot be cleared from the input field. When the value is deleted form the input filed and the input field loses focus, the last selected option is reapplied.
Also the onChange does not trigger when input field is cleared.
TEST PLAN:
test clearing values if allowClearingSelection is not set (should default to false)
- go to the "Controlled" TimeSelect example
- before selecting a new value, click the input field, delete its current value, and click elsewhere to ensure the input field loses focus
- the input value should go back to the initial value (11:59:00 PM) and onChange should not triggered (can be checked with a console.log)
- reload the same example
- select a new value from the dropdown
- after it' selected, …
> INSTUI-4429 fix(ui-time-select): clear input field after setting an empty value

- packages/ui-pagination/src/Pagination/__new-tests__/Pagination.test.tsx
- packages/ui-pagination/src/Pagination/index.tsx
Closes: INSTUI-4422
TEST PLAN:
check all examples in inspector, the pagination buttons should all be in lists. There should be no duplicate key warning in the console
> fix(ui-pagination): fix Pagination sometimes displaying non `li` elements in lists, fix key errors too

- packages/__docs__/src/App/index.tsx
- packages/__docs__/src/App/props.ts
- packages/__docs__/src/App/styles.ts
- packages/__docs__/src/Hero/index.tsx
- packages/__docs__/src/Nav/index.tsx
- packages/__docs__/src/NavToggle/index.tsx
- packages/__docs__/src/NavToggle/props.ts
Closes: INSTUI-4240
ISUUE: main page does not have a a 'Skip to main content' button to avoid going through repetitive content. This current implementation is based on this recommendation: https://www.a11y-collective.com/blog/skip-to-main-content/
TEST PLAN:
test skipt to main button:
- go through the different types of docs page with screenreader with Tab
1. main page
2. document like /#Alert or /#focus-management
3. changelog page /#CHANGELOG
4. theme page like /#canvas-high-contrast
5. icons page: /#icons
6. error page /#iconsss
- the first focusable element on each page should be a 'Skip to main content' button
- the button should not be visible when not focused
- when the button is clicked, it should bring the focus to the main content
- the 'Skip to main content' button also should …
> chore: add 'Skip to main content' button to the main page

- packages/ui-menu/src/Menu/MenuItem/index.tsx
- packages/ui-menu/src/Menu/MenuItemGroup/__new-tests__/MenuItemGroup.test.tsx
- packages/ui-menu/src/Menu/MenuItemGroup/index.tsx
- packages/ui-menu/src/Menu/MenuItemSeparator/index.tsx
- packages/ui-menu/src/Menu/index.tsx
- packages/ui-menu/src/Menu/props.ts
Closes: INSTUI-4285
Tested on VoiceOver, NVDA, JAWS. Also simplified DOM structure quite a bit, there are multiple examples of Menu online that do not use a List to wrap the whole thing, it was not needed
TEST PLAN:
Open the Menu example and go trough it with NVDA, JAWS, VoiceOver. You should be able to navigate and they should read the correct menu item number (e.g. 3 of 7).
Check the DOM structure with the inspector to see if it looks OK
> fix(ui-menu): screenreaders should read the correct number of menu items

- packages/ui-pagination/src/Pagination/index.tsx
We left margin unset, so it was inheriting values from the browser's stylesheet.
Fix for this fix: https://github.com/instructure/instructure-ui/pull/1839
> fix(ui-pagination): remove margin from legacy Pagination

- packages/ui-color-picker/src/ColorPreset/__new-tests__/ColorPreset.test.tsx
- packages/ui-color-picker/src/ColorPreset/index.tsx
INSTUI-4273
**Test:**
1. you have to test `ColorPreset` and `ColorContrast` separately, go to the docs page examples
2. try it with JAWS, NVDA and VoiceOver
3. go through the colors, the hex content of the color should be read only once
4. if you select one color, the hex content and a 'selected' text should be read
5. check if you notice other accessibility/screenreader issues
6. check the components with Accessibility Insights chrome extension
> fix(ui-color-picker): add hex to aria-label

- packages/ui-source-code-editor/src/SourceCodeEditor/README.md
- packages/ui-source-code-editor/src/SourceCodeEditor/__new-tests__/SourceCodeEditor.test.tsx
- packages/ui-source-code-editor/src/SourceCodeEditor/index.tsx
Closes: INSTUI-4289
ISSUE: SourceCodeEditor label is not linked to the input field pragmatically. Therefore screenreader does not read the label when tabbed into the input field
TEST PLAN:
- open the first example in SourceCodeEditor
- with a screenreader go into the input field
- the screenreader should announce the label 'javascript SourceCodeEditor with syntax highlight" when entering the input field
- the input (textbox) element should have an "aria-labelledby" attribute pointing to the label element by id.
> fix(ui-source-code-editor): link label to input field programmatically

- packages/ui-a11y-utils/src/FocusRegion.ts
We noticed a weird issue where sometimes a Modal got closed unexpectedly when we clicked on any Button.
```tsx
import { Button } from '@instructure/ui-buttons';
import { Modal } from '@instructure/ui-modal';
import { SimpleSelect } from '@instructure/ui-simple-select';
import React from 'react';
export const App: React.FC = () => {
const [modalOpen, setModalOpen] = React.useState(false);
return (
<>
<Button onClick={() => setModalOpen(true)}>Open modal</Button>
<Modal open={modalOpen} onDismiss={() => setModalOpen(false)} label="Modal">
<div style={{ display: 'flex', gap: '20px' }}>
<SimpleSelect renderLabel="Use only keyboard to open this select">
<SimpleSelect.Option id="foo" value="foo">
Foo
</SimpleSelect.Option>
<SimpleSelect.Option id="bar" value="bar">
Bar
</SimpleSelect.Option> …
```
> fix(ui-a11y-utils): fix focus region missing mouse down target

- packages/ui-select/src/Select/index.tsx
TEST PLAN: check if the bottom of select's dropdown and the option list has the same border radius
closes: INSTUI-4442
> fix(ui-select): fix select's dropdown border radius

- packages/__docs__/src/App/index.tsx
- packages/ui-date-time-input/src/DateTimeInput/README.md
This fix makes margins much smaller in small viewports, so pages look much better. This fixes Calendar examples being clipped off.
To test check out the DateTimeInput and Calendar pages in docs with width set to 320px via devtools.
closes: INSTUI-4256
> docs(ui-date-time-input): fix Calendar and DateTimeInput page examples clipped off in docs

- packages/ui-time-select/src/TimeSelect/index.tsx
- packages/ui-time-select/src/TimeSelect/props.ts
This was never intended as a required prop.
> fix(ui-time-select): make allowClearingSelection an optional prop

- packages/ui-time-select/src/TimeSelect/__new-tests__/TimeSelect.test.tsx
- packages/ui-time-select/src/TimeSelect/index.tsx
TimeSelect was resetting to its defaultValue after a valid value was set if entering an invalid value. This commit fixes it by not losing the selected option ID when the input changes
Testing the fix:
Enter the following code:
```
<TimeSelect
renderLabel="Choose a time"
placeholder="e.g., 4:00:00 PM"
defaultValue="2020-05-18T22:00:00"
step={15}
onChange={(e, { value }) => console.log(value)}
format="LTS"
/>
```
1. select a different time than the defaultValue
2. click into the input field, delete the value inside until there are multiple options shown and click outside/tab away. It should display the value you selected previously. There should be no change event emitted
Fixes INSTUI-4451
> Fix TimeSelect showing the wrong value when defaultValue is set and entering a wrong value after a good one

- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-a11y-utils/src/FocusRegionOptions.ts
- packages/ui-dialog/src/Dialog/props.ts
- packages/ui-popover/src/Popover/index.tsx
- packages/ui-tooltip/src/Tooltip/index.tsx
INSTUI-4459
- this fix https://github.com/instructure/instructure-ui/pull/1850 introduced some issues when trying to make Tooltip ESC closeable when inside of a modal without closing the Modal itself
- it resulted in the Tooltip disappearing when hovered over
- it also caused some focus issues in certain configurations
TEST PLAN:
**test the examples in Tooltip:**
- the Tooltip should remain visible when it is hovered over
- it should close on ESC, even when it is hovered over
- the Tooltip examples should work as expected, even with keyboard navigation
**test the Tooltip when inside of a modal:**
- open the TEST#1 code in the comments below
- the Tooltips should close on ESC without closing the modal, even when it is hovered over
**test the Tooltip with Tray:**
- open the TEST#2 code in …
> fix(many): fix Tooltip focus issues and make Tooltip closeable inside of a Modal

- packages/ui-pagination/src/Pagination/index.tsx
<ul> padding was unset and so inherited from the browser's stylesheet
Context: https://instructure.slack.com/archives/C0JCJ63TR/p1740483851746669?thread_ts=1737474461.141169&cid=C0JCJ63TR
Easy change, tried to do it myself:)
You can easily test what has changed by removing the padding in the browser's DevTools.
> fix(ui-pagination): remove padding from legacy Pagination

- packages/ui-form-field/src/FormField/index.tsx
This is a fix for the bug introduced by the FormFieldLayout refactor PR 1863. Now the multiple select example should not delete the added Tag-s
[Is a revert from here: packages/ui-form-field/src/FormField/index.tsx](https://github.com/instructure/instructure-ui/pull/1863/files#diff-c3fa8d3879537cb2154a993c04dfa9d0bd50e05c64ad876325b046f34c25d59c)
To Test: Check the select examples. Clicking on the label should bring the input field in the focus
> fix(ui-form-field): fix Select's focus selecting its leaf not instead of the input field

- packages/ui-form-field/src/FormFieldLayout/props.ts
INSTUI-4477
this bug was introduced when this line was removed: https://github.com/instructure/instructure-ui/pull/1863/files#diff-13252981104c2c32508f00c654a221b51e4b11acfc1ea64c9e1242e603fcb01cL183
test plan:
- check out branch locally (!) and open the textinput docs and see that there's no react warning error
> fix(ui-form-field): do not pass vAlign prop to underlying html element

- packages/ui-file-drop/src/FileDrop/index.tsx
By default browsers do not populate the input's `files` and `value` prop when a file is dropped (its populated when clicking on the control). This PR populates `files` prop when dropping (and the `value` prop which is calculated from this one)
To test:
Drop files into a `FileDrop` example, you should see the `files` object populated in devtool's "Properties" tab or in the console.
Test it with Chrome, Safari, FF
Fixes INSTUI-4476
> fix(ui-file-drop): underlying HTML input's 'files' prop is now populated when dropping a file

- packages/ui-form-field/src/FormField/__new-tests__/FormField.test.tsx
- packages/ui-form-field/src/FormField/index.tsx
- packages/ui-form-field/src/FormFieldLayout/styles.ts
Also add a test so clicking on the label selects the right control to fix bugs occuring like the one required https://github.com/instructure/instructure-ui/pull/1891
To test: open the page for `FormField` The 'inline' text should not be right aligned at the point when the layout changes from vertical to horizontal
> fix(ui-form-field): fix misaligned text when size is exactly at the breakpoint

- packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/index.tsx
- packages/ui-breadcrumb/src/Breadcrumb/BreadcrumbLink/props.ts
- packages/ui-tooltip/src/Tooltip/index.tsx
- packages/ui-tooltip/src/Tooltip/props.ts
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/DesktopLayout/__new-tests__/TopNavBarDesktopLayout.test.tsx
> feat(ui-breadcrumb,ui-tooltip): add tooltips for truncated breadcrumbs

- packages/ui-source-code-editor/src/SourceCodeEditor/index.tsx
INSTUI-4492
test plan:
- open sourcecodeeditor and make sure you can focus the editor view and scroll it via keyboard
- check dom: the `div` with class `cm-scroller` should have `tabIndex` 0 (and not -1)
> fix(ui-source-code-editor): make scrollview in SourceCodeEditor keyboard accessible

- packages/ui-utils/src/index.ts
This seems to occur rarely with e.g. Vite 2. Sadly we could not reproduce it
fixes INSTUI-4470
> fix(ui-utils): fix 'no matching export' build error

- cypress/component/Pagination.cy.tsx
- packages/ui-pagination/src/Pagination/index.tsx
- packages/ui-pagination/src/Pagination/props.ts
- packages/ui-pagination/src/Pagination/styles.ts
INSTUI-4461
**ISSUE:** 
- on smaller screen sizes the Pagination has a horizontal scrollbar
- in some cases it has a vertical scrollbar and page buttons and their focus ring aren't fully visible when the parent has no padding
**TEST PLAN:**
**test no horizontal scrollbars:**
- open the examples in Pagination
- click Inspect then switch to mobile device view
- when exceeding the width of the container, the pagination numbers should wrap instead of a horizontal scrollbars appearing, and the new lines should be centered (similarly to the the legacy examples)
**test no vertical scrollbars:**
- go to the first example, click Inspect and on the Styles tab remove the preview parent element's (class="css-kinttp-preview") padding
- while the parent's padding removed, try when no margin prop is …
> fix(ui-pagination): make Pagination wrap on smaller screen sizes and prevent scrollbars

- packages/ui-side-nav-bar/src/SideNavBar/__new-tests__/SideNavBar.test.tsx
- packages/ui-side-nav-bar/src/SideNavBar/index.tsx
Now we allow any valid React element.
To test:
Add null/undefined/falsy children to the SideNavBar
Fixes INSTUI-4496
> INSTUI-4496 fix(ui-side-nav-bar): fix crash on null/falsy children

- packages/ui-form-field/src/FormFieldMessage/theme.ts
INSTUI-4491
test plan:
- check a newError message in the docs app -> the red should be darker than the current/previous color
> fix(ui-form-field): update form error message color to have better contrast

- package-lock.json
- packages/ui-options/package.json
- packages/ui-options/tsconfig.build.json
Some bundlers or package managers (`pnpm`? `vite`?) error out with an error that `isAndroidOrIOS` is missing from the build. Its added to `ui-options` in a transitive dependency (`ui-react-utils` -> `ui-utils`), which should work, but it does not. This is an attempt to fix this issue
> fix(ui-options): fix isAndroidOrIOS missing error for some bundlers

- packages/__docs__/src/ComponentTheme/index.tsx
- packages/__docs__/src/Document/index.tsx
- packages/__docs__/src/Document/props.ts
TEST_PLAN:
go to the docs app and navigate to any component's docs page. Check the default theme variables section. Change the theme. Observe that the color variables are changing.
Test Avatar (only functional component currently) and any other component with default theme colors
closes: INSTUI-4497
> Fix docs theme not respecting theme change

- packages/__docs__/functionalComponentThemes.ts
- packages/__docs__/src/ComponentTheme/index.tsx
- packages/__docs__/src/Document/index.tsx
- packages/__docs__/src/Document/props.ts
TEST_PLAN: Check Avatar (the only functional component at the moment) if it has the proper default themes block on it's docs page. Also check couple of others to check if they still have it
Closes: INSTUI-4493
> docs: fix missing default component theme block in functional component doc pages

- packages/shared-types/src/BaseTheme.ts
- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-link/src/Link/README.md
- packages/ui-link/src/Link/index.tsx
- packages/ui-link/src/Link/props.ts
- packages/ui-link/src/Link/styles.ts
- packages/ui-link/src/Link/theme.ts
- packages/ui-text/src/Text/index.tsx
- packages/ui-themes/src/sharedThemeTokens/borders.ts
- packages/ui-themes/src/sharedThemeTokens/breakpoints.ts
- packages/ui-themes/src/sharedThemeTokens/forms.ts
- packages/ui-themes/src/sharedThemeTokens/media.ts
- packages/ui-themes/src/sharedThemeTokens/shadows.ts
- packages/ui-themes/src/sharedThemeTokens/spacing.ts
- packages/ui-themes/src/sharedThemeTokens/stacking.ts
- packages/ui-themes/src/sharedThemeTokens/transitions.ts
- packages/ui-themes/src/sharedThemeTokens/typography.ts
TEST_PLAN:
Check the [ticket](https://instructure.atlassian.net/browse/INSTUI-4506) and if it's criteria is met. Check the README and if the explanation is it's understandable
INSTUI-4506
> feat(ui-link): add variants to <Link>

- packages/__docs__/src/Theme/index.tsx
test plan: 
- theme pages should load (e.g. `/#canvas`)
> docs: fix regression in docs page themes section

- packages/ui-focusable/src/Focusable/README.md
tooltips should use aria-describedby.
To test: check the first Focusable example in VoiceOver and NVDA. It should read the tooltip
Fixes INSTUI-4313
> fix(ui-focusable): fix Focusable example using the wrong ARIA tag

- packages/ui-modal/src/Modal/ModalHeader/theme.ts
INSTUI-4528
**Test**
1. Create a Modal with the `variant` prop set to `inverse`
2. Observe if the background color (of all Modal parts: Modal, Modal.Header, Modal.Footer) is `grey100100`
> fix(ui-modal): set inverseBackground to grey100100

- packages/__docs__/src/Preview/styles.ts
- packages/ui-select/src/Select/README.md
- packages/ui-select/src/Select/index.tsx
- packages/ui-simple-select/src/SimpleSelect/index.tsx
- packages/ui-time-select/src/TimeSelect/index.tsx
INSTUI-4428
**ISSUE:**
- Select does not work properly on iOS with Voiceover. After opening the listbox by double tapping on the input field, the listbox closes when the user try to swipe right to jump from the input to the listbox items
**TEST PLAN:**
- make sure you have the latest iOS update
- test the examples in Select, SimpleSelect, TimeSelect, DateTimeInput, Table (sortable responsive), Calendar (with yearpicker) examples **with VoiceOver on iPad and/or iPhone**
- open the listbox by double tapping on the input field and swipe right
- you should be able to jump to a listbox item after swiping right
- the listbox should remain open after swiping right
- you should be able to navigate through the listbox items by swiping left and right
- after double tapping on a list item, the focus …
> fix(many): make Select accessible for iOS VoiceOver

- packages/__docs__/src/CodeSandboxButton/index.tsx
- packages/ui-table/src/Table/Head/index.tsx
- packages/ui-table/src/Table/README.md
- packages/ui-table/src/Table/__new-tests__/Table.test.tsx
- fix table crashing in stacked layout when using falsy children
- a `Table` example that was using `Children` instead of `React.Children`
- CodeSandboxes crashing because missing imports.
- Make CodeSandbox examples nicer by only importing samples when needed
Fixes INSTUI-4534
To test:
1. try this code in this PR, it should not crash:
```
<Table caption="Test table" layout="stacked">
<Table.Head>
{/* @ts-expect-error error is normal here */}
<Table.Row>
<Table.Cell>Foo</Table.Cell>
{}
{false}
</Table.Row>
</Table.Head>
<Table.Body>
<Table.Row>
<Table.RowHeader>1</Table.RowHeader>
<Table.Cell>The Shawshank Redemption</Table.Cell>
<Table.Cell>1994</Table.Cell>
<Table.Cell>9.3</Table.Cell>
</Table.Row>
<Table.Row>
<Table.RowHeader>2</Table.RowHeader>
<Table.Cell>The Godfather</Table.Cell> …
```
> fix(ui-table): fix table crashing in stacked layout when using falsy children

- packages/ui-avatar/src/Avatar/__new-tests__/Avatar.test.tsx
- packages/ui-avatar/src/Avatar/index.tsx
- packages/ui-date-input/src/DateInput2/__new-tests__/DateInput2.test.tsx
- packages/ui-date-input/src/DateInput2/index.tsx
This is needed for things that try to access the `ref` prop, like our [Transition](https://github.com/instructure/instructure-ui/blob/7226e21d53f5e36820440205bfc2e269281e47bd/packages/ui-motion/src/Transition/BaseTransition/index.ts#L342) or [Position](https://github.com/instructure/instructure-ui/blob/7226e21d53f5e36820440205bfc2e269281e47bd/packages/ui-position/src/Position/index.tsx#L295) package.
Also we have a page asking users to add the `ref` prop, see https://instructure.design/#accessing-the-dom
Finally in React 19 this code will be much simpler, see https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop 
To test: check is `Transition`, `Position` works with `Avatar` and `DateInput2`
Fixes INSTUI-4520
> fix(ui-date-input,ui-avatar): add ref support to functional components

- packages/ui-view/src/View/theme.ts
TEST PLAN: check if the colors of View is in sync with the design docs
https://docs.google.com/spreadsheets/d/16_GjG_LvCvvvkdvFNTcrC11P81GwwSRyWGxKbc5RWeE/edit?gid=0#gid=0
INSTUI-4532
> style(ui-view): improve view border colors

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-modal/src/Modal/README.md
- packages/ui-modal/src/Modal/theme.ts
The theme variable was not used anywhere.
To test: Check if the new recommendation to change z-index in the docs works
Fixes INSTUI-4536
> refactor(ui-modal,shared-types): remove unused theme variable, add docs on how to change Modal's z-index

- package-lock.json
- packages/ui-scripts/lib/build/generate-all-tokens.js
- packages/ui-scripts/lib/utils/handle-generate-tokens.js
- packages/ui-scripts/package.json
The debug statements help to investigate flaky CI builds that fail.
Also remove `fse`, since the error seems to be that `styleDictionarySource` is not created  in some cases
Trying to fix errors like
```
scss
✔︎ /home/runner/work/instructure-ui/instructure-ui/packages/canvas-high-contrast-theme/tokens/scss/_variables.scss
scss
✔︎ /home/runner/work/instructure-ui/instructure-ui/packages/canvas-theme/tokens/scss/_variables.scss
scss
✔︎ /home/runner/work/instructure-ui/instructure-ui/packages/ui-theme-tokens/tokens/canvas/scss/_variables.scss
scss
✔︎ /home/runner/work/instructure-ui/instructure-ui/packages/ui-themes/tokens/canvas/scss/_variables.scss
/home/runner/work/instructure-ui/instructure-ui/node_modules/json5/lib/parse.js:1110
const err = new SyntaxError(message)
^
SyntaxError: Failed …
```
> Attempt to fix 'JSON5: invalid end of input' build error in CI

- packages/ui-checkbox/src/Checkbox/props.ts
- packages/ui-radio-input/src/RadioInputGroup/props.ts
Since these were not added to `allowedProps`, they were not excluded by `omitProps`, so they were added to native DOM elements resulting in this warning.
To test: Add the `isRequired` prop to `RadioInputGroup` and `CheckBox` in a local build. Observe that there are no console warnings and the asterisk is added
Fixes INSTUI-4531
> fix(ui-radio-input,ui-checkbox): fix 'React does not recognize the isRequired prop on a DOM element' on RadioInputGroup and Checkbox

- packages/ui-flex/src/Flex/README.md
- packages/ui-view/src/View/README.md
- packages/ui-view/src/View/__new-tests__/View.test.tsx
- packages/ui-view/src/View/props.ts
- packages/ui-view/src/View/styles.ts
The main change is to use CSS `outline` instead of an absolute positioned `:before` element. This has the following effects:
`+` Now focus ring is not part of the size calculation, so there will be no scrollbars e.g. if the `overflow` is set to `auto` in some parent element.
`+` `View` now can display focus rings even if its `position` is not `absolute`
`+` Page CSS and code became simpler since we are not using `:before` CSS pseudo tags
`+` Focus ring will follow fancy `border` settings (see `View`'s focus ring examples)
`~` The focus animation is very slightly different. (the old one was using `scale`, this uses `outline-offset`)
`-` We were using the `outline` prop to display the debug border with the `withVisualDebug` prop. To fix this conflict the debug border now uses box-shadow; …
> Rewrite focus ring logic in `View`

- packages/ui-select/src/Select/README.md
INSTUI-4539
IISSUE:
- the line handling the input blur isn't in the right place
- handling the inputRef with states is not a good practice
TEST PLAN:
- check the class and functional examples on iPad/iPhone with VoiceOver, the focus should be returned to the input field after selecting an option
- functional examples should handle inputRef with useRef
> docs(ui-select): fix_focus_input_function_in_select_examples

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-buttons/src/BaseButton/props.ts
- packages/ui-buttons/src/BaseButton/styles.ts
- packages/ui-buttons/src/BaseButton/theme.ts
- packages/ui-buttons/src/Button/README.md
- packages/ui-buttons/src/Button/props.ts
- packages/ui-buttons/src/IconButton/README.md
- packages/ui-buttons/src/IconButton/props.ts
TEST_PLAN: compare with design documentation
INSTUI-4546
> feat(ui-buttons,shared-types): add ai-primary and ai-secondary colors to buttons

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-heading/src/Heading/README.md
- packages/ui-heading/src/Heading/props.ts
- packages/ui-heading/src/Heading/styles.ts
- packages/ui-heading/src/Heading/theme.ts
TEST_PLAN: compare with design documentation
INSTUI-4550
> feat(ui-heading,shared-types): add ai color

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-text/src/Text/README.md
- packages/ui-text/src/Text/props.ts
- packages/ui-text/src/Text/styles.ts
- packages/ui-text/src/Text/theme.ts
TEST_PLAN: compare with design documentation
INSTUI-4547
> feat(ui-text,shared-types): add ai-highlight color

- packages/ui-checkbox/src/Checkbox/ToggleFacade/styles.ts
INSTUI-4553
Test:
1. Check if pointer cursor disappears when hovering over a disabled checkbox (toggle variant)
Example code to use:
`<Checkbox disabled label="Toggle Checkbox" variant="toggle" />`
> fix(ui-checkbox): remove pointer cursor from disabled checkbox toggle

- packages/ui-alerts/src/Alert/index.tsx
The Alert component accepts onDismiss, but it's passing this down to a div element that doesn't
recognize it, which is causing the warning.
> fix(ui-alerts): stop passing onDismiss to div in Alert

- .github/workflows/visual-regression.yml
- packages/ui-alerts/src/Alert/README.md
- packages/ui-alerts/src/Alert/index.tsx
- packages/ui-alerts/src/Alert/props.ts
- packages/ui-alerts/src/Alert/styles.ts
INSTUI-4533
test plan:
- open the alert component's page in the docs and go through with screenreader -> it should announce the type of the alert
> fix(ui-alerts): add variantScreenReaderLabel prop to Alert to improve screenreader usability

- cypress.config.ts
- cypress/component/DateInput2.cy.tsx
- cypress/component/Dialog.cy.tsx
- cypress/component/Modal-test-1.cy.tsx
- cypress/component/Modal-test-2.cy.tsx
- cypress/component/Popover.cy.tsx
- cypress/component/TextArea.cy.tsx
> INSTUI-4542 Improve Cypress test stability for low-resource environments

- packages/ui-tabs/src/Tabs/styles.ts
INSTUI-4562
Test:
1. Check if a vertical scrollbar is not present on a Tabs component with props `variant` set to `secondary` and `tabOverflow` set to `scroll`
> fix(ui-tabs): remove scrollbar from tabs

- packages/ui-avatar/src/Avatar/theme.ts
- packages/ui-heading/src/Heading/theme.ts
- packages/ui-radio-input/src/RadioInputGroup/theme.ts
- packages/ui-side-nav-bar/src/SideNavBar/SideNavBarItem/theme.ts
> fix(many): fix access of colors from theme

- packages/ui-drilldown/src/Drilldown/__new-tests__/Drilldown.test.tsx
- packages/ui-drilldown/src/Drilldown/index.tsx
- packages/ui-select/src/Select/__new-tests__/Select.test.tsx
- packages/ui-select/src/Select/index.tsx
- packages/ui-tabs/src/Tabs/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/index.tsx
The issue is that we are letting users choose any string as an ID, and the querySelector method only accepts CSS safe IDs. Luckily there is a built in method to escape stuff that it does not like
Fixes INSTUI-4570
To test:
- This code should not throw errors:
```
const options = ["Option 1", 'Option 2 with " inside']
render(
<SimpleSelect renderLabel="Uncontrolled Select">
{options.map((option) => (
<SimpleSelect.Option id={option} value={option}>
{option}
</SimpleSelect.Option>
))}
</SimpleSelect>
)
```
- In the 'Video Settings' Drilldown example make an option's ID contain a double quote ("). when hovering over it the example should not crash
> fix(many): fix "not a valid selector" exception when an option ID contains quotes

- packages/ui-date-input/src/DateInput2/index.tsx
- packages/ui-i18n/src/Locale.ts
- packages/ui-i18n/src/getLocale.ts
- packages/ui-i18n/src/getTimezone.ts
INSTUI-4571
test plan:
- check all examples for dateinput2, they should work as expected
- input a date manually (with keyboard) for each example and blur the input -> it should parse the date successfully
- placeholder hints should not have any number in them, just `D`, `M` and `Y` letters
- use chrome devtools and change your location (3 dots -> more tools -> sensors -> location)
- check the component examples again with different locales
- check if manually changing locale and timezone works as expected
> fix(ui-date-input): make DateInput2 date parsing work in every locale and timezone

- packages/ui-buttons/src/BaseButton/index.tsx
INSTUI-4527
**ISSUE:**
- In Safari, the same BaseButton or Button component doesn't show a focus ring, whereas the ring does appear in Chrome and other browsers - this is due to a missing 0 tabindex, which Safari needs
- Modal trigger button does not have a focus ring after closing the Modal due to this
**TEST PLAN:**
- make sure you have the latest Safari version
- open BaseButton and Button pages **in Safari**
- the first few examples should get a focus ring when they are clicked on - unlike in the latest InstUI release in Safari
- they should have a tabIndex=0 in Safari but not in other browsers
- open the first example of Modal **in Safari,** after closing it, the Modal should have a focus ring - unlike in the latest InstUI release in Safari
> fix(ui-buttons): make Button have a focus ring in Safari

- packages/ui-checkbox/src/Checkbox/__new-tests__/Checkbox.test.tsx
- packages/ui-checkbox/src/Checkbox/index.tsx
- packages/ui-checkbox/src/Checkbox/props.ts
- packages/ui-color-picker/src/ColorPicker/__new-tests__/ColorPicker.test.tsx
- packages/ui-color-picker/src/ColorPicker/index.tsx
- packages/ui-color-picker/src/ColorPicker/props.ts
- packages/ui-radio-input/src/RadioInput/__new-tests__/RadioInput.test.tsx
- packages/ui-radio-input/src/RadioInput/index.tsx
- packages/ui-radio-input/src/RadioInput/props.ts
- packages/ui-range-input/src/RangeInput/__new-tests__/RangeInput.test.tsx
- packages/ui-range-input/src/RangeInput/index.tsx
- packages/ui-range-input/src/RangeInput/props.ts
INSTUI-4400
**ISSUE:**
- some components (e.g., RadioInput, Checkbox) that use an input field are missing the inputRef prop.
**TEST PLAN:**
- copy the code below to the preview
- click on each of the five "Focus' buttons
- the corresponding input field should get focused
- review the tests
```
class FocusExample extends React.Component {
radioElement = null;
checkboxElement = null;
checkboxToggleElement = null;
rangeInputElement = null;  
colorElement = null;
focusRadio = () => {
if (this.radioElement) {
this.radioElement.focus();
}
};
focusCheckbox = () => {
if (this.checkboxElement) {
this.checkboxElement.focus();
}
};
focusCheckboxToggle = () => {
if (this.checkboxToggleElement) {
this.checkboxToggleElement.focus();
}
};
focusRangeInput = () => { 
if (this.rangeInputElement) { …
```
> feat(many): add missing inputRef prop to input components

- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarBrand/styles.ts
The root cause was that now View uses the CSS outline prop to display its focus ring, but it was overridden here
To test: Check the TopNavBarBrand example in the docs app it should not flash an outline on hover
Fixes: INSTUI-4585
> fix(ui-top-nav-bar): fix TopNavBarBrand flashing an outline on hover

- packages/ui-color-utils/tsconfig.build.json
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarItem/index.tsx
The issue was likely that TopNavBarItem did not enter the focused state because its rerendered a lot. This fix does not use the onFocus React event rather sets withFocusoutline to undefined so the focus ring is added via CSS
This PR also fixes a strange build error, that checkTSReferences was failing with a JSON parse error.
To test: Check the TopNavBar examples. Menu items should be in focus when their dropdown is open and when it gets closed (e.g. by pressing ESC) 
Fixes INSTUI-4587
> fix(ui-top-nav-bar): fix focus ring not showing when closing a dropdown

- packages/__docs__/src/Nav/index.tsx
- packages/__docs__/src/Nav/props.ts
INSTUI-4243
**ISSUE:**
- search results in documentation's side navigation are not announced
**TEST PLAN:**
- navigate to the "Find…" search bar in the side navigation using different screen readers
- type a search term (e.g., "color" or "select")
- the screen reader should:
- announce the number of results available
- clearly indicate when no results are available
> chore: announce search results in side navigation

- packages/ui-heading/src/Heading/README.md
- packages/ui-heading/src/Heading/index.tsx
- packages/ui-heading/src/Heading/props.ts
TEST_PLAN:  Check if all the variants still set the `h` tags as before, but if level is set, it overrides the defaults.
Also check the wording and completeness of the docs
INSTUI-4612
> feat(ui-heading): enable setting level for headings with variant

- packages/ui-select/src/Select/index.tsx
INSTUI-4361
**ISSUE:**
- in Chrome, Select starts scrolling when the bottom area of the last visible item is hovered and `scrollToHighlightedOption` is true
**TEST PLAN:**
- open the examples in Select in Chrome
- open the listbox and start hovering around the bottom edge of the last item and the listbox
- it should not scroll to the next item (like it does in the current version)
> fix(ui-select): prevent scrolling when last item is hovered in Chrome

- packages/ui-dom-utils/src/findFocusable.ts
- packages/ui-modal/src/Modal/ModalBody/index.tsx
- packages/ui-modal/src/Modal/ModalBody/props.ts
The issue was that its not recognized by `findFocusable` as a focusable element. Recently browsers have made scrollable elements focusable, but there is no sure way to know that a scrollbar is displayed, an easy workaround is to add the `tabIndex=0` prop.
Note that this breaks VoiceOver a bit, its not able to navigate the inside of a scrollable container with SR focus
To test: Make a modal with lots of text, make the browser window really small so the modal has a scrollbar. Keyboard focus trapping should work properly
Fixes INSTUI-4625
> fix(ui-modal,ui-dom-utils): fix Modal focus trap broken when it has a scrollbar

- packages/ui-text-input/src/TextInput/styles.ts
INSTUI-4628
the issue was caused by the previous solutions reliance on the `data-cid` prop which is not present in prod
test plan:
- check DateInput2 -> icon button should not have a padding on the right
- check the code
> fix(ui-text-input): better IconButton positioning inside TextInput when wrapped inside a Popover

- packages/__docs__/buildScripts/build-docs.mts
- packages/__docs__/buildScripts/utils/getJSDoc.mts
- packages/debounce/src/debounce.ts
- packages/emotion/src/getComponentThemeOverride.ts
- packages/ui-color-utils/src/alpha.ts
- packages/ui-color-utils/src/contrast.ts
- packages/ui-color-utils/src/conversions.ts
- packages/ui-color-utils/src/validateContrast.ts
- packages/ui-dom-utils/src/handleMouseOverOut.ts
- packages/ui-react-utils/src/ensureSingleChild.tsx
- packages/ui-react-utils/src/getDisplayName.ts
- packages/ui-react-utils/src/getElementType.ts
- packages/ui-react-utils/src/getInteraction.ts
- packages/ui-react-utils/src/matchComponentTypes.ts
- packages/ui-react-utils/src/pickProps.ts
- packages/ui-utils/src/createChainedFunction.ts
The new parsing algorithm was wrong for cases like `const f = () => {}`. This patch fixes it.
To test: compare the docs of the utilities, some e.g. https://instructure.design/#contrastWithAlpha should have more function param information
> refactor(many): fix docs parsing for arrow functions

- packages/ui-modal/src/Modal/ModalBody/index.tsx
TEST_PLAN:
-  check if tabbing works ok in general through a modal
- make sure you can't tab to the modal body if it has no scrollbar
- make sure you can tab to the modal body if it has scrollbar
INSTUI-4648
> fix(ui-modal): remove tabbability from modalBody if there is no scrollbar

- packages/ui-color-picker/src/ColorPreset/index.tsx
TEST_PLAN:
Check if `ColorPreset`'s buttons have the `type="button"` attribute
INSTUI-4647
> feat(ui-color-picker): add type=button to color preset's buttons for better form handling

- packages/__docs__/src/ComponentTheme/index.tsx
- packages/__docs__/src/Params/index.tsx
- packages/__docs__/src/Properties/index.tsx
- packages/ui-table/src/Table/Row/props.ts
- packages/ui-table/src/Table/__tests__/Table.test.tsx
- allow falsy children for Table.Row, this makes it possible to use `{condition && <Table.Cell>bla</Table.Cell>}`
- sort docs params and theme variables by name
- Do not render the 'default' column in docs if nothing has a default value
To test: check if the props/theme variables are sorted for components; check if the "default" colunm is not displayed for components and utility functions
> Small fixes for props/theme variables/params in docs

- packages/ui-svg-images/src/InlineSVG/index.tsx
- packages/ui-svg-images/src/InlineSVG/props.ts
- packages/ui-svg-images/src/SVGIcon/README.md
Firefox interprets unitless width/height values as undefined when they are strings, e.g. width="100" This fix converts numerical string values like "3.5" to number to make FF happy
To test:
Test `SVGIcon` with various widht/height values in FF/Safari/Chrome in the docs app:
```
<div>
<SVGIcon src={iconExample} title="love" width='100' height='100' />
<SVGIcon src={iconExample} title="love" width='100px' height='100px' />
<SVGIcon src={iconExample} title="love" width='2.5rem' height='2.5rem' />
<SVGIcon src={iconExample} title="love" width={100} height={100} />
</div>
```
Fixes INSTUI-4650
> fix(ui-svg-images): fix Firefox discarding numeric width/height values

- packages/ui-motion/src/Transition/styles.ts
The issue was that View's focus ring CSS had stronger specificity
To test: Check Transition examples, they should animate
Fixes INSTUI-4652
> fix(ui-motion): fix Transitions not working on focusable elements

- packages/shared-types/src/ComponentThemeVariables.ts
- packages/ui-tag/src/Tag/README.md
- packages/ui-tag/src/Tag/styles.ts
- packages/ui-tag/src/Tag/theme.ts
Remove maxWidth style variable from Tag:
The full text content of the Tag should always be visible on the documentation page:
https://instructure.design/#Tag/#Sizes
`<Tag
text="Long string of text designed to trigger overflow"
/>`
> chore(ui-tag)Remove maxWidth from tag

- packages/ui-react-utils/src/safeCloneElement.ts
the issue was that in React 18 or earlier if one tries to access props.ref it will emit this warning. This PR changes it so its only accessed if the React version number is 19 or above
To test: Launch app locally so you see the error messages. Component pages like Tooltip should not have any `Warning: [object Object]: ref is not a prop. Trying to access it will result in undefined being returned.` error messages
Fixes INSTUI-4664
> fix(ui-react-utils): fix "ref is not a prop" warning spam

- packages/ui-drilldown/src/Drilldown/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarLayout/SmallViewportLayout/__tests__/TopNavBarSmallViewportLayout.test.tsx
- packages/ui-top-nav-bar/src/TopNavBar/TopNavBarMenuItems/index.tsx
- packages/ui-top-nav-bar/src/TopNavBar/utils/mapItemsForDrilldown.tsx
notes:
react 19 only supposed to get rid of `defaultProps` for functional components, however after the update it broke in multiple different class components. my best guess is the `withStyle` decorator which should "forward" the default props but maybe it isn't anymore? I don't know and I wasn't able to find out or verify...
test plan:
- all vitest tests should be green
- check the code. it's not pretty, feels a bit hacky, what do you think? could it be improved?
> fix last 3 failing tests after react 19 upgrade

- packages/ui-form-field/src/FormFieldLayout/styles.ts
TEST_PLAN:
try setting a `FormField` `messages` prop  with a `screenreader-only` message and check if the visuals change from a `FormField` without any `messages`. 
(add this prop for example: `messages={[{ text: "announcement", type: 'screenreader-only' }] }`)
Check if any other view of `FormField` has changed
INSTUI-4673
> fix(ui-form-field): should not change layout when only screenreader-only message is present

- packages/ui-table/src/Table/Body/index.tsx
- packages/ui-table/src/Table/ColHeader/props.ts
- packages/ui-table/src/Table/Head/index.tsx
- packages/ui-table/src/Table/Row/index.tsx
Remove deprecated prop passing down and use TableContext instead.
Test:
Check the Table Compnent if its working as before
> INSTUI-4592 feat(ui-table): remove deprecated prop from Table

- cypress/component/Focusable.cy.tsx
- cypress/component/Tray.cy.tsx
- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-a11y-utils/src/FocusRegionOptions.ts
- packages/ui-dialog/src/Dialog/props.ts
The issue occurred in the following conditions:
1. A non-keyboard focusable element is added to the top of the stack,e.g. an Overlay with just text
2. The keyboard focusable element is removed from the stack just below it. In this case the focus region stayed the now removed element getting the focus stuck
To test:
- Run the code in the Cypress test locally
- Test out ALL the examples that use popovers/modals. Play with their popover settings like `shouldReturnFocus`, `shouldCloseOnDocumentClick`, `shouldContainFocus`
Fixes INSTUI-4685
> fix(ui-dialog,ui-a11y-utils): fix focus getting stuck in some cases if something is removed from the middle of the focus stack

- packages/ui-menu/src/Menu/MenuItem/styles.ts
Remove fade in/out transitions from menu items.
Test:
On the Menu documentation page confirm there is no highlight transition when hovering or focusing on a menu item.
> INSTUI-4679 feat(ui-menu): remove fade transitions from menu items

- docs/contributor-docs/ai-features.md
- docs/contributor-docs/contributing.md
- docs/getting-started/accessibility.md
- docs/getting-started/theming-components.md
- docs/getting-started/usage.md
- docs/guides/accessing-the-dom.md
- docs/guides/color-system.md
- docs/guides/focus-management.md
- docs/guides/form-errors.md
- docs/guides/layout-spacing.md
- docs/guides/module-federation.md
- docs/guides/server-side-rendering.md
- docs/guides/typography-system.md
- docs/guides/using-theme-overrides.md
- docs/patterns/ContentAlignment.md
- docs/patterns/DestroyAction.md
- docs/patterns/Search.md
- docs/patterns/UsingIcons.md
- packages/__docs__/buildScripts/ai-accessible-documentation/generate-ai-accessible-llms-file.mts
- packages/__docs__/buildScripts/ai-accessible-documentation/generate-ai-accessible-markdowns.mts
- packages/__docs__/buildScripts/ai-accessible-documentation/summaries-for-llms-file.json
- packages/__docs__/buildScripts/build-docs.mts
INSTUI-4701
ISSUE:
- InstUI lacks an ai-friendly documentation
TEST PLAN:
- check https://instructure.design/pr-preview/pr-2109/llms.txt it should open contain all necessary sections, components and guides and each link should be followed by a short summary of that guide/component
- the links in the llms.txt should redirect to existing markdown files, these should include every information and in the case of components, examples, prop tables and usage, in the case of sub-components like Tabs.Panel in Tabs, the prop table should include the props of the sub-component
- check the structure and section hierarchy of the llms.txt file and the markdown files, they should be error-free
- check https://instructure.design/pr-preview/pr-2109/markdowns/documentation.zip , it should download a …
> build: generate llms.txt and markdown files of the documentation for optimal AI consumption

- packages/ui-radio-input/src/RadioInput/index.tsx
INSTUI-4715
**ISSUE:**
- RadioInput has disabled and aria-disabled='true' attributes at the same time, which is unnecessary
**TEST PLAN:**
- test the examples below with different screenreader (VoiceOver/NVDA/JAWS), browser (Chrome/Safari/Firefox) and operating system (Mac/Windows) combinations
- screenreader announcement and behaviour for the disabled and readOnly RadioInputs should not differ from the ones in the current release (etc. should announced as dimmed/unavailable, selected)
- inspect the HTML, input with disabled attribute should not have the aria-disabled attribute
- examples in RadioInputGroup should behave the same
```
<FormFieldGroup description={<ScreenReaderContent>Toggle examples</ScreenReaderContent>}>
<RadioInputGroup
name="fruits1"
defaultValue="apple" …
```
> fix(ui-radio-input): remove aria-disabled from RadioInput

- packages/ui-a11y-utils/src/FocusRegion.ts
- packages/ui-a11y-utils/src/__tests__/FocusRegion.test.tsx
- packages/ui-drawer-layout/src/DrawerLayout/DrawerTray/props.ts
The issue was that DrawerLayout updates the FocusRegion when opening multiple times by changing the value of `shouldCloseOnEscape` (by calling `updateElement`), but FocusRegion is not adding/removing event listeners when its options change. Also add unit tests for FocusRegion (AI generated)
To test:
check if the DrawerLayout examples close when ESC is pressed. They should not close if `shouldCloseOnEscape` is set to `false`
fixes: INSTUI-4731
> fix(ui-drawer-layout,ui-a11y-utils): fix DrawerLayout not closing on ESC keypress

- packages/ui-drilldown/src/Drilldown/DrilldownPage/props.ts
- packages/ui-drilldown/src/Drilldown/index.tsx
INSTUI-4688
**ISSUE:**
- including an optional Option (e.g.: {someBool && renderAnOption()}) as child of DrillDown.Page now result in type error
**TEST PLAN:**
- open the brach locally
- create the file with the code below in your InstUI codebase
- {someBool && renderAnOption()}) or {someBool ? renderAnOption() : null} should not get a TypeScipt type error in your IDE
```
import React from 'react'
import Drilldown from '.'
import { createRoot } from 'react-dom/client'
const Example = () => {
const [someBool] = React.useState(true)
const renderAnOption = () => (
<Drilldown.Option id="conditionalOption">
Conditional Option
</Drilldown.Option>
)
return (
<Drilldown rootPageId="root" width="20rem" maxHeight="30rem">
<Drilldown.Page id="root">
<Drilldown.Option …
```
> feat(ui-drilldown): make Drilldown.Page handle optional Options

- packages/ui-buttons/src/BaseButton/styles.ts
INSTUI-4751
Test:
Check buttons doc page and the focus ring on buttons with prop shape="circle"
> fix(ui-buttons): fix focus ring distortion on circle shape buttons

- packages/ui-drilldown/src/Drilldown/DrilldownGroup/__tests__/DrilldownGroup.test.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownOption/__tests__/DrilldownOption.test.tsx
- packages/ui-drilldown/src/Drilldown/DrilldownPage/__tests__/DrilldownPage.test.tsx
- packages/ui-drilldown/src/Drilldown/__tests__/Drilldown.test.tsx
- packages/ui-drilldown/src/Drilldown/index.tsx
INST-UI4752
Add fix for prevent option selection when Drilldown or its sub-components get disabled prop.
Test plan:
Go to Drilldown doc page and at the Disabled prop section ensure that its work as expected in all sub-component level
> fix(ui-drilldown): fix Drilldown for prevent option selection when disabled
